export enum GuidedSelfCheckReviewStatus { PENDING='PENDING', ASSIGNED='ASSIGNED', IN_REVIEW='IN_REVIEW', COMPLETED='COMPLETED', CANCELLED='CANCELLED' }
export enum GuidedSelfCheckReviewPriority { ROUTINE='ROUTINE', URGENT='URGENT' }
export enum GuidedSelfCheckReviewOrigin { CLASSIFICATION_REQUIRED='CLASSIFICATION_REQUIRED', QA_SAMPLE='QA_SAMPLE' }
export enum GuidedSelfCheckReviewDecision { NO_FURTHER_REVIEW_REQUIRED='NO_FURTHER_REVIEW_REQUIRED', FOLLOW_UP_RECOMMENDED='FOLLOW_UP_RECOMMENDED', PATIENT_CONTACT_REQUIRED='PATIENT_CONTACT_REQUIRED', URGENT_ESCALATION_CONFIRMED='URGENT_ESCALATION_CONFIRMED' }
export enum GuidedSelfCheckContactStatus { NOT_REQUIRED='NOT_REQUIRED', REQUIRED='REQUIRED', CONTACTED='CONTACTED' }
export enum GuidedSelfCheckReviewEvent { REVIEW_CREATED='REVIEW_CREATED', REVIEW_ASSIGNED='REVIEW_ASSIGNED', REVIEW_REASSIGNED='REVIEW_REASSIGNED', REVIEW_STARTED='REVIEW_STARTED', REVIEW_COMPLETED='REVIEW_COMPLETED', REVIEW_CANCELLED='REVIEW_CANCELLED' }
