export enum GuidedSelfCheckAnalysisStatus { PENDING='PENDING',PROCESSING='PROCESSING',COMPLETED='COMPLETED',FAILED='FAILED' }
export enum GuidedSelfCheckAnalysisEvent { ANALYSIS_REQUESTED='ANALYSIS_REQUESTED',ANALYSIS_STARTED='ANALYSIS_STARTED',ANALYSIS_COMPLETED='ANALYSIS_COMPLETED',ANALYSIS_FAILED='ANALYSIS_FAILED' }
export enum GuidedSelfCheckAnalysisFailureCode { PROVIDER_UNAVAILABLE='PROVIDER_UNAVAILABLE',TIMEOUT='TIMEOUT',INVALID_OUTPUT='INVALID_OUTPUT',PROCESSING_ERROR='PROCESSING_ERROR' }
export enum GuidedSelfCheckAnalysisPriority { ROUTINE='ROUTINE',ELEVATED='ELEVATED' }
