export enum GuidedSelfCheckReviewerAuthorizationStatus { AUTHORIZED='AUTHORIZED', DISABLED='DISABLED' }
export enum GuidedSelfCheckReviewerAuthorizationEvent { REVIEWER_AUTHORIZED='REVIEWER_AUTHORIZED', REVIEWER_REAUTHORIZED='REVIEWER_REAUTHORIZED', REVIEWER_DISABLED='REVIEWER_DISABLED' }
