export enum GuidedSelfCheckContactWorkItemStatus { PENDING='PENDING', ACKNOWLEDGED='ACKNOWLEDGED', IN_PROGRESS='IN_PROGRESS', COMPLETED='COMPLETED', CANCELLED='CANCELLED' }
export enum GuidedSelfCheckContactWorkItemOutcome { CONTACTED='CONTACTED', UNREACHABLE='UNREACHABLE', PATIENT_DECLINED='PATIENT_DECLINED', REFERRED_TO_CLINICAL_REVIEW='REFERRED_TO_CLINICAL_REVIEW' }
