export enum GuidedSelfCheckInternalClinicalProfessionalType {
  DOCTOR = 'DOCTOR',
  NURSE = 'NURSE',
  OTHER_CLINICAL_PROFESSIONAL = 'OTHER_CLINICAL_PROFESSIONAL',
}

export enum GuidedSelfCheckInternalClinicalProfessionalStatus {
  ACTIVE = 'ACTIVE',
  DISABLED = 'DISABLED',
}

export enum GuidedSelfCheckInternalClinicalCapability {
  SELF_CHECK_CLINICAL_REVIEW = 'SELF_CHECK_CLINICAL_REVIEW',
  URGENT_SELF_CHECK_REVIEW = 'URGENT_SELF_CHECK_REVIEW',
}

export enum GuidedSelfCheckInternalClinicalProfessionalEvent {
  INTERNAL_CLINICAL_PROFESSIONAL_AUTHORIZED = 'INTERNAL_CLINICAL_PROFESSIONAL_AUTHORIZED',
  INTERNAL_CLINICAL_PROFESSIONAL_DISABLED = 'INTERNAL_CLINICAL_PROFESSIONAL_DISABLED',
  CAPABILITY_GRANTED = 'CAPABILITY_GRANTED',
  CAPABILITY_REVOKED = 'CAPABILITY_REVOKED',
}
