export enum GuidedSelfCheckFundingStatus { UNPAID='UNPAID', PAYMENT_PENDING='PAYMENT_PENDING', PAID='PAID', SATISFIED_FREE='SATISFIED_FREE' }
export enum GuidedSelfCheckWorkflowStatus { NOT_STARTED='NOT_STARTED', IN_PROGRESS='IN_PROGRESS', COMPLETED='COMPLETED', CANCELLED='CANCELLED', EXPIRED='EXPIRED' }

