export enum HospitalBillPaymentStatus {
  PENDING = 'PENDING',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_RECEIVED_HOSPITAL_PENDING = 'PAYMENT_RECEIVED_HOSPITAL_PENDING',
  PAID = 'PAID',
  FAILED = 'FAILED',
}
