import { IsArray,IsBoolean,IsDateString,IsIn,IsInt,IsNotEmpty,IsOptional,IsString,IsUUID,Min } from 'class-validator';
export class CreateHmoDto { @IsString() @IsNotEmpty() name!:string; @IsString() @IsNotEmpty() code!:string; @IsOptional() @IsString() contact?:string; @IsOptional() @IsString() authorizationContact?:string; @IsOptional() @IsString() claimsContact?:string; @IsOptional() @IsIn(['API','PORTAL','MANUAL']) verificationMethod?:string; @IsOptional() @IsString() claimSubmissionMethod?:string; @IsOptional() @IsBoolean() active?:boolean; }
export class CreateHmoPlanDto { @IsUUID() hmoId!:string; @IsString() name!:string; @IsString() code!:string; }
export class UpsertCoverageDto { @IsUUID() patientId!:string; @IsUUID() hmoId!:string; @IsOptional() @IsUUID() planId?:string; @IsString() memberId!:string; @IsOptional() @IsString() policyNumber?:string; @IsOptional() @IsIn(['PRINCIPAL','DEPENDANT']) memberType?:string; @IsOptional() @IsString() employerOrganisation?:string; @IsOptional() @IsDateString() validFrom?:string; @IsOptional() @IsDateString() expiresAt?:string; }
export class CreateHmoCaseDto { @IsUUID() coverageId!:string; @IsString() careRequestReference!:string; @IsUUID() hospitalProviderId!:string; }
export class VerifyEligibilityDto { @IsIn(['ELIGIBLE','INELIGIBLE','EXPIRED','PENDING']) result!:string; @IsString() verificationReference!:string; @IsOptional() @IsString() notes?:string; }
export class RequestAuthorizationDto { @IsArray() requestedServices!:unknown[]; @IsOptional() @IsString() clinicalReason?:string; @IsOptional() @IsInt() @Min(0) requestedAmountMinor?:number; @IsOptional() @IsString() currency?:string; @IsOptional() @IsArray() supportingDocuments?:unknown[]; }
export class DecideAuthorizationDto { @IsIn(['APPROVED','PARTIALLY_APPROVED','REJECTED']) status!:string; @IsOptional() @IsString() authorizationCode?:string; @IsOptional() @IsArray() approvedServices?:unknown[]; @IsOptional() @IsInt() @Min(0) approvedAmountMinor?:number; @IsOptional() @IsInt() @Min(0) copayAmountMinor?:number; @IsOptional() @IsDateString() validUntil?:string; @IsOptional() @IsString() hmoComments?:string; }
export class ConfirmDeliveredServicesDto { @IsArray() deliveredServices!:unknown[]; }
export class SubmitClaimDto { @IsString() @IsNotEmpty() externalClaimReference!:string; }
export class RecordClaimPaymentDto { @IsInt() @Min(0) paidAmountMinor!:number; @IsOptional() @IsInt() @Min(0) approvedAmountMinor?:number; @IsOptional() @IsInt() @Min(0) platformFeeBps?:number; @IsString() @IsNotEmpty() paymentReference!:string; }
export class ReconcileClaimDto { @IsString() @IsNotEmpty() reconciliationReference!:string; }
