import { BadRequestException,ConflictException,Injectable,NotFoundException } from '@nestjs/common'; import { InjectRepository } from '@nestjs/typeorm'; import { Repository } from 'typeorm'; import { PatientAccessService } from '../patients/patient-access.service'; import { CareRequest } from '../care-requests/entities/care-request.entity'; import { Hmo } from './entities/hmo.entity'; import { HmoPlan } from './entities/hmo-plan.entity'; import { PatientHmoCoverage } from './entities/patient-hmo-coverage.entity'; import { HmoCase } from './entities/hmo-case.entity'; import { HmoAuthorization } from './entities/hmo-authorization.entity'; import { HmoClaim } from './entities/hmo-claim.entity'; import { CreateHmoCaseDto,CreateHmoDto,CreateHmoPlanDto,DecideAuthorizationDto,RequestAuthorizationDto,UpsertCoverageDto,VerifyEligibilityDto,ConfirmDeliveredServicesDto } from './hmo.dto';
@Injectable() export class HmoService { constructor(@InjectRepository(Hmo) private hmos:Repository<Hmo>,@InjectRepository(HmoPlan) private plans:Repository<HmoPlan>,@InjectRepository(PatientHmoCoverage) private coverages:Repository<PatientHmoCoverage>,@InjectRepository(HmoCase) private cases:Repository<HmoCase>,@InjectRepository(HmoAuthorization) private auths:Repository<HmoAuthorization>,@InjectRepository(HmoClaim) private claims:Repository<HmoClaim>,@InjectRepository(CareRequest) private cares:Repository<CareRequest>,private patientAccess:PatientAccessService){}
 listHmos(){return this.hmos.find({where:{active:true},order:{name:'ASC'}});} createHmo(d:CreateHmoDto){return this.hmos.save(this.hmos.create({...d,code:d.code.trim().toUpperCase()}));} createPlan(d:CreateHmoPlanDto){return this.plans.save(this.plans.create({...d,code:d.code.trim().toUpperCase()}));}
 async addCoverage(d:UpsertCoverageDto){const h=await this.hmos.findOneBy({id:d.hmoId,active:true});if(!h)throw new NotFoundException('HMO not found'); if(d.planId&&!await this.plans.findOneBy({id:d.planId,hmoId:d.hmoId,active:true}))throw new BadRequestException('Plan does not belong to HMO'); return this.coverages.save(this.coverages.create({...d,memberType:d.memberType||'PRINCIPAL'}));}
 async listMine(userId:string,patientReference:string){const p=await this.patientAccess.resolveAccessiblePatient(userId,patientReference);return this.listCoverages(p.id);} async addMine(userId:string,patientReference:string,d:Omit<UpsertCoverageDto,'patientId'>){const p=await this.patientAccess.resolveAccessiblePatient(userId,patientReference);return this.addCoverage({...d,patientId:p.id});}
 listCoverages(patientId:string){return this.coverages.find({where:{patientId},relations:{hmo:true,plan:true},order:{createdAt:'DESC'}});}
 async createCase(d:CreateHmoCaseDto){const coverage=await this.coverages.findOne({where:{id:d.coverageId},relations:{patient:true}});if(!coverage)throw new NotFoundException('Coverage not found');const care=await this.cares.findOneBy({reference:d.careRequestReference});if(!care)throw new NotFoundException('Encounter not found');if(care.patientId!==coverage.patientId)throw new ConflictException('Coverage and encounter belong to different patients');if(care.hostProviderId&&care.hostProviderId!==d.hospitalProviderId)throw new ConflictException('HMO hospital must match encounter host hospital');return this.cases.save(this.cases.create({coverageId:coverage.id,careRequestId:care.id,hospitalProviderId:d.hospitalProviderId,eligibilityStatus:'PENDING'}));}
 async verify(reference:string,d:VerifyEligibilityDto,userId:string){const c=await this.cases.findOne({where:{reference},relations:{coverage:true}});if(!c)throw new NotFoundException('HMO case not found');c.eligibilityStatus=d.result;c.eligibilityReference=d.verificationReference;c.eligibilityNotes=d.notes||null;c.eligibilityVerifiedAt=new Date();c.eligibilityVerifiedBy=userId;c.coverage.eligibilityStatus=d.result as any;c.coverage.lastVerifiedAt=c.eligibilityVerifiedAt;c.coverage.verificationReference=d.verificationReference;await this.coverages.save(c.coverage);return this.cases.save(c);}
 async requestAuthorization(reference:string,d:RequestAuthorizationDto){const c=await this.cases.findOneBy({reference});if(!c)throw new NotFoundException('HMO case not found');if(c.eligibilityStatus!=='ELIGIBLE')throw new ConflictException('Eligibility must be confirmed before authorization');return this.auths.save(this.auths.create({hmoCaseId:c.id,status:'PENDING',requestedServices:d.requestedServices,clinicalReason:d.clinicalReason||null,requestedAmountMinor:d.requestedAmountMinor==null?null:String(d.requestedAmountMinor),currency:d.currency||'NGN',supportingDocuments:d.supportingDocuments||[]}));}
 async decide(reference:string,d:DecideAuthorizationDto){const a=await this.auths.findOneBy({reference});if(!a)throw new NotFoundException('Authorization not found');a.status=d.status;a.authorizationCode=d.authorizationCode||null;a.approvedServices=d.approvedServices||[];a.approvedAmountMinor=d.approvedAmountMinor==null?null:String(d.approvedAmountMinor);a.copayAmountMinor=d.copayAmountMinor==null?null:String(d.copayAmountMinor);a.validUntil=d.validUntil?new Date(d.validUntil):null;a.hmoComments=d.hmoComments||null;if((d.status==='APPROVED'||d.status==='PARTIALLY_APPROVED')&&!a.authorizationCode)throw new BadRequestException('Authorization code is required for approval');return this.auths.save(a);}
 async confirmDelivery(reference:string,d:ConfirmDeliveredServicesDto,userId:string){const a=await this.auths.findOneBy({reference});if(!a)throw new NotFoundException('Authorization not found');if(!['APPROVED','PARTIALLY_APPROVED'].includes(a.status))throw new ConflictException('Only approved authorization can be delivered');if(!d.deliveredServices.length)throw new BadRequestException('At least one delivered service is required');a.deliveredServices=d.deliveredServices;a.serviceConfirmedAt=new Date();a.serviceConfirmedBy=userId;return this.auths.save(a);}
 async generateClaim(reference:string){const a=await this.auths.findOneBy({reference});if(!a)throw new NotFoundException('Authorization not found');if(!a.serviceConfirmedAt||!a.deliveredServices.length)throw new ConflictException('Delivered service confirmation is required before claim generation');const prior=await this.claims.findOneBy({authorizationId:a.id});if(prior)return prior;const amount=a.approvedAmountMinor||a.requestedAmountMinor;if(!amount)throw new ConflictException('Claim amount is unavailable');return this.claims.save(this.claims.create({authorizationId:a.id,status:'DRAFT',services:a.deliveredServices,claimedAmountMinor:amount,currency:a.currency}));}
 async desk(){return this.cases.find({relations:{coverage:{hmo:true,plan:true,patient:true},careRequest:true,hospitalProvider:true},order:{createdAt:'DESC'},take:200});}
 async funnel(){const cases=await this.cases.find();const auths=await this.auths.find();const claims=await this.claims.find();return {eligibility:cases.filter(x=>x.eligibilityStatus==='ELIGIBLE').length,authorization:auths.filter(x=>['APPROVED','PARTIALLY_APPROVED'].includes(x.status)).length,careCompleted:auths.filter(x=>!!x.serviceConfirmedAt).length,claimsSubmitted:claims.filter(x=>x.status!=='DRAFT'&&x.status!=='READY').length,paid:claims.filter(x=>x.status==='PAID').length,reconciled:0,primedRevenueMinor:'0'};}
}