import { INestApplication, UnauthorizedException, ValidationPipe } from '@nestjs/common';
import { Reflector } from '@nestjs/core';
import { Test } from '@nestjs/testing';
import * as request from 'supertest';
import { JwtAuthGuard } from '../src/auth/jwt-auth.guard';
import { RolesGuard } from '../src/auth/roles.guard';
import { AdminProviderCapabilitiesController } from '../src/providers/admin-provider-capabilities.controller';
import { AdminProviderLocationsController } from '../src/providers/admin-provider-locations.controller';
import { ProviderCapabilitiesService } from '../src/providers/provider-capabilities.service';
import { AdminProviderAvailabilityController } from '../src/providers/admin-provider-availability.controller';
import { ProviderAvailabilityService } from '../src/providers/provider-availability.service';
import { AdminProviderMatchingController } from '../src/providers/admin-provider-matching.controller';
import { ProviderMatchingService } from '../src/providers/provider-matching.service';
import { AdminProviderAssignmentsService } from '../src/providers/admin-provider-assignments.service';
import { UserRole } from '../src/users/enums/user-role.enum';

describe('Admin provider capabilities (e2e)', () => {
  let app: INestApplication;
  const providerId = '10000000-0000-4000-8000-000000000001';
  beforeAll(async () => {
    const service = { listServices: jest.fn().mockResolvedValue([]), listLocations: jest.fn().mockResolvedValue([]), getService: jest.fn(), createService: jest.fn(), activateService: jest.fn(), deactivateService: jest.fn(), linkLocation: jest.fn(), unlinkLocation: jest.fn(), getLocation: jest.fn(), createLocation: jest.fn(), updateLocation: jest.fn(), activateLocation: jest.fn(), deactivateLocation: jest.fn() };
    const availability = { list: jest.fn().mockResolvedValue([]), get: jest.fn(), create: jest.fn(), update: jest.fn(), activate: jest.fn(), deactivate: jest.fn() };
    const matching = { startMatching: jest.fn().mockResolvedValue({ bookingStatus: 'PENDING_PROVIDER_MATCH', assignment: { id: '10000000-0000-4000-8000-000000000001', bookingId: 'secret-booking', providerId: 'secret-provider', status: 'OFFERED', expiresAt: new Date('2026-08-24T08:30:00Z'), reasonCode: 'INTERNAL' } }), confirmAssignment: jest.fn(), expireStaleOffers: jest.fn().mockResolvedValue({ expiredCount: 2, nextOffers: [{ bookingStatus: 'PENDING_PROVIDER_MATCH', assignment: { id: 'next-secret' } }, { bookingStatus: 'UNFULFILLABLE', assignment: null }] }) };
    const assignments = { list: jest.fn().mockResolvedValue([]), get: jest.fn().mockResolvedValue({ assignmentId: '10000000-0000-4000-8000-000000000001' }) };
    const module = await Test.createTestingModule({ controllers: [AdminProviderCapabilitiesController, AdminProviderLocationsController, AdminProviderAvailabilityController, AdminProviderMatchingController], providers: [RolesGuard, Reflector, { provide: ProviderCapabilitiesService, useValue: service }, { provide: ProviderAvailabilityService, useValue: availability }, { provide: ProviderMatchingService, useValue: matching }, { provide: AdminProviderAssignmentsService, useValue: assignments }] }).overrideGuard(JwtAuthGuard).useValue({ canActivate: (context: any) => { const req = context.switchToHttp().getRequest(); const token = req.headers.authorization; if (!token) throw new UnauthorizedException(); req.user = { id: '10000000-0000-4000-8000-000000000099', roles: token === 'Bearer admin' ? [UserRole.ADMIN] : token === 'Bearer operations' ? [UserRole.OPERATIONS] : [UserRole.USER] }; return true; } }).compile();
    app = module.createNestApplication(); app.setGlobalPrefix('api/v1'); app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true })); await app.init();
  });
  afterAll(async () => app.close());
  const path = `/api/v1/admin/providers/${providerId}/services`;
  it('returns 401 without authentication', () => request(app.getHttpServer()).get(path).expect(401));
  it('returns 403 for USER', () => request(app.getHttpServer()).get(path).set('Authorization', 'Bearer user').expect(403));
  it('allows ADMIN', () => request(app.getHttpServer()).get(path).set('Authorization', 'Bearer admin').expect(200).expect([]));
  it('allows OPERATIONS', () => request(app.getHttpServer()).get(path).set('Authorization', 'Bearer operations').expect(200).expect([]));
  const availabilityPath = `/api/v1/admin/providers/${providerId}/availability`;
  it('returns 401 for unauthenticated availability access', () => request(app.getHttpServer()).get(availabilityPath).expect(401));
  it('returns 403 for USER availability access', () => request(app.getHttpServer()).get(availabilityPath).set('Authorization', 'Bearer user').expect(403));
  it('allows ADMIN availability access', () => request(app.getHttpServer()).get(availabilityPath).set('Authorization', 'Bearer admin').expect(200).expect([]));
  it('allows OPERATIONS availability access', () => request(app.getHttpServer()).get(availabilityPath).set('Authorization', 'Bearer operations').expect(200).expect([]));
  const matchingPath = '/api/v1/admin/bookings/SC-2026-ABCDEF123456/matching/start';
  it('returns 401 for unauthenticated matching commands', () => request(app.getHttpServer()).post(matchingPath).expect(401));
  it('returns 403 for USER matching commands', () => request(app.getHttpServer()).post(matchingPath).set('Authorization', 'Bearer user').expect(403));
  it('allows ADMIN matching commands with a minimized response', () => request(app.getHttpServer()).post(matchingPath).set('Authorization', 'Bearer admin').expect(200).expect((response) => { expect(response.body).toEqual({ bookingReference: 'SC-2026-ABCDEF123456', bookingStatus: 'PENDING_PROVIDER_MATCH', outcome: 'OFFER_CREATED', assignmentId: '10000000-0000-4000-8000-000000000001', assignmentStatus: 'OFFERED', offerExpiresAt: '2026-08-24T08:30:00.000Z' }); expect(response.body).not.toHaveProperty('bookingId'); expect(response.body).not.toHaveProperty('providerId'); expect(response.body).not.toHaveProperty('reasonCode'); }));
  it('allows OPERATIONS matching commands', () => request(app.getHttpServer()).post(matchingPath).set('Authorization', 'Bearer operations').expect(200));
  it('returns a summarized stale-expiry response', () => request(app.getHttpServer()).post('/api/v1/admin/provider-assignments/expire-stale').set('Authorization', 'Bearer operations').expect(200).expect({ expiredCount: 2, continuedMatchingCount: 1, unfulfillableCount: 1 }));
  const assignmentsPath = '/api/v1/admin/provider-assignments';
  it('returns 401 for unauthenticated assignment lists', () => request(app.getHttpServer()).get(assignmentsPath).expect(401));
  it('returns 403 for USER assignment lists', () => request(app.getHttpServer()).get(assignmentsPath).set('Authorization', 'Bearer user').expect(403));
  it('allows ADMIN assignment lists', () => request(app.getHttpServer()).get(assignmentsPath).set('Authorization', 'Bearer admin').expect(200).expect([]));
  it('allows OPERATIONS assignment lists', () => request(app.getHttpServer()).get(assignmentsPath).set('Authorization', 'Bearer operations').expect(200).expect([]));
});
