export enum PatientCareActionSource {
  HEALTH_CHECK_COMPLETED = 'HEALTH_CHECK_COMPLETED',
  GENERAL_CARE_COMPLETED = 'GENERAL_CARE_COMPLETED',
  PROVIDER_CONNECTION_CONNECTED = 'PROVIDER_CONNECTION_CONNECTED',
  PHARMACY_DISPENSING_COMPLETED = 'PHARMACY_DISPENSING_COMPLETED',
}
