import { MigrationInterface, QueryRunner } from 'typeorm';
export class ProviderAvailabilityExceptions1787673600000 implements MigrationInterface {
  name = 'ProviderAvailabilityExceptions1787673600000';
  public async up(q: QueryRunner): Promise<void> {
    await q.query(`CREATE TYPE "provider_availability_exception_type_enum" AS ENUM ('UNAVAILABLE', 'AVAILABLE')`);
    await q.query(`CREATE TABLE "provider_availability_exceptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "provider_id" uuid NOT NULL, "provider_service_id" uuid, "provider_location_id" uuid, "date" date NOT NULL, "start_time" time, "end_time" time, "timezone" character varying NOT NULL, "type" "provider_availability_exception_type_enum" NOT NULL, "reason" character varying, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "CHK_provider_availability_exceptions_times_paired" CHECK (("start_time" IS NULL) = ("end_time" IS NULL)), CONSTRAINT "CHK_provider_availability_exceptions_time_range" CHECK ("start_time" IS NULL OR "start_time" < "end_time"), CONSTRAINT "PK_provider_availability_exceptions" PRIMARY KEY ("id"))`);
    await q.query(`CREATE INDEX "IDX_provider_availability_exceptions_lookup" ON "provider_availability_exceptions" ("provider_id", "date", "timezone", "is_active")`); await q.query(`CREATE INDEX "IDX_provider_availability_exceptions_service" ON "provider_availability_exceptions" ("provider_service_id") WHERE "provider_service_id" IS NOT NULL`); await q.query(`CREATE INDEX "IDX_provider_availability_exceptions_location" ON "provider_availability_exceptions" ("provider_location_id") WHERE "provider_location_id" IS NOT NULL`);
    await q.query(`ALTER TABLE "provider_availability_exceptions" ADD CONSTRAINT "FK_provider_availability_exceptions_provider" FOREIGN KEY ("provider_id") REFERENCES "providers"("id") ON DELETE RESTRICT`); await q.query(`ALTER TABLE "provider_availability_exceptions" ADD CONSTRAINT "FK_provider_availability_exceptions_service_provider" FOREIGN KEY ("provider_service_id", "provider_id") REFERENCES "provider_services"("id", "provider_id") ON DELETE RESTRICT`); await q.query(`ALTER TABLE "provider_availability_exceptions" ADD CONSTRAINT "FK_provider_availability_exceptions_location_provider" FOREIGN KEY ("provider_location_id", "provider_id") REFERENCES "provider_locations"("id", "provider_id") ON DELETE RESTRICT`);
    await q.query(`ALTER TABLE "provider_availability_exceptions" ADD CONSTRAINT "EX_provider_availability_exceptions_active_overlap" EXCLUDE USING gist ("provider_id" WITH =, "date" WITH =, COALESCE("provider_service_id", '00000000-0000-0000-0000-000000000000'::uuid) WITH =, COALESCE("provider_location_id", '00000000-0000-0000-0000-000000000000'::uuid) WITH =, "timezone" WITH =, int8range(COALESCE(EXTRACT(EPOCH FROM "start_time")::bigint, 0), COALESCE(EXTRACT(EPOCH FROM "end_time")::bigint, 86400), '[)') WITH &&) WHERE ("is_active")`);
  }
  public async down(q: QueryRunner): Promise<void> { await q.query(`ALTER TABLE "provider_availability_exceptions" DROP CONSTRAINT "EX_provider_availability_exceptions_active_overlap"`); await q.query(`ALTER TABLE "provider_availability_exceptions" DROP CONSTRAINT "FK_provider_availability_exceptions_location_provider"`); await q.query(`ALTER TABLE "provider_availability_exceptions" DROP CONSTRAINT "FK_provider_availability_exceptions_service_provider"`); await q.query(`ALTER TABLE "provider_availability_exceptions" DROP CONSTRAINT "FK_provider_availability_exceptions_provider"`); await q.query(`DROP INDEX "IDX_provider_availability_exceptions_location"`); await q.query(`DROP INDEX "IDX_provider_availability_exceptions_service"`); await q.query(`DROP INDEX "IDX_provider_availability_exceptions_lookup"`); await q.query(`DROP TABLE "provider_availability_exceptions"`); await q.query(`DROP TYPE "provider_availability_exception_type_enum"`); }
}
