import { MigrationInterface, QueryRunner } from 'typeorm';
export class PublicBookingSessions1787932800000 implements MigrationInterface { name='PublicBookingSessions1787932800000'; async up(q:QueryRunner){
  await q.query(`CREATE TABLE "public_booking_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "booking_id" uuid NOT NULL, "token_hash" char(64) NOT NULL, "expires_at" timestamptz NOT NULL, "revoked_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), "last_used_at" timestamptz, CONSTRAINT "PK_public_booking_sessions" PRIMARY KEY ("id"), CONSTRAINT "UQ_public_booking_sessions_token_hash" UNIQUE ("token_hash"), CONSTRAINT "FK_public_booking_sessions_booking" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE RESTRICT)`);
  await q.query(`CREATE INDEX "IDX_public_booking_sessions_booking_active" ON "public_booking_sessions" ("booking_id", "expires_at", "revoked_at")`);
  await q.query(`ALTER TABLE "booking_contacts" ADD CONSTRAINT "UQ_booking_contacts_id_booking" UNIQUE ("id", "booking_id")`);
  await q.query(`ALTER TABLE "booking_funding" DROP CONSTRAINT "CHK_booking_funding_responsible_party"`); await q.query(`ALTER TABLE "booking_funding" DROP CONSTRAINT "CHK_booking_funding_source_party_type"`);
  await q.query(`ALTER TABLE "booking_funding" ADD "payer_contact_id" uuid`);
  await q.query(`ALTER TABLE "booking_funding" ADD CONSTRAINT "FK_booking_funding_payer_contact_booking" FOREIGN KEY ("payer_contact_id", "booking_id") REFERENCES "booking_contacts"("id", "booking_id") ON DELETE RESTRICT`);
  await q.query(`ALTER TABLE "booking_funding" ADD CONSTRAINT "CHK_booking_funding_responsible_party" CHECK ((CASE WHEN "responsible_user_id" IS NULL THEN 0 ELSE 1 END + CASE WHEN "responsible_organisation_id" IS NULL THEN 0 ELSE 1 END + CASE WHEN "payer_contact_id" IS NULL THEN 0 ELSE 1 END) <= 1)`);
  await q.query(`ALTER TABLE "booking_funding" ADD CONSTRAINT "CHK_booking_funding_source_party_type" CHECK (("source_type" = 'ORGANISATION' AND "responsible_organisation_id" IS NOT NULL) OR ("source_type" = 'SELF' AND (("responsible_user_id" IS NOT NULL) <> ("payer_contact_id" IS NOT NULL))) OR ("source_type" IN ('FAMILY', 'SPONSOR') AND "responsible_user_id" IS NOT NULL) OR "source_type" = 'OTHER')`);
 } async down(q:QueryRunner){
  await q.query(`ALTER TABLE "booking_funding" DROP CONSTRAINT "CHK_booking_funding_source_party_type"`); await q.query(`ALTER TABLE "booking_funding" DROP CONSTRAINT "CHK_booking_funding_responsible_party"`); await q.query(`ALTER TABLE "booking_funding" DROP CONSTRAINT "FK_booking_funding_payer_contact_booking"`); await q.query(`ALTER TABLE "booking_funding" DROP COLUMN "payer_contact_id"`);
  await q.query(`ALTER TABLE "booking_funding" ADD CONSTRAINT "CHK_booking_funding_responsible_party" CHECK ("responsible_user_id" IS NULL OR "responsible_organisation_id" IS NULL)`); await q.query(`ALTER TABLE "booking_funding" ADD CONSTRAINT "CHK_booking_funding_source_party_type" CHECK (("source_type" = 'ORGANISATION' AND "responsible_organisation_id" IS NOT NULL AND "responsible_user_id" IS NULL) OR ("source_type" IN ('SELF', 'FAMILY', 'SPONSOR') AND "responsible_user_id" IS NOT NULL AND "responsible_organisation_id" IS NULL) OR "source_type" = 'OTHER')`);
  await q.query(`ALTER TABLE "booking_contacts" DROP CONSTRAINT "UQ_booking_contacts_id_booking"`); await q.query(`DROP INDEX "IDX_public_booking_sessions_booking_active"`); await q.query(`DROP TABLE "public_booking_sessions"`);
 } }
