import { MigrationInterface, QueryRunner } from 'typeorm';
export class HomeVisitAddressesAndServiceAreas1788796800000 implements MigrationInterface {
  name = 'HomeVisitAddressesAndServiceAreas1788796800000';
  async up(q: QueryRunner): Promise<void> {
    await q.query(`CREATE TABLE "booking_visit_addresses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "booking_id" uuid NOT NULL, "address_line1" varchar(255) NOT NULL, "address_line2" varchar(255), "city" varchar(120) NOT NULL, "state_or_region" varchar(120) NOT NULL, "postal_code" varchar(30), "country_code" char(2) NOT NULL, "latitude" numeric(9,6), "longitude" numeric(9,6), "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "UQ_booking_visit_addresses_booking" UNIQUE ("booking_id"), CONSTRAINT "CHK_booking_visit_address_country" CHECK ("country_code" ~ '^[A-Z]{2}$'), CONSTRAINT "CHK_booking_visit_address_coordinates" CHECK (("latitude" IS NULL OR "latitude" BETWEEN -90 AND 90) AND ("longitude" IS NULL OR "longitude" BETWEEN -180 AND 180)), CONSTRAINT "PK_booking_visit_addresses" PRIMARY KEY ("id"), CONSTRAINT "FK_booking_visit_addresses_booking" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE)`);
    await q.query(`CREATE TABLE "provider_service_areas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "provider_id" uuid NOT NULL, "provider_service_id" uuid NOT NULL, "country_code" char(2) NOT NULL, "state_or_region" varchar(120) NOT NULL, "city" varchar(120), "postal_code" varchar(30), "is_active" boolean NOT NULL DEFAULT true, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "CHK_provider_service_area_country" CHECK ("country_code" ~ '^[A-Z]{2}$'), CONSTRAINT "PK_provider_service_areas" PRIMARY KEY ("id"), CONSTRAINT "FK_provider_service_areas_provider" FOREIGN KEY ("provider_id") REFERENCES "providers"("id") ON DELETE CASCADE, CONSTRAINT "FK_provider_service_areas_service_owner" FOREIGN KEY ("provider_service_id", "provider_id") REFERENCES "provider_services"("id", "provider_id") ON DELETE CASCADE)`);
    await q.query(`CREATE INDEX "IDX_provider_service_areas_provider" ON "provider_service_areas" ("provider_id")`);
    await q.query(`CREATE INDEX "IDX_provider_service_areas_matching" ON "provider_service_areas" ("provider_service_id", "is_active", "country_code", "state_or_region", "city", "postal_code")`);
  }
  async down(q: QueryRunner): Promise<void> { await q.query(`DROP TABLE "provider_service_areas"`); await q.query(`DROP TABLE "booking_visit_addresses"`); }
}
