import { MigrationInterface, QueryRunner } from 'typeorm';

export class HealthCheckEncounters1788364800000 implements MigrationInterface {
  name = 'HealthCheckEncounters1788364800000';
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TYPE "health_check_encounter_status_enum" AS ENUM ('DRAFT', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')`);
    await queryRunner.query(`CREATE TYPE "health_check_measurement_code_enum" AS ENUM ('BLOOD_PRESSURE', 'BLOOD_GLUCOSE', 'BMI', 'TEMPERATURE', 'OXYGEN_SATURATION', 'PULSE')`);
    await queryRunner.query(`CREATE TYPE "health_check_measurement_action_enum" AS ENUM ('CREATED', 'UPDATED')`);
    await queryRunner.query(`CREATE TABLE "health_check_encounters" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "booking_id" uuid NOT NULL, "provider_id" uuid NOT NULL, "provider_assignment_id" uuid NOT NULL, "status" "health_check_encounter_status_enum" NOT NULL DEFAULT 'DRAFT', "started_at" timestamptz, "completed_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "PK_health_check_encounters" PRIMARY KEY ("id"), CONSTRAINT "UQ_health_check_encounters_booking" UNIQUE ("booking_id"), CONSTRAINT "CHK_health_check_encounters_timestamps" CHECK (("status" <> 'IN_PROGRESS' AND "status" <> 'COMPLETED') OR "started_at" IS NOT NULL), CONSTRAINT "CHK_health_check_encounters_completed_at" CHECK ("status" <> 'COMPLETED' OR "completed_at" IS NOT NULL), CONSTRAINT "FK_health_check_encounters_booking" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE RESTRICT, CONSTRAINT "FK_health_check_encounters_provider" FOREIGN KEY ("provider_id") REFERENCES "providers"("id") ON DELETE RESTRICT, CONSTRAINT "FK_health_check_encounters_assignment_scope" FOREIGN KEY ("provider_assignment_id", "provider_id", "booking_id") REFERENCES "provider_assignments"("id", "provider_id", "booking_id") ON DELETE RESTRICT)`);
    await queryRunner.query(`CREATE INDEX "IDX_health_check_encounters_provider_status" ON "health_check_encounters" ("provider_id", "status")`);
    await queryRunner.query(`CREATE TABLE "health_check_measurements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "encounter_id" uuid NOT NULL, "code" "health_check_measurement_code_enum" NOT NULL, "value_numeric" numeric(12,4) NOT NULL, "value_secondary_numeric" numeric(12,4), "unit" varchar(16) NOT NULL, "recorded_at" timestamptz NOT NULL, "recorded_by_user_id" uuid NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "PK_health_check_measurements" PRIMARY KEY ("id"), CONSTRAINT "UQ_health_check_measurements_encounter_code" UNIQUE ("encounter_id", "code"), CONSTRAINT "CHK_health_check_measurements_shape" CHECK (("code" = 'BLOOD_PRESSURE' AND "value_secondary_numeric" IS NOT NULL) OR ("code" <> 'BLOOD_PRESSURE' AND "value_secondary_numeric" IS NULL)), CONSTRAINT "FK_health_check_measurements_encounter" FOREIGN KEY ("encounter_id") REFERENCES "health_check_encounters"("id") ON DELETE RESTRICT, CONSTRAINT "FK_health_check_measurements_actor" FOREIGN KEY ("recorded_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT)`);
    await queryRunner.query(`CREATE INDEX "IDX_health_check_measurements_encounter" ON "health_check_measurements" ("encounter_id")`);
    await queryRunner.query(`CREATE TABLE "health_check_measurement_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "measurement_id" uuid NOT NULL, "action" "health_check_measurement_action_enum" NOT NULL, "previous_value" jsonb, "new_value" jsonb NOT NULL, "actor_user_id" uuid NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "PK_health_check_measurement_history" PRIMARY KEY ("id"), CONSTRAINT "FK_health_check_measurement_history_measurement" FOREIGN KEY ("measurement_id") REFERENCES "health_check_measurements"("id") ON DELETE RESTRICT, CONSTRAINT "FK_health_check_measurement_history_actor" FOREIGN KEY ("actor_user_id") REFERENCES "users"("id") ON DELETE RESTRICT)`);
    await queryRunner.query(`CREATE INDEX "IDX_health_check_measurement_history_measurement_created" ON "health_check_measurement_history" ("measurement_id", "created_at")`);
    await queryRunner.query(`CREATE TABLE "health_check_encounter_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "encounter_id" uuid NOT NULL, "from_status" "health_check_encounter_status_enum", "to_status" "health_check_encounter_status_enum" NOT NULL, "actor_user_id" uuid NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "PK_health_check_encounter_history" PRIMARY KEY ("id"), CONSTRAINT "FK_health_check_encounter_history_encounter" FOREIGN KEY ("encounter_id") REFERENCES "health_check_encounters"("id") ON DELETE RESTRICT, CONSTRAINT "FK_health_check_encounter_history_actor" FOREIGN KEY ("actor_user_id") REFERENCES "users"("id") ON DELETE RESTRICT)`);
    await queryRunner.query(`CREATE INDEX "IDX_health_check_encounter_history_encounter_created" ON "health_check_encounter_history" ("encounter_id", "created_at")`);
  }
  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "health_check_encounter_history"`);
    await queryRunner.query(`DROP TABLE "health_check_measurement_history"`);
    await queryRunner.query(`DROP TABLE "health_check_measurements"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_health_check_encounters_provider_status"`);
    await queryRunner.query(`DROP TABLE "health_check_encounters"`);
    await queryRunner.query(`DROP TYPE "health_check_measurement_action_enum"`);
    await queryRunner.query(`DROP TYPE "health_check_measurement_code_enum"`);
    await queryRunner.query(`DROP TYPE "health_check_encounter_status_enum"`);
  }
}
