import { MigrationInterface, QueryRunner } from 'typeorm';
export class ProviderServiceUnitsAndOrderFulfillment1791216000000 implements MigrationInterface {
  name='ProviderServiceUnitsAndOrderFulfillment1791216000000';
  async up(q:QueryRunner){
    await q.query(`CREATE TYPE "provider_service_unit_type_enum" AS ENUM ('GENERAL','PHARMACY','LABORATORY','RADIOLOGY','PROCEDURE','SPECIALIST','OTHER')`);
    await q.query(`CREATE TYPE "provider_service_unit_status_enum" AS ENUM ('ACTIVE','INACTIVE')`);
    await q.query(`CREATE TABLE "provider_service_units"("id" uuid NOT NULL DEFAULT uuid_generate_v4(),"reference" varchar(32) NOT NULL,"provider_id" uuid NOT NULL,"code" varchar(80) NOT NULL,"name" varchar(160) NOT NULL,"type" "provider_service_unit_type_enum" NOT NULL,"description" text,"status" "provider_service_unit_status_enum" NOT NULL DEFAULT 'ACTIVE',"provider_location_id" uuid,"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now(),"deleted_at" timestamptz,CONSTRAINT "PK_provider_service_units" PRIMARY KEY("id"),CONSTRAINT "UQ_provider_service_units_id_provider" UNIQUE("id","provider_id"),CONSTRAINT "FK_provider_service_units_provider" FOREIGN KEY("provider_id") REFERENCES "providers"("id") ON DELETE RESTRICT,CONSTRAINT "FK_provider_service_units_location_owner" FOREIGN KEY("provider_location_id","provider_id") REFERENCES "provider_locations"("id","provider_id") ON DELETE RESTRICT)`);
    await q.query(`CREATE UNIQUE INDEX "UQ_provider_service_units_reference" ON "provider_service_units"("reference")`);
    await q.query(`CREATE UNIQUE INDEX "UQ_provider_service_units_code_provider" ON "provider_service_units"("provider_id","code") WHERE "deleted_at" IS NULL`);
    await q.query(`CREATE INDEX "IDX_provider_service_units_provider_status" ON "provider_service_units"("provider_id","status")`);
    await q.query(`CREATE TYPE "clinical_order_fulfillment_status_enum" AS ENUM ('PROPOSED','SELECTED','ACCEPTED','CANCELLED')`);
    await q.query(`CREATE TABLE "clinical_order_fulfillments"("id" uuid NOT NULL DEFAULT uuid_generate_v4(),"reference" varchar(32) NOT NULL,"clinical_order_id" uuid NOT NULL,"patient_id" uuid NOT NULL,"fulfillment_provider_id" uuid NOT NULL,"fulfillment_service_unit_id" uuid NOT NULL,"recommended_service_unit_id" uuid,"recommended_by_provider_id" uuid,"selected_by_user_id" uuid,"status" "clinical_order_fulfillment_status_enum" NOT NULL,"accepted_at" timestamptz,"cancelled_at" timestamptz,"cancellation_reason" varchar(500),"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "PK_clinical_order_fulfillments" PRIMARY KEY("id"),CONSTRAINT "FK_order_fulfillment_order" FOREIGN KEY("clinical_order_id") REFERENCES "clinical_orders"("id") ON DELETE RESTRICT,CONSTRAINT "FK_order_fulfillment_patient" FOREIGN KEY("patient_id") REFERENCES "patients"("id") ON DELETE RESTRICT,CONSTRAINT "FK_order_fulfillment_provider" FOREIGN KEY("fulfillment_provider_id") REFERENCES "providers"("id") ON DELETE RESTRICT,CONSTRAINT "FK_order_fulfillment_unit_owner" FOREIGN KEY("fulfillment_service_unit_id","fulfillment_provider_id") REFERENCES "provider_service_units"("id","provider_id") ON DELETE RESTRICT,CONSTRAINT "FK_order_fulfillment_recommended_unit" FOREIGN KEY("recommended_service_unit_id") REFERENCES "provider_service_units"("id") ON DELETE RESTRICT,CONSTRAINT "FK_order_fulfillment_recommender" FOREIGN KEY("recommended_by_provider_id") REFERENCES "providers"("id") ON DELETE RESTRICT,CONSTRAINT "FK_order_fulfillment_selector" FOREIGN KEY("selected_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT,CONSTRAINT "CHK_order_fulfillment_status_dates" CHECK (("status"='ACCEPTED' AND "accepted_at" IS NOT NULL AND "cancelled_at" IS NULL) OR ("status"='CANCELLED' AND "cancelled_at" IS NOT NULL) OR ("status" IN ('PROPOSED','SELECTED') AND "accepted_at" IS NULL AND "cancelled_at" IS NULL)))`);
    await q.query(`CREATE UNIQUE INDEX "UQ_clinical_order_fulfillments_reference" ON "clinical_order_fulfillments"("reference")`);
    await q.query(`CREATE UNIQUE INDEX "UQ_clinical_order_fulfillments_active_order" ON "clinical_order_fulfillments"("clinical_order_id") WHERE "status" IN ('PROPOSED','SELECTED','ACCEPTED')`);
    await q.query(`CREATE INDEX "IDX_clinical_order_fulfillments_provider_status" ON "clinical_order_fulfillments"("fulfillment_provider_id","status")`);
    await q.query(`CREATE INDEX "IDX_clinical_order_fulfillments_order_created" ON "clinical_order_fulfillments"("clinical_order_id","created_at")`);
    await q.query(`CREATE TABLE "clinical_order_fulfillment_history"("id" uuid NOT NULL DEFAULT uuid_generate_v4(),"fulfillment_id" uuid NOT NULL,"from_status" "clinical_order_fulfillment_status_enum","to_status" "clinical_order_fulfillment_status_enum" NOT NULL,"actor_user_id" uuid,"reason_code" varchar(80) NOT NULL,"reason_note" varchar(500),"created_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "PK_clinical_order_fulfillment_history" PRIMARY KEY("id"),CONSTRAINT "FK_order_fulfillment_history_fulfillment" FOREIGN KEY("fulfillment_id") REFERENCES "clinical_order_fulfillments"("id") ON DELETE RESTRICT,CONSTRAINT "FK_order_fulfillment_history_actor" FOREIGN KEY("actor_user_id") REFERENCES "users"("id") ON DELETE RESTRICT)`);
    await q.query(`CREATE INDEX "IDX_order_fulfillment_history_fulfillment_created" ON "clinical_order_fulfillment_history"("fulfillment_id","created_at")`);
  }
  async down(q:QueryRunner){await q.query(`DROP TABLE "clinical_order_fulfillment_history"`);await q.query(`DROP TABLE "clinical_order_fulfillments"`);await q.query(`DROP TYPE "clinical_order_fulfillment_status_enum"`);await q.query(`DROP TABLE "provider_service_units"`);await q.query(`DROP TYPE "provider_service_unit_status_enum"`);await q.query(`DROP TYPE "provider_service_unit_type_enum"`);}
}
