import { MigrationInterface,QueryRunner } from 'typeorm';
const groups=[['current_health','Current health and concerns','Tell us what brings you here today.'],['existing_conditions','Existing medical conditions',null],['hypertension','High blood pressure history',null],['diabetes','Diabetes history',null],['family_history','Family health history',null],['medicines','Medicines',null],['allergies','Allergies',null],['blood_pressure','Last known blood pressure','Patient-reported readings are not yet provider-validated.'],['blood_sugar','Last known blood sugar','Patient-reported readings are not yet provider-validated.'],['equipment_access','Measurement equipment access',null],['lifestyle','Basic lifestyle information',null],['professional_note','Anything else','Share anything you would like a healthcare professional to know.']] as const;
type Q={g:number;k:string;t:string;type:string;r?:boolean;u?:boolean;o?:string[];c?:object;v?:object;m?:object};
const qs:Q[]=[
{g:0,k:'current_health_concerns',t:'What health concerns would you like to tell us about today?',type:'LONG_TEXT',r:true,v:{maxLength:5000}},
{g:1,k:'existing_conditions',t:'Which existing medical conditions have you been told you have?',type:'MULTI_CHOICE',r:true,u:true,o:['NONE','ASTHMA','HEART_CONDITION','KIDNEY_CONDITION','SICKLE_CELL','OTHER']},
{g:2,k:'hypertension_history',t:'Have you ever been told by a healthcare professional that you have high blood pressure?',type:'SINGLE_CHOICE',r:true,u:true,o:['YES','NO']},
{g:2,k:'hypertension_details',t:'Please share anything you know about your high blood pressure history.',type:'LONG_TEXT',r:true,c:{questionKey:'hypertension_history',operator:'EQUALS',expected:'YES'},v:{maxLength:3000}},
{g:3,k:'diabetes_history',t:'Have you ever been told by a healthcare professional that you have diabetes?',type:'SINGLE_CHOICE',r:true,u:true,o:['YES','NO']},
{g:3,k:'diabetes_details',t:'Please share anything you know about your diabetes history.',type:'LONG_TEXT',r:true,c:{questionKey:'diabetes_history',operator:'EQUALS',expected:'YES'},v:{maxLength:3000}},
{g:4,k:'family_history',t:'Which conditions are known in your close family?',type:'MULTI_CHOICE',u:true,o:['NONE','HIGH_BLOOD_PRESSURE','DIABETES','HEART_DISEASE','STROKE','OTHER']},
{g:5,k:'takes_regular_medicines',t:'Do you currently take any medicines regularly?',type:'BOOLEAN',r:true,u:true},
{g:5,k:'medication_details',t:'List the medicines you take regularly, if known.',type:'LONG_TEXT',r:true,c:{questionKey:'takes_regular_medicines',operator:'EQUALS',expected:true},v:{maxLength:5000}},
{g:6,k:'has_allergies',t:'Do you have any known medicine, food, or other allergies?',type:'SINGLE_CHOICE',r:true,u:true,o:['YES','NO']},
{g:6,k:'allergy_details',t:'Please describe your known allergies.',type:'LONG_TEXT',r:true,c:{questionKey:'has_allergies',operator:'EQUALS',expected:'YES'},v:{maxLength:3000}},
{g:7,k:'knows_recent_blood_pressure',t:'Do you know a recent blood pressure reading?',type:'BOOLEAN',r:true},
{g:7,k:'last_known_blood_pressure',t:'Enter your most recent blood pressure reading.',type:'BLOOD_PRESSURE',r:true,u:true,c:{questionKey:'knows_recent_blood_pressure',operator:'EQUALS',expected:true},m:{unit:'mmHg',provenance:'PATIENT_REPORTED'}},
{g:8,k:'knows_recent_blood_sugar',t:'Do you know a recent blood sugar reading?',type:'BOOLEAN',r:true},
{g:8,k:'last_known_blood_sugar',t:'Enter your most recent blood sugar reading.',type:'BLOOD_GLUCOSE',r:true,u:true,c:{questionKey:'knows_recent_blood_sugar',operator:'EQUALS',expected:true},m:{units:['mmol/L','mg/dL'],provenance:'PATIENT_REPORTED'}},
{g:9,k:'measurement_equipment_access',t:'Which measurement equipment can you access?',type:'MULTI_CHOICE',r:true,o:['NONE','BLOOD_PRESSURE_MONITOR','GLUCOSE_METER']},
{g:10,k:'smoking_status',t:'Do you currently smoke or use tobacco?',type:'SINGLE_CHOICE',r:true,u:true,o:['YES','NO','SOMETIMES']},
{g:10,k:'activity_level',t:'How would you describe your usual physical activity?',type:'SINGLE_CHOICE',r:true,u:true,o:['LOW','MODERATE','HIGH']},
{g:11,k:'professional_note',t:'Is there anything else you would like a healthcare professional to know?',type:'LONG_TEXT',v:{maxLength:5000}},
];
export class GuidedSelfCheckQuestionnaireV11791907200000 implements MigrationInterface{name='GuidedSelfCheckQuestionnaireV11791907200000';async up(q:QueryRunner){
await q.query(`CREATE TYPE "guided_self_check_question_type_enum" AS ENUM ('SINGLE_CHOICE','MULTI_CHOICE','BOOLEAN','SHORT_TEXT','LONG_TEXT','NUMBER','BLOOD_PRESSURE','BLOOD_GLUCOSE')`);await q.query(`CREATE TYPE "guided_self_check_answer_state_enum" AS ENUM ('KNOWN','DONT_KNOW')`);await q.query(`CREATE TYPE "guided_self_check_answer_provenance_enum" AS ENUM ('PATIENT_REPORTED')`);
await q.query(`CREATE TABLE "guided_self_check_questionnaire_versions"("id" uuid NOT NULL DEFAULT uuid_generate_v4(),"version" integer NOT NULL,"is_active" boolean NOT NULL DEFAULT false,"schema_version" smallint NOT NULL DEFAULT 1,"created_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "PK_gsc_questionnaire_versions" PRIMARY KEY("id"),CONSTRAINT "UQ_gsc_questionnaire_version" UNIQUE("version"),CONSTRAINT "CHK_gsc_questionnaire_version_positive" CHECK("version">0))`);await q.query(`CREATE UNIQUE INDEX "UQ_gsc_questionnaire_active" ON "guided_self_check_questionnaire_versions"("is_active") WHERE "is_active"=true`);
await q.query(`CREATE TABLE "guided_self_check_question_groups"("id" uuid NOT NULL DEFAULT uuid_generate_v4(),"questionnaire_version_id" uuid NOT NULL,"key" varchar(80) NOT NULL,"title" varchar(180) NOT NULL,"helper_text" text,"sort_order" smallint NOT NULL,CONSTRAINT "PK_gsc_question_groups" PRIMARY KEY("id"),CONSTRAINT "UQ_gsc_question_group_key" UNIQUE("questionnaire_version_id","key"),CONSTRAINT "UQ_gsc_question_group_order" UNIQUE("questionnaire_version_id","sort_order"),CONSTRAINT "FK_gsc_question_group_version" FOREIGN KEY("questionnaire_version_id") REFERENCES "guided_self_check_questionnaire_versions"("id") ON DELETE RESTRICT)`);
await q.query(`CREATE TABLE "guided_self_check_questions"("id" uuid NOT NULL DEFAULT uuid_generate_v4(),"questionnaire_version_id" uuid NOT NULL,"group_id" uuid NOT NULL,"key" varchar(100) NOT NULL,"text" text NOT NULL,"helper_text" text,"type" "guided_self_check_question_type_enum" NOT NULL,"required" boolean NOT NULL DEFAULT false,"allows_dont_know" boolean NOT NULL DEFAULT false,"options" jsonb,"visibility_condition" jsonb,"validation_metadata" jsonb,"measurement_metadata" jsonb,"sort_order" smallint NOT NULL,CONSTRAINT "PK_gsc_questions" PRIMARY KEY("id"),CONSTRAINT "UQ_gsc_question_key" UNIQUE("questionnaire_version_id","key"),CONSTRAINT "UQ_gsc_question_order" UNIQUE("group_id","sort_order"),CONSTRAINT "FK_gsc_question_version" FOREIGN KEY("questionnaire_version_id") REFERENCES "guided_self_check_questionnaire_versions"("id") ON DELETE RESTRICT,CONSTRAINT "FK_gsc_question_group" FOREIGN KEY("group_id") REFERENCES "guided_self_check_question_groups"("id") ON DELETE RESTRICT)`);
await q.query(`ALTER TABLE "guided_self_checks" ADD "questionnaire_version_id" uuid`);await q.query(`ALTER TABLE "guided_self_checks" ADD "started_at" timestamptz`);await q.query(`ALTER TABLE "guided_self_checks" ADD "completed_at" timestamptz`);await q.query(`ALTER TABLE "guided_self_checks" ADD CONSTRAINT "FK_gsc_questionnaire_version" FOREIGN KEY("questionnaire_version_id") REFERENCES "guided_self_check_questionnaire_versions"("id") ON DELETE RESTRICT`);await q.query(`CREATE INDEX "IDX_gsc_questionnaire_version" ON "guided_self_checks"("questionnaire_version_id")`);
await q.query(`CREATE TABLE "guided_self_check_answers"("id" uuid NOT NULL DEFAULT uuid_generate_v4(),"guided_self_check_id" uuid NOT NULL,"question_id" uuid NOT NULL,"state" "guided_self_check_answer_state_enum" NOT NULL,"value" jsonb,"provenance" "guided_self_check_answer_provenance_enum" NOT NULL DEFAULT 'PATIENT_REPORTED',"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "PK_gsc_answers" PRIMARY KEY("id"),CONSTRAINT "UQ_gsc_answer_check_question" UNIQUE("guided_self_check_id","question_id"),CONSTRAINT "CHK_gsc_answer_state_value" CHECK(("state"='DONT_KNOW' AND "value" IS NULL) OR "state"='KNOWN'),CONSTRAINT "FK_gsc_answer_check" FOREIGN KEY("guided_self_check_id") REFERENCES "guided_self_checks"("id") ON DELETE RESTRICT,CONSTRAINT "FK_gsc_answer_question" FOREIGN KEY("question_id") REFERENCES "guided_self_check_questions"("id") ON DELETE RESTRICT)`);await q.query(`CREATE INDEX "IDX_gsc_answers_check_updated" ON "guided_self_check_answers"("guided_self_check_id","updated_at")`);
const vr=await q.query(`INSERT INTO "guided_self_check_questionnaire_versions"("version","is_active") VALUES (1,true) RETURNING "id"`);const versionId=vr[0].id;const groupIds:string[]=[];for(let i=0;i<groups.length;i++){const g=groups[i];const rows=await q.query(`INSERT INTO "guided_self_check_question_groups"("questionnaire_version_id","key","title","helper_text","sort_order") VALUES ($1,$2,$3,$4,$5) RETURNING "id"`,[versionId,g[0],g[1],g[2],i+1]);groupIds.push(rows[0].id);}const orders=new Map<number,number>();for(const x of qs){const order=(orders.get(x.g)??0)+1;orders.set(x.g,order);await q.query(`INSERT INTO "guided_self_check_questions"("questionnaire_version_id","group_id","key","text","type","required","allows_dont_know","options","visibility_condition","validation_metadata","measurement_metadata","sort_order") VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9::jsonb,$10::jsonb,$11::jsonb,$12)`,[versionId,groupIds[x.g],x.k,x.t,x.type,x.r??false,x.u??false,x.o?JSON.stringify(x.o):null,x.c?JSON.stringify(x.c):null,x.v?JSON.stringify(x.v):null,x.m?JSON.stringify(x.m):null,order]);}
}async down(q:QueryRunner){await q.query(`DROP TABLE "guided_self_check_answers"`);await q.query(`DROP INDEX "IDX_gsc_questionnaire_version"`);await q.query(`ALTER TABLE "guided_self_checks" DROP CONSTRAINT "FK_gsc_questionnaire_version"`);await q.query(`ALTER TABLE "guided_self_checks" DROP COLUMN "completed_at"`);await q.query(`ALTER TABLE "guided_self_checks" DROP COLUMN "started_at"`);await q.query(`ALTER TABLE "guided_self_checks" DROP COLUMN "questionnaire_version_id"`);await q.query(`DROP TABLE "guided_self_check_questions"`);await q.query(`DROP TABLE "guided_self_check_question_groups"`);await q.query(`DROP TABLE "guided_self_check_questionnaire_versions"`);await q.query(`DROP TYPE "guided_self_check_answer_provenance_enum"`);await q.query(`DROP TYPE "guided_self_check_answer_state_enum"`);await q.query(`DROP TYPE "guided_self_check_question_type_enum"`);}}
