import { MigrationInterface,QueryRunner } from 'typeorm';
export class GuidedSelfCheckProfessionalReviews1792166400000 implements MigrationInterface{name='GuidedSelfCheckProfessionalReviews1792166400000';async up(q:QueryRunner){
 await q.query(`CREATE TYPE "guided_self_check_review_status_enum" AS ENUM ('PENDING','ASSIGNED','IN_REVIEW','COMPLETED','CANCELLED')`);
 await q.query(`CREATE TYPE "guided_self_check_review_priority_enum" AS ENUM ('ROUTINE','URGENT')`);
 await q.query(`CREATE TYPE "guided_self_check_review_origin_enum" AS ENUM ('CLASSIFICATION_REQUIRED','QA_SAMPLE')`);
 await q.query(`CREATE TYPE "guided_self_check_review_decision_enum" AS ENUM ('NO_FURTHER_REVIEW_REQUIRED','FOLLOW_UP_RECOMMENDED','PATIENT_CONTACT_REQUIRED','URGENT_ESCALATION_CONFIRMED')`);
 await q.query(`CREATE TYPE "guided_self_check_contact_status_enum" AS ENUM ('NOT_REQUIRED','REQUIRED','CONTACTED')`);
 await q.query(`CREATE TYPE "guided_self_check_review_event_enum" AS ENUM ('REVIEW_CREATED','REVIEW_ASSIGNED','REVIEW_REASSIGNED','REVIEW_STARTED','REVIEW_COMPLETED','REVIEW_CANCELLED')`);
 await q.query(`CREATE TABLE "guided_self_check_professional_reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(),"reference" varchar(40) NOT NULL,"guided_self_check_id" uuid NOT NULL,"classification_id" uuid NOT NULL,"classification_snapshot" "guided_self_check_classification_enum" NOT NULL,"priority" "guided_self_check_review_priority_enum" NOT NULL,"origin" "guided_self_check_review_origin_enum" NOT NULL DEFAULT 'CLASSIFICATION_REQUIRED',"status" "guided_self_check_review_status_enum" NOT NULL DEFAULT 'PENDING',"assigned_reviewer_user_id" uuid,"assigned_reviewer_provider_id" uuid,"assigned_at" timestamptz,"started_at" timestamptz,"completed_at" timestamptz,"cancelled_at" timestamptz,"decision" "guided_self_check_review_decision_enum","reviewer_notes" text,"contact_required" boolean NOT NULL DEFAULT false,"contact_status" "guided_self_check_contact_status_enum" NOT NULL DEFAULT 'NOT_REQUIRED',"contacted_at" timestamptz,"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "PK_gsc_professional_reviews" PRIMARY KEY("id"),CONSTRAINT "UQ_gsc_review_reference" UNIQUE("reference"),CONSTRAINT "UQ_gsc_review_classification" UNIQUE("classification_id"),CONSTRAINT "CHK_gsc_review_classification_required" CHECK("classification_snapshot" IN ('AMBER','RED')),CONSTRAINT "CHK_gsc_review_completion" CHECK(("status"='COMPLETED' AND "decision" IS NOT NULL AND "completed_at" IS NOT NULL) OR "status"<>'COMPLETED'))`);
 await q.query(`ALTER TABLE "guided_self_check_professional_reviews" ADD CONSTRAINT "FK_gsc_review_check" FOREIGN KEY("guided_self_check_id") REFERENCES "guided_self_checks"("id") ON DELETE RESTRICT`);await q.query(`ALTER TABLE "guided_self_check_professional_reviews" ADD CONSTRAINT "FK_gsc_review_classification" FOREIGN KEY("classification_id") REFERENCES "guided_self_check_classifications"("id") ON DELETE RESTRICT`);await q.query(`ALTER TABLE "guided_self_check_professional_reviews" ADD CONSTRAINT "FK_gsc_review_user" FOREIGN KEY("assigned_reviewer_user_id") REFERENCES "users"("id") ON DELETE RESTRICT`);await q.query(`ALTER TABLE "guided_self_check_professional_reviews" ADD CONSTRAINT "FK_gsc_review_provider" FOREIGN KEY("assigned_reviewer_provider_id") REFERENCES "providers"("id") ON DELETE RESTRICT`);
 await q.query(`CREATE INDEX "IDX_gsc_review_queue" ON "guided_self_check_professional_reviews"("status","priority","created_at")`);await q.query(`CREATE INDEX "IDX_gsc_review_assignee" ON "guided_self_check_professional_reviews"("assigned_reviewer_user_id","status")`);
 await q.query(`CREATE TABLE "guided_self_check_professional_review_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(),"review_id" uuid NOT NULL,"event" "guided_self_check_review_event_enum" NOT NULL,"actor_user_id" uuid,"from_status" "guided_self_check_review_status_enum","to_status" "guided_self_check_review_status_enum","metadata" jsonb NOT NULL DEFAULT '{}',"created_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "PK_gsc_review_history" PRIMARY KEY("id"),CONSTRAINT "FK_gsc_review_history_review" FOREIGN KEY("review_id") REFERENCES "guided_self_check_professional_reviews"("id") ON DELETE RESTRICT,CONSTRAINT "FK_gsc_review_history_actor" FOREIGN KEY("actor_user_id") REFERENCES "users"("id") ON DELETE RESTRICT)`);await q.query(`CREATE INDEX "IDX_gsc_review_history" ON "guided_self_check_professional_review_history"("review_id","created_at")`);
 }async down(q:QueryRunner){await q.query(`DROP TABLE "guided_self_check_professional_review_history"`);await q.query(`DROP TABLE "guided_self_check_professional_reviews"`);await q.query(`DROP TYPE "guided_self_check_review_event_enum"`);await q.query(`DROP TYPE "guided_self_check_contact_status_enum"`);await q.query(`DROP TYPE "guided_self_check_review_decision_enum"`);await q.query(`DROP TYPE "guided_self_check_review_origin_enum"`);await q.query(`DROP TYPE "guided_self_check_review_priority_enum"`);await q.query(`DROP TYPE "guided_self_check_review_status_enum"`);}}
