import { MigrationInterface, QueryRunner } from 'typeorm';
export class HmoPhaseOneFoundation1796659200000 implements MigrationInterface {
 name='HmoPhaseOneFoundation1796659200000';
 public async up(q:QueryRunner):Promise<void>{
  await q.query(`CREATE TABLE "hmos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" varchar(160) NOT NULL, "code" varchar(40) NOT NULL, "logo_url" varchar, "contact" varchar, "authorization_contact" varchar, "claims_contact" varchar, "verification_method" varchar(20) NOT NULL DEFAULT 'MANUAL', "claim_submission_method" varchar(40) NOT NULL DEFAULT 'MANUAL', "api_config" jsonb, "active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(), "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(), CONSTRAINT "UQ_hmos_code" UNIQUE ("code"), CONSTRAINT "PK_hmos" PRIMARY KEY ("id"))`);
  await q.query(`CREATE TABLE "hmo_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "hmo_id" uuid NOT NULL, "name" varchar(120) NOT NULL, "code" varchar(50) NOT NULL, "active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(), "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(), CONSTRAINT "UQ_hmo_plans_hmo_code" UNIQUE ("hmo_id","code"), CONSTRAINT "PK_hmo_plans" PRIMARY KEY ("id"), CONSTRAINT "FK_hmo_plans_hmo" FOREIGN KEY ("hmo_id") REFERENCES "hmos"("id") ON DELETE RESTRICT)`);
  await q.query(`CREATE TABLE "patient_hmo_coverages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patient_id" uuid NOT NULL, "hmo_id" uuid NOT NULL, "plan_id" uuid, "member_id" varchar(120) NOT NULL, "policy_number" varchar, "member_type" varchar(20) NOT NULL DEFAULT 'PRINCIPAL', "employer_organisation" varchar, "valid_from" date, "expires_at" date, "document_url" varchar, "eligibility_status" varchar(20) NOT NULL DEFAULT 'UNVERIFIED', "last_verified_at" TIMESTAMPTZ, "verification_reference" varchar, "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(), "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(), CONSTRAINT "PK_patient_hmo_coverages" PRIMARY KEY ("id"), CONSTRAINT "FK_patient_hmo_patient" FOREIGN KEY ("patient_id") REFERENCES "patients"("id") ON DELETE RESTRICT, CONSTRAINT "FK_patient_hmo_hmo" FOREIGN KEY ("hmo_id") REFERENCES "hmos"("id") ON DELETE RESTRICT, CONSTRAINT "FK_patient_hmo_plan" FOREIGN KEY ("plan_id") REFERENCES "hmo_plans"("id") ON DELETE RESTRICT)`);
  await q.query(`CREATE INDEX "IDX_patient_hmo_coverages_patient" ON "patient_hmo_coverages" ("patient_id")`);
  await q.query(`CREATE TABLE "hmo_cases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reference" varchar(40) NOT NULL, "coverage_id" uuid NOT NULL, "care_request_id" uuid NOT NULL, "hospital_provider_id" uuid NOT NULL, "eligibility_status" varchar(20) NOT NULL DEFAULT 'PENDING', "eligibility_reference" varchar, "eligibility_notes" text, "eligibility_verified_at" TIMESTAMPTZ, "eligibility_verified_by" uuid, "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(), "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(), CONSTRAINT "UQ_hmo_cases_reference" UNIQUE ("reference"), CONSTRAINT "PK_hmo_cases" PRIMARY KEY ("id"), CONSTRAINT "FK_hmo_case_coverage" FOREIGN KEY ("coverage_id") REFERENCES "patient_hmo_coverages"("id") ON DELETE RESTRICT, CONSTRAINT "FK_hmo_case_care" FOREIGN KEY ("care_request_id") REFERENCES "care_requests"("id") ON DELETE RESTRICT, CONSTRAINT "FK_hmo_case_hospital" FOREIGN KEY ("hospital_provider_id") REFERENCES "providers"("id") ON DELETE RESTRICT)`);
  await q.query(`CREATE TABLE "hmo_authorizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reference" varchar(40) NOT NULL, "hmo_case_id" uuid NOT NULL, "status" varchar(30) NOT NULL DEFAULT 'PENDING', "requested_services" jsonb NOT NULL, "clinical_reason" text, "requested_amount_minor" bigint, "currency" char(3) NOT NULL DEFAULT 'NGN', "supporting_documents" jsonb NOT NULL DEFAULT '[]'::jsonb, "authorization_code" varchar, "approved_services" jsonb NOT NULL DEFAULT '[]'::jsonb, "approved_amount_minor" bigint, "copay_amount_minor" bigint, "valid_until" TIMESTAMPTZ, "hmo_comments" text, "delivered_services" jsonb NOT NULL DEFAULT '[]'::jsonb, "service_confirmed_at" TIMESTAMPTZ, "service_confirmed_by" uuid, "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(), "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(), CONSTRAINT "UQ_hmo_authorizations_reference" UNIQUE ("reference"), CONSTRAINT "PK_hmo_authorizations" PRIMARY KEY ("id"), CONSTRAINT "FK_hmo_auth_case" FOREIGN KEY ("hmo_case_id") REFERENCES "hmo_cases"("id") ON DELETE RESTRICT)`);
  await q.query(`CREATE TABLE "hmo_claims" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reference" varchar(40) NOT NULL, "authorization_id" uuid NOT NULL, "status" varchar(30) NOT NULL DEFAULT 'DRAFT', "services" jsonb NOT NULL, "claimed_amount_minor" bigint NOT NULL, "currency" char(3) NOT NULL, "submitted_at" TIMESTAMPTZ, "paid_at" TIMESTAMPTZ, "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(), "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(), CONSTRAINT "UQ_hmo_claims_reference" UNIQUE ("reference"), CONSTRAINT "UQ_hmo_claim_auth" UNIQUE ("authorization_id"), CONSTRAINT "PK_hmo_claims" PRIMARY KEY ("id"), CONSTRAINT "FK_hmo_claim_auth" FOREIGN KEY ("authorization_id") REFERENCES "hmo_authorizations"("id") ON DELETE RESTRICT)`);
 }
 public async down(q:QueryRunner):Promise<void>{for(const t of ['hmo_claims','hmo_authorizations','hmo_cases','patient_hmo_coverages','hmo_plans','hmos']) await q.query(`DROP TABLE "${t}"`);}
}