import { BadRequestException, ConflictException, NotFoundException } from '@nestjs/common'; import { ClinicalRecordAccessService } from './clinical-record-access.service'; import { ClinicalRecordAccessGrant } from './entities/clinical-record-access-grant.entity'; import { ClinicalRecordAccessAudit } from './entities/clinical-record-access-audit.entity'; import { ClinicalRecord } from './entities/clinical-record.entity'; import { ClinicalRecordAttachment } from './entities/clinical-record-attachment.entity'; import { Patient } from '../patients/entities/patient.entity'; import { Provider } from '../providers/entities/provider.entity'; import { ClinicalRecordAccessScope } from './enums/clinical-record-access-scope.enum'; import { ClinicalRecordType } from './enums/clinical-record-type.enum'; import { ClinicalRecordStatus } from './enums/clinical-record-status.enum'; import { ClinicalRecordAccessAction } from './enums/clinical-record-access-action.enum';
describe('ClinicalRecordAccessService', () => {
 const user: any = { id: 'patient-user' }; const providerUser: any = { id: 'provider-user' }; const patient: any = { id: 'patient-id', userId: user.id, givenName: 'Ada', familyName: 'Okafor', status: 'ACTIVE', deletedAt: null }; const provider: any = { id: 'provider-id', providerReference: 'SCPR-74A176AB04848BE2D3977F8493D29CE5', displayName: 'Prime Diagnostics', providerType: 'DIAGNOSTIC_CENTRE', status: 'ACTIVE', onboardingStatus: 'APPROVED', deletedAt: null };
 let record: any; let grant: any; let grantRepo: any; let auditRepo: any; let recordRepo: any; let attachmentRepo: any; let providerRepo: any; let providerQb: any; let manager: any; let recordsService: any; let storage: any; let subject: ClinicalRecordAccessService; let grantQb: any;
 const qb = () => { const value: any = {}; for (const method of ['select','innerJoinAndSelect','leftJoinAndSelect','where','andWhere','orderBy','addOrderBy','skip','take']) value[method] = jest.fn().mockReturnValue(value); value.getOne = jest.fn(); value.getManyAndCount = jest.fn().mockResolvedValue([[], 0]); return value; };
 beforeEach(() => {
  record = { id: 'record-id', reference: 'SC-CLR-ABCDEF123456', patientId: patient.id, patient, providerId: 'origin-provider', provider: { ...provider, id: 'origin-provider' }, recordType: ClinicalRecordType.LAB_RESULT, status: ClinicalRecordStatus.FINALIZED, title: 'Full Blood Count', summary: null, attachments: [], occurredAt: new Date(), finalizedAt: new Date(), createdAt: new Date(), updatedAt: new Date(), careRequest: null, careAppointment: null, careServiceDefinition: null, consultation: null };
  grant = { id: 'grant-id', reference: 'SC-CRG-ABCDEF123456', patientId: patient.id, granteeProviderId: provider.id, granteeProvider: provider, scope: ClinicalRecordAccessScope.ALL_RECORDS, recordType: null, clinicalRecordId: null, clinicalRecord: null, grantedByUserId: user.id, grantedAt: new Date(), expiresAt: null, revokedAt: null, createdAt: new Date(), updatedAt: new Date() };
  grantQb = qb(); grantQb.getOne.mockResolvedValue(null);
  grantRepo = { manager: null, create: jest.fn(value => ({ ...grant, ...value })), save: jest.fn(async value => value), findOne: jest.fn().mockResolvedValue(grant), createQueryBuilder: jest.fn(() => grantQb) };
  auditRepo = { create: jest.fn(value => value), save: jest.fn(async value => value), createQueryBuilder: jest.fn(() => qb()) };
  recordRepo = { findOne: jest.fn().mockResolvedValue(record), createQueryBuilder: jest.fn(() => qb()) }; attachmentRepo = { findOne: jest.fn().mockResolvedValue({ clinicalRecordId: record.id, reference: 'SC-CLA-ABCDEF123456', storagePublicId: 'opaque', storageResourceType: 'raw', storageVersion: '1', storageFormat: 'pdf' }) };
  const patientRepo: any = { findOne: jest.fn().mockResolvedValue(patient), findOneOrFail: jest.fn().mockResolvedValue(patient) }; providerQb = qb(); providerQb.getOne.mockResolvedValue(provider); providerRepo = { createQueryBuilder: jest.fn(() => providerQb) };
  manager = { transaction: jest.fn(async work => work(manager)), getRepository: jest.fn(entity => entity === ClinicalRecordAccessGrant ? grantRepo : entity === ClinicalRecordAccessAudit ? auditRepo : entity === ClinicalRecord ? recordRepo : entity === ClinicalRecordAttachment ? attachmentRepo : entity === Patient ? patientRepo : entity === Provider ? providerRepo : {}) }; grantRepo.manager = manager;
  recordsService = { sharedReadBuilder: jest.fn(() => { const value = qb(); value.getOne.mockResolvedValue(record); return value; }), projectRecord: jest.fn(row => ({ reference: row.reference, provider: { providerReference: row.provider.providerReference }, attachments: [] })) }; storage = { createAccessUrl: jest.fn().mockResolvedValue('https://signed.example/private') };
  subject = new ClinicalRecordAccessService(grantRepo, auditRepo, patientRepo, providerRepo, { resolveOperational: jest.fn().mockResolvedValue(provider) } as any, recordsService, storage);
 });
 it('lists operational Providers independently of marketplace capabilities with safe search and pagination', async () => { providerQb.getManyAndCount.mockResolvedValue([[provider], 1]); const result: any = await subject.listEligibleProviders(user, { page: 2, limit: 5, q: 'prime' }); expect(providerQb.where).toHaveBeenCalledWith('provider.status = :active', { active: 'ACTIVE' }); expect(providerQb.andWhere).toHaveBeenCalledWith('provider.onboardingStatus = :approved', { approved: 'APPROVED' }); expect(providerQb.andWhere).toHaveBeenCalledWith('provider.deletedAt IS NULL'); expect(providerQb.andWhere).toHaveBeenCalledWith('provider.displayName ILIKE :search', { search: '%prime%' }); expect(providerQb.orderBy).toHaveBeenCalledWith('provider.displayName', 'ASC'); expect(providerQb.addOrderBy).toHaveBeenCalledWith('provider.providerReference', 'ASC'); expect(providerQb.skip).toHaveBeenCalledWith(5); expect(providerQb.take).toHaveBeenCalledWith(5); expect(result).toEqual({ items: [{ providerReference: provider.providerReference, displayName: provider.displayName, providerType: provider.providerType, location: { city: undefined, stateOrRegion: undefined, countryCode: undefined } }], page: 2, limit: 5, total: 1, totalPages: 1 }); expect(JSON.stringify(result)).not.toContain('provider-id'); expect(JSON.stringify(result)).not.toContain('email'); expect(JSON.stringify(result)).not.toContain('commission'); });
 it('independently rejects grant creation when the shared eligibility query no longer resolves the Provider', async () => { providerQb.getOne.mockResolvedValueOnce(null); await expect(subject.createGrant(user, { providerReference: provider.providerReference, scope: ClinicalRecordAccessScope.ALL_RECORDS })).rejects.toBeInstanceOf(NotFoundException); expect(providerQb.andWhere).toHaveBeenCalledWith('provider.providerReference = :providerReference', { providerReference: provider.providerReference }); expect(grantRepo.save).not.toHaveBeenCalled(); });
 it.each([[ClinicalRecordAccessScope.ALL_RECORDS, {}], [ClinicalRecordAccessScope.RECORD_TYPE, { recordType: ClinicalRecordType.LAB_RESULT }], [ClinicalRecordAccessScope.SINGLE_RECORD, { clinicalRecordReference: 'SC-CLR-ABCDEF123456' }]])('creates patient-owned %s grants using provider public reference', async (scope, extra) => { const result: any = await subject.createGrant(user, { providerReference: provider.providerReference, scope, ...extra }); expect(result).toMatchObject({ scope, status: 'ACTIVE', provider: { providerReference: provider.providerReference } }); expect(grantRepo.save).toHaveBeenCalledWith(expect.objectContaining({ patientId: patient.id, granteeProviderId: provider.id, grantedByUserId: user.id })); });
 it('requires correct scope fields, future expiry, and owned finalized single record', async () => { await expect(subject.createGrant(user, { providerReference: provider.providerReference, scope: ClinicalRecordAccessScope.RECORD_TYPE })).rejects.toBeInstanceOf(BadRequestException); await expect(subject.createGrant(user, { providerReference: provider.providerReference, scope: ClinicalRecordAccessScope.ALL_RECORDS, expiresAt: new Date(Date.now()-1000).toISOString() })).rejects.toBeInstanceOf(BadRequestException); recordRepo.findOne.mockResolvedValueOnce(null); await expect(subject.createGrant(user, { providerReference: provider.providerReference, scope: ClinicalRecordAccessScope.SINGLE_RECORD, clinicalRecordReference: record.reference })).rejects.toBeInstanceOf(NotFoundException); });
 it('rejects exact active duplicates while allowing explicit overlapping scope semantics', async () => { grantQb.getOne.mockResolvedValueOnce(grant); await expect(subject.createGrant(user, { providerReference: provider.providerReference, scope: ClinicalRecordAccessScope.ALL_RECORDS })).rejects.toBeInstanceOf(ConflictException); });
 it('writes append-only VIEW and ATTACHMENT_ACCESS audit records only after a covering grant', async () => { grantQb.getOne.mockResolvedValue(grant); await expect(subject.getShared(providerUser, record.reference)).resolves.toMatchObject({ reference: record.reference, patient: { displayName: 'Ada O.' } }); expect(auditRepo.save).toHaveBeenCalledWith(expect.objectContaining({ action: ClinicalRecordAccessAction.VIEW, grantId: grant.id })); await expect(subject.sharedAttachmentAccess(providerUser, record.reference, 'SC-CLA-ABCDEF123456')).resolves.toEqual(expect.objectContaining({ url: 'https://signed.example/private' })); expect(auditRepo.save).toHaveBeenCalledWith(expect.objectContaining({ action: ClinicalRecordAccessAction.ATTACHMENT_ACCESS })); });
 it('denies absent, revoked, or expired grants regardless of care relationships', async () => { grantQb.getOne.mockResolvedValue(null); await expect(subject.getShared(providerUser, record.reference)).rejects.toBeInstanceOf(NotFoundException); expect(auditRepo.save).not.toHaveBeenCalled(); });
 it('revokes without deletion and derives REVOKED/EXPIRED state', async () => { const revoked: any = await subject.revokeGrant(user, grant.reference); expect(revoked.status).toBe('REVOKED'); expect(grantRepo.save).toHaveBeenCalled(); grant.revokedAt = null; grant.expiresAt = new Date(Date.now()-1000); expect((subject as any).mapGrant(grant).status).toBe('EXPIRED'); });
 it('safe shared projections expose no internal or storage identifiers', async () => { grantQb.getOne.mockResolvedValue(grant); const result: any = await subject.getShared(providerUser, record.reference); expect(JSON.stringify(result)).not.toContain('record-id'); expect(JSON.stringify(result)).not.toContain('storagePublicId'); expect(JSON.stringify(result)).not.toContain('createdByUserId'); });
});
