import { ConflictException } from '@nestjs/common';
import { BookingLifecycleService } from './booking-lifecycle.service';
import { BookingStatusHistory } from './entities/booking-status-history.entity'; import { Booking } from './entities/booking.entity'; import { BookingStatus } from './enums/booking-status.enum';
import { ProviderAssignment } from '../providers/entities/provider-assignment.entity'; import { ProviderAssignmentHistory } from '../providers/entities/provider-assignment-history.entity'; import { ProviderBookingReservation } from '../providers/entities/provider-booking-reservation.entity'; import { ProviderAssignmentStatus } from '../providers/enums/provider-assignment-status.enum'; import { ProviderBookingReservationStatus } from '../providers/enums/provider-booking-reservation-status.enum';
const ids = { booking: '10000000-0000-4000-8000-000000000001', assignment: '20000000-0000-4000-8000-000000000001', provider: '30000000-0000-4000-8000-000000000001', actor: '40000000-0000-4000-8000-000000000001' };
describe('BookingLifecycleService', () => {
  let bookingRepo: any, assignmentRepo: any, reservationRepo: any, bookingHistory: any, assignmentHistory: any, subject: BookingLifecycleService;
  const booking = (status = BookingStatus.PENDING_PROVIDER_MATCH) => ({ id: ids.booking, bookingReference: 'SC-2026-ABCDEFGHIJKL', status, preferredDate: '2026-08-20', preferredTimeWindowStart: '09:00', preferredTimeWindowEnd: '11:00', preferredTimezone: 'Africa/Lagos', cancellationReason: null });
  const assignment = (status: ProviderAssignmentStatus) => ({ id: ids.assignment, bookingId: ids.booking, providerId: ids.provider, status, reasonCode: null, reasonNote: null });
  beforeEach(() => { bookingRepo={ findOne:jest.fn().mockResolvedValue(booking()), save:jest.fn(async(v)=>v) }; assignmentRepo={ find:jest.fn().mockResolvedValue([]), save:jest.fn(async(v)=>v) }; reservationRepo={ find:jest.fn().mockResolvedValue([]), save:jest.fn(async(v)=>v) }; bookingHistory={ create:jest.fn(v=>v), save:jest.fn(async(v)=>v) }; assignmentHistory={ create:jest.fn(v=>v), save:jest.fn(async(v)=>v) }; const manager:any={ getRepository:jest.fn((e)=>e===Booking?bookingRepo:e===ProviderAssignment?assignmentRepo:e===ProviderBookingReservation?reservationRepo:e===BookingStatusHistory?bookingHistory:assignmentHistory) }; bookingRepo.manager={ transaction:jest.fn(async(fn:any)=>fn(manager)) }; subject=new BookingLifecycleService(bookingRepo); });
  it('cancels an unassigned booking with booking history', async () => { const result=await subject.cancelBooking('SC-2026-ABCDEFGHIJKL',ids.actor,{ reason:'Changed plans' }); expect(result).toMatchObject({ bookingStatus:BookingStatus.CANCELLED, cancelledAssignmentCount:0, releasedReservationCount:0 }); expect(bookingHistory.save).toHaveBeenCalledWith(expect.objectContaining({ toStatus:BookingStatus.CANCELLED, reasonNote:'Changed plans' })); });
  it.each([ProviderAssignmentStatus.OFFERED, ProviderAssignmentStatus.ACCEPTED, ProviderAssignmentStatus.CONFIRMED])('cancels %s assignment and its active reservation when present', async (status) => { assignmentRepo.find.mockResolvedValue([assignment(status)]); if(status!==ProviderAssignmentStatus.OFFERED) reservationRepo.find.mockResolvedValue([{ id:'reservation',providerAssignmentId:ids.assignment,status:status===ProviderAssignmentStatus.CONFIRMED?ProviderBookingReservationStatus.CONFIRMED:ProviderBookingReservationStatus.HELD,releasedAt:null }]); const result=await subject.cancelBooking('SC-2026-ABCDEFGHIJKL',ids.actor,{}); expect(assignmentRepo.save).toHaveBeenCalledWith(expect.objectContaining({ status:ProviderAssignmentStatus.CANCELLED })); expect(assignmentHistory.save).toHaveBeenCalledWith(expect.objectContaining({ fromStatus:status,toStatus:ProviderAssignmentStatus.CANCELLED })); if(status!==ProviderAssignmentStatus.OFFERED) expect(reservationRepo.save).toHaveBeenCalledWith(expect.objectContaining({ status:ProviderBookingReservationStatus.CANCELLED, releasedAt:expect.any(Date) })); expect(result.cancelledAssignmentCount).toBe(1); });
  it.each([BookingStatus.COMPLETED, BookingStatus.CANCELLED, BookingStatus.EXPIRED])('rejects cancellation of terminal %s booking', async(status)=>{ bookingRepo.findOne.mockResolvedValue(booking(status)); await expect(subject.cancelBooking('SC-2026-ABCDEFGHIJKL',ids.actor,{})).rejects.toBeInstanceOf(ConflictException); });
  it('reschedules an unassigned pending booking and records a same-status audit event', async()=>{ const result=await subject.rescheduleBooking('SC-2026-ABCDEFGHIJKL',ids.actor,{preferredDate:'2026-08-28',preferredTimeFrom:'12:00',preferredTimeTo:'14:00',preferredTimezone:'Europe/London'}); expect(result).toMatchObject({bookingStatus:BookingStatus.PENDING_PROVIDER_MATCH,preferredDate:'2026-08-28',preferredTimezone:'Europe/London'}); expect(bookingHistory.save).toHaveBeenCalledWith(expect.objectContaining({fromStatus:BookingStatus.PENDING_PROVIDER_MATCH,toStatus:BookingStatus.PENDING_PROVIDER_MATCH,reasonCode:'BOOKING_RESCHEDULED'})); });
  it.each([ProviderAssignmentStatus.OFFERED, ProviderAssignmentStatus.ACCEPTED, ProviderAssignmentStatus.CONFIRMED])('reschedules with %s assignment by closing it and requiring fresh matching', async(status)=>{ bookingRepo.findOne.mockResolvedValue(booking(status===ProviderAssignmentStatus.CONFIRMED?BookingStatus.PROVIDER_ASSIGNED:BookingStatus.PENDING_PROVIDER_MATCH)); assignmentRepo.find.mockResolvedValue([assignment(status)]); if(status!==ProviderAssignmentStatus.OFFERED) reservationRepo.find.mockResolvedValue([{id:'reservation',providerAssignmentId:ids.assignment,status:ProviderBookingReservationStatus.HELD,releasedAt:null}]); const result=await subject.rescheduleBooking('SC-2026-ABCDEFGHIJKL',ids.actor,{preferredDate:'2026-08-28',preferredTimeFrom:'12:00',preferredTimeTo:'14:00',preferredTimezone:'Africa/Lagos'}); expect(result.bookingStatus).toBe(BookingStatus.PENDING_PROVIDER_MATCH); expect(assignmentRepo.save).toHaveBeenCalledWith(expect.objectContaining({status:ProviderAssignmentStatus.CANCELLED})); if(status!==ProviderAssignmentStatus.OFFERED) expect(reservationRepo.save).toHaveBeenCalledWith(expect.objectContaining({status:ProviderBookingReservationStatus.RELEASED})); });
  it.each([BookingStatus.DRAFT, BookingStatus.AWAITING_FUNDING])('preserves pre-matching status %s during reschedule',async(status)=>{ bookingRepo.findOne.mockResolvedValue(booking(status)); expect((await subject.rescheduleBooking('SC-2026-ABCDEFGHIJKL',ids.actor,{preferredDate:'2026-08-28',preferredTimeFrom:'12:00',preferredTimeTo:'14:00',preferredTimezone:'Africa/Lagos'})).bookingStatus).toBe(status); });
});
