import { Transform,Type } from 'class-transformer';import { ArrayMaxSize,IsArray,IsEnum,IsInt,IsNotEmpty,IsObject,IsOptional,IsString,Length,Max,Min,ValidateNested } from 'class-validator';import { GuidedSelfCheckAnswerState } from '../enums/guided-self-check-questionnaire.enum';import { GuidedSelfCheckClinicalRule,GuidedSelfCheckClassification,GuidedSelfCheckPatientMessageKey } from '../enums/guided-self-check-classification.enum';
export class AuthorizeClinicalGovernanceDto{@IsString()@IsNotEmpty()providerReference!:string;@IsOptional()@IsString()@Length(1,500)reason?:string;}
export class DisableClinicalGovernanceDto{@IsString()@Length(1,500)reason!:string;}
export class RulesetMessageKeysDto{@IsEnum(GuidedSelfCheckPatientMessageKey)green!:GuidedSelfCheckPatientMessageKey;@IsEnum(GuidedSelfCheckPatientMessageKey)amber!:GuidedSelfCheckPatientMessageKey;@IsEnum(GuidedSelfCheckPatientMessageKey)red!:GuidedSelfCheckPatientMessageKey;}
export class CreateClinicalRulesetDto{@IsInt()@Min(1)questionnaireVersion!:number;@IsString()@Length(1,140)name!:string;@IsOptional()@IsString()@Length(1,2000)description?:string;@IsArray()@ArrayMaxSize(200)rules!:GuidedSelfCheckClinicalRule[];@ValidateNested()@Type(()=>RulesetMessageKeysDto)patientMessageKeys!:RulesetMessageKeysDto;}
export class UpdateClinicalRulesetDto{@IsOptional()@IsString()@Length(1,140)name?:string;@IsOptional()@IsString()@Length(1,2000)description?:string;@IsOptional()@IsArray()@ArrayMaxSize(200)rules?:GuidedSelfCheckClinicalRule[];@IsOptional()@ValidateNested()@Type(()=>RulesetMessageKeysDto)patientMessageKeys?:RulesetMessageKeysDto;}
export class GovernanceNoteDto{@IsOptional()@IsString()@Length(1,1000)note?:string;}
export class SyntheticAnswerDto{@IsString()@IsNotEmpty()questionKey!:string;@IsEnum(GuidedSelfCheckAnswerState)state!:GuidedSelfCheckAnswerState;@IsOptional()value?:unknown;}
export class SimulateClinicalRulesetDto{@IsArray()@ArrayMaxSize(300)@ValidateNested({each:true})@Type(()=>SyntheticAnswerDto)answers!:SyntheticAnswerDto[];}
export class RulesetListQueryDto{@IsOptional()@Type(()=>Number)@IsInt()@Min(1)page=1;@IsOptional()@Type(()=>Number)@IsInt()@Min(1)@Max(100)limit=20;}
