import { Type } from 'class-transformer';import { ArrayMaxSize,IsArray,IsBoolean,IsEmail,IsEnum,IsInt,IsNotEmpty,IsOptional,IsString,Length,Max,Min,ValidateNested } from 'class-validator';import { GuidedSelfCheckAnswerState } from '../enums/guided-self-check-questionnaire.enum';import { GuidedSelfCheckClinicalRule,GuidedSelfCheckPatientMessageKey,GuidedSelfCheckRulesetGovernanceStatus } from '../enums/guided-self-check-classification.enum';import { GuidedSelfCheckClinicalGovernanceAuthorizationStatus } from '../enums/guided-self-check-clinical-governance.enum';
import { Matches } from 'class-validator';
export class AuthorizeClinicalGovernanceDto{@IsEmail()userEmail!:string;@IsOptional()@IsString()providerReference?:string;@IsOptional()@IsString()@Length(1,500)reason?:string;}
export class DisableClinicalGovernanceDto{@IsString()@Length(1,500)reason!:string;}
export class RulesetMessageKeysDto{@IsEnum(GuidedSelfCheckPatientMessageKey)green!:GuidedSelfCheckPatientMessageKey;@IsEnum(GuidedSelfCheckPatientMessageKey)amber!:GuidedSelfCheckPatientMessageKey;@IsEnum(GuidedSelfCheckPatientMessageKey)red!:GuidedSelfCheckPatientMessageKey;}
export class CreateClinicalRulesetDto{@IsInt()@Min(1)questionnaireVersion!:number;@IsString()@Length(1,140)name!:string;@IsOptional()@IsString()@Length(1,2000)description?:string;@IsArray()@ArrayMaxSize(200)rules!:GuidedSelfCheckClinicalRule[];@ValidateNested()@Type(()=>RulesetMessageKeysDto)patientMessageKeys!:RulesetMessageKeysDto;}
export class UpdateClinicalRulesetDto{@IsOptional()@Matches(/^[0-9a-f]{64}$/)expectedContentHash?:string;@IsOptional()@IsString()@Length(1,140)name?:string;@IsOptional()@IsString()@Length(1,2000)description?:string;@IsOptional()@IsArray()@ArrayMaxSize(200)rules?:GuidedSelfCheckClinicalRule[];@IsOptional()@ValidateNested()@Type(()=>RulesetMessageKeysDto)patientMessageKeys?:RulesetMessageKeysDto;}
export class GovernanceNoteDto{@IsOptional()@IsString()@Length(1,1000)note?:string;}
export class SyntheticAnswerDto{@IsString()@IsNotEmpty()questionKey!:string;@IsEnum(GuidedSelfCheckAnswerState)state!:GuidedSelfCheckAnswerState;@IsOptional()value?:unknown;}
export class SimulateClinicalRulesetDto{@IsArray()@ArrayMaxSize(300)@ValidateNested({each:true})@Type(()=>SyntheticAnswerDto)answers!:SyntheticAnswerDto[];}
export class RulesetListQueryDto{@IsOptional()@Type(()=>Number)@IsInt()@Min(1)page=1;@IsOptional()@Type(()=>Number)@IsInt()@Min(1)@Max(100)limit=20;@IsOptional()@IsEnum(GuidedSelfCheckRulesetGovernanceStatus)status?:GuidedSelfCheckRulesetGovernanceStatus;@IsOptional()@Type(()=>Number)@IsInt()@Min(1)questionnaireVersion?:number;@IsOptional()@Type(()=>Boolean)@IsBoolean()isActive?:boolean;}
export class GovernanceAuthorizationListQueryDto{@IsOptional()@Type(()=>Number)@IsInt()@Min(1)page=1;@IsOptional()@Type(()=>Number)@IsInt()@Min(1)@Max(100)limit=20;@IsOptional()@IsEnum(GuidedSelfCheckClinicalGovernanceAuthorizationStatus)status?:GuidedSelfCheckClinicalGovernanceAuthorizationStatus;}
