export enum MatchingQueueReadiness {
  READY = 'READY',
  FUNDING_INCOMPLETE = 'FUNDING_INCOMPLETE',
  INCOMPLETE_SCHEDULING = 'INCOMPLETE_SCHEDULING',
  ACTIVE_OFFER = 'ACTIVE_OFFER',
  ACCEPTED_AWAITING_CONFIRMATION = 'ACCEPTED_AWAITING_CONFIRMATION',
  UNFULFILLABLE = 'UNFULFILLABLE',
  ALREADY_ASSIGNED = 'ALREADY_ASSIGNED',
}
