export enum ProviderServiceAddonConfigurationUnavailableReason {
  PROVIDER_CONFIGURATION_DISABLED = 'PROVIDER_CONFIGURATION_DISABLED',
  CANONICAL_CONTENT_INACTIVE = 'CANONICAL_CONTENT_INACTIVE',
  PACKAGE_ELIGIBILITY_INACTIVE = 'PACKAGE_ELIGIBILITY_INACTIVE',
}
