export enum BookingStatus {
  DRAFT = 'DRAFT',
  AWAITING_FUNDING = 'AWAITING_FUNDING',
  PENDING_PROVIDER_MATCH = 'PENDING_PROVIDER_MATCH',
  AWAITING_PROVIDER_RESPONSE = 'AWAITING_PROVIDER_RESPONSE',
  PROVIDER_ASSIGNED = 'PROVIDER_ASSIGNED',
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  UNFULFILLABLE = 'UNFULFILLABLE',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}
