import { BadRequestException, ConflictException } from '@nestjs/common';
import { BookingStatusHistory } from '../bookings/entities/booking-status-history.entity';
import { Booking } from '../bookings/entities/booking.entity';
import { BookingStatus } from '../bookings/enums/booking-status.enum';
import { FulfilmentMode } from '../health-checks/entities/fulfilment-mode.entity';
import { HealthCheckPackage } from '../health-checks/entities/health-check-package.entity';
import { ProviderAssignment } from './entities/provider-assignment.entity';
import { ProviderBookingReservation } from './entities/provider-booking-reservation.entity';
import { ProviderLocation } from './entities/provider-location.entity';
import { Provider } from './entities/provider.entity';
import { ProviderAssignmentStatus } from './enums/provider-assignment-status.enum';
import { ProviderBookingReservationStatus } from './enums/provider-booking-reservation-status.enum';
import { ProviderStatus } from './enums/provider-status.enum';
import { AdminBookingSchedulingService } from './admin-booking-scheduling.service';

describe('AdminBookingSchedulingService', () => {
  const ids = { booking: 'booking-1', assignment: 'assignment-1', provider: 'provider-1', location: 'location-1', actor: 'actor-1', package: 'package-1', mode: 'mode-1' };
  const dto: any = { date: '2026-08-25', timeFrom: '09:00', timeTo: '10:00', timezone: 'Africa/Lagos' };
  let booking: any; let assignment: any; let provider: any; let mode: any; let reservation: any; let location: any; let repositories: Map<any, any>; let capabilities: any; let subject: AdminBookingSchedulingService; let histories: any[];
  beforeEach(() => {
    booking = { id: ids.booking, bookingReference: 'SC-2026-ABCDEF123456', status: BookingStatus.PROVIDER_ASSIGNED, healthCheckPackageId: ids.package, fulfilmentModeId: ids.mode, preferredDate: '2026-08-24', preferredTimeWindowStart: '08:00', preferredTimeWindowEnd: '09:00', preferredTimezone: 'Africa/Lagos', scheduledDate: null, scheduledTimeFrom: null, scheduledTimeTo: null, scheduledTimezone: null, providerLocationId: null };
    assignment = { id: ids.assignment, bookingId: ids.booking, providerId: ids.provider, status: ProviderAssignmentStatus.CONFIRMED };
    provider = { id: ids.provider, displayName: 'SmartClinic Ikeja', status: ProviderStatus.ACTIVE, deletedAt: null };
    mode = { id: ids.mode, code: 'HOME_VISIT', isActive: true }; reservation = { id: 'reservation-1', bookingId: ids.booking, providerId: ids.provider, providerAssignmentId: ids.assignment, status: ProviderBookingReservationStatus.CONFIRMED, scheduledDate: '2026-08-24', startTime: '08:00', endTime: '09:00', timezone: 'Africa/Lagos', providerLocationId: null };
    location = { id: ids.location, providerId: ids.provider, name: 'Ikeja Clinic', addressLine1: '1 Clinic Road', addressLine2: null, city: 'Ikeja', state: 'Lagos', countryCode: 'NG', isActive: true };
    histories = [];
    const repository = (row: any) => ({ findOne: jest.fn(async () => row), save: jest.fn(async (value) => value), create: jest.fn((value) => value) });
    repositories = new Map<any, any>([[Booking, repository(booking)], [ProviderAssignment, repository(assignment)], [Provider, repository(provider)], [HealthCheckPackage, repository({ id: ids.package, isActive: true })], [FulfilmentMode, repository(mode)], [ProviderBookingReservation, repository(reservation)], [ProviderLocation, repository(location)], [BookingStatusHistory, { create: jest.fn((value) => value), save: jest.fn(async (value) => { histories.push(value); return value; }) }]]);
    const manager: any = { getRepository: jest.fn((entity) => repositories.get(entity)), transaction: jest.fn(async (work) => work(manager)) }; (repositories.get(Booking) as any).manager = manager;
    capabilities = { findEligibleProviders: jest.fn().mockResolvedValue([{ providerId: ids.provider, providerLocationIds: [] }]) };
    subject = new AdminBookingSchedulingService(repositories.get(Booking), capabilities);
  });

  it('schedules a PROVIDER_ASSIGNED booking, preserves preferences, reconciles capacity, and appends history', async () => { const preferred = [booking.preferredDate, booking.preferredTimeWindowStart, booking.preferredTimeWindowEnd]; const result = await subject.schedule(booking.bookingReference, ids.actor, dto); expect(result).toMatchObject({ bookingStatus: BookingStatus.SCHEDULED, scheduledDate: dto.date, assignmentStatus: ProviderAssignmentStatus.CONFIRMED }); expect(booking.status).toBe(BookingStatus.SCHEDULED); expect([booking.preferredDate, booking.preferredTimeWindowStart, booking.preferredTimeWindowEnd]).toEqual(preferred); expect(reservation).toMatchObject({ scheduledDate: dto.date, startTime: dto.timeFrom, endTime: dto.timeTo, timezone: dto.timezone, status: ProviderBookingReservationStatus.CONFIRMED }); expect(histories).toEqual([expect.objectContaining({ fromStatus: BookingStatus.PROVIDER_ASSIGNED, toStatus: BookingStatus.SCHEDULED, reasonCode: 'BOOKING_SCHEDULED', actorUserId: ids.actor })]); expect(capabilities.findEligibleProviders).toHaveBeenCalledWith(ids.package, ids.mode, expect.objectContaining({ requestedDate: dto.date }), ids.assignment); });
  it.each([BookingStatus.DRAFT, BookingStatus.AWAITING_FUNDING, BookingStatus.PENDING_PROVIDER_MATCH, BookingStatus.UNFULFILLABLE, BookingStatus.IN_PROGRESS, BookingStatus.COMPLETED, BookingStatus.CANCELLED, BookingStatus.EXPIRED])('rejects lifecycle %s', async (status) => { booking.status = status; await expect(subject.schedule(booking.bookingReference, ids.actor, dto)).rejects.toBeInstanceOf(ConflictException); });
  it('requires a confirmed assignment and active provider', async () => { repositories.get(ProviderAssignment).findOne.mockResolvedValue(null); await expect(subject.schedule(booking.bookingReference, ids.actor, dto)).rejects.toBeInstanceOf(ConflictException); repositories.get(ProviderAssignment).findOne.mockResolvedValue(assignment); provider.status = ProviderStatus.SUSPENDED; await expect(subject.schedule(booking.bookingReference, ids.actor, dto)).rejects.toBeInstanceOf(ConflictException); });
  it('rejects invalid time order', async () => { await expect(subject.schedule(booking.bookingReference, ids.actor, { ...dto, timeFrom: '10:00', timeTo: '09:00' })).rejects.toBeInstanceOf(BadRequestException); });
  it('returns idempotently for the identical schedule and rejects a different repeat', async () => { Object.assign(booking, { status: BookingStatus.SCHEDULED, scheduledDate: dto.date, scheduledTimeFrom: '09:00:00', scheduledTimeTo: '10:00:00', scheduledTimezone: dto.timezone, providerLocationId: null, scheduledAt: new Date() }); await expect(subject.schedule(booking.bookingReference, ids.actor, dto)).resolves.toMatchObject({ bookingStatus: BookingStatus.SCHEDULED }); expect(histories).toHaveLength(0); await expect(subject.schedule(booking.bookingReference, ids.actor, { ...dto, timeTo: '11:00' })).rejects.toBeInstanceOf(ConflictException); });
  it('requires PROVIDER_LOCATION location ownership, activation, and capability linkage', async () => { mode.code = 'PROVIDER_LOCATION'; await expect(subject.schedule(booking.bookingReference, ids.actor, dto)).rejects.toBeInstanceOf(BadRequestException); capabilities.findEligibleProviders.mockResolvedValue([{ providerId: ids.provider, providerLocationIds: [ids.location] }]); await expect(subject.schedule(booking.bookingReference, ids.actor, { ...dto, providerLocationId: ids.location })).resolves.toMatchObject({ providerLocation: { id: ids.location, name: 'Ikeja Clinic' } }); expect(reservation.providerLocationId).toBe(ids.location); });
  it('rejects wrong, inactive, or unlinked provider locations', async () => { mode.code = 'PROVIDER_LOCATION'; capabilities.findEligibleProviders.mockResolvedValue([{ providerId: ids.provider, providerLocationIds: [] }]); await expect(subject.schedule(booking.bookingReference, ids.actor, { ...dto, providerLocationId: ids.location })).rejects.toBeInstanceOf(ConflictException); capabilities.findEligibleProviders.mockResolvedValue([{ providerId: ids.provider, providerLocationIds: [ids.location] }]); location.providerId = 'other'; await expect(subject.schedule(booking.bookingReference, ids.actor, { ...dto, providerLocationId: ids.location })).rejects.toBeInstanceOf(ConflictException); location.providerId = ids.provider; location.isActive = false; await expect(subject.schedule(booking.bookingReference, ids.actor, { ...dto, providerLocationId: ids.location })).rejects.toBeInstanceOf(ConflictException); });
  it('rejects providerLocationId for HOME_VISIT', async () => { await expect(subject.schedule(booking.bookingReference, ids.actor, { ...dto, providerLocationId: ids.location })).rejects.toBeInstanceOf(BadRequestException); });
  it('rejects unavailable or capacity-conflicted windows without changing the booking', async () => { capabilities.findEligibleProviders.mockResolvedValue([]); await expect(subject.schedule(booking.bookingReference, ids.actor, dto)).rejects.toBeInstanceOf(ConflictException); expect(booking.status).toBe(BookingStatus.PROVIDER_ASSIGNED); expect(histories).toHaveLength(0); });
});
