import { BadRequestException, ConflictException, NotFoundException } from '@nestjs/common';
import { ProviderCapabilitiesService } from './provider-capabilities.service';
import { ProviderStatus } from './enums/provider-status.enum';

const ids = { provider: '10000000-0000-4000-8000-000000000001', other: '10000000-0000-4000-8000-000000000002', package: '20000000-0000-4000-8000-000000000001', mode: '30000000-0000-4000-8000-000000000001', service: '40000000-0000-4000-8000-000000000001', location: '50000000-0000-4000-8000-000000000001' };
const now = new Date();
const repo = () => ({ findOne: jest.fn(), findOneBy: jest.fn(), find: jest.fn(), exists: jest.fn().mockResolvedValue(false), create: jest.fn((v) => v), save: jest.fn(async (v) => ({ id: v.id ?? ids.service, createdAt: now, updatedAt: now, locationLinks: [], ...v })), insert: jest.fn(), delete: jest.fn().mockResolvedValue({ affected: 1 }), createQueryBuilder: jest.fn() });

describe('ProviderCapabilitiesService', () => {
  let providers: any, services: any, locations: any, links: any, packages: any, modes: any, subject: ProviderCapabilitiesService;
  const provider = (status = ProviderStatus.ACTIVE, id = ids.provider) => ({ id, status });
  const service = (changes = {}) => ({ id: ids.service, providerId: ids.provider, healthCheckPackageId: ids.package, fulfilmentModeId: ids.mode, isActive: true, createdAt: now, updatedAt: now, locationLinks: [], ...changes });
  const location = (changes = {}) => ({ id: ids.location, providerId: ids.provider, name: 'Clinic', addressLine1: 'Road', addressLine2: null, city: 'Lagos', state: 'Lagos', countryCode: 'NG', latitude: null, longitude: null, isActive: true, createdAt: now, updatedAt: now, ...changes });
  beforeEach(() => { providers = repo(); services = repo(); locations = repo(); links = repo(); packages = repo(); modes = repo(); subject = new ProviderCapabilitiesService(providers, services, locations, links, packages, modes); providers.findOne.mockResolvedValue(provider()); packages.findOne.mockResolvedValue({ id: ids.package, isActive: true }); modes.findOne.mockResolvedValue({ id: ids.mode, code: 'PROVIDER_LOCATION', isActive: true }); services.findOne.mockResolvedValue(service()); locations.findOne.mockResolvedValue(location()); modes.findOneBy.mockResolvedValue({ id: ids.mode, code: 'PROVIDER_LOCATION', isActive: true }); packages.findOneBy.mockResolvedValue({ id: ids.package, isActive: true }); });

  it('creates a provider service', async () => expect((await subject.createService(ids.provider, { healthCheckPackageId: ids.package, fulfilmentModeId: ids.mode })).isActive).toBe(true));
  it('prevents duplicate provider/package/mode capabilities', async () => { services.exists.mockResolvedValue(true); await expect(subject.createService(ids.provider, { healthCheckPackageId: ids.package, fulfilmentModeId: ids.mode })).rejects.toBeInstanceOf(ConflictException); });
  it('rejects an inactive provider', async () => { providers.findOne.mockResolvedValue(provider(ProviderStatus.INACTIVE)); await expect(subject.createService(ids.provider, { healthCheckPackageId: ids.package, fulfilmentModeId: ids.mode })).rejects.toBeInstanceOf(BadRequestException); });
  it('rejects an inactive package', async () => { packages.findOne.mockResolvedValue({ id: ids.package, isActive: false }); await expect(subject.createService(ids.provider, { healthCheckPackageId: ids.package, fulfilmentModeId: ids.mode })).rejects.toBeInstanceOf(BadRequestException); });
  it('rejects an inactive fulfilment mode', async () => { modes.findOne.mockResolvedValue({ id: ids.mode, isActive: false }); await expect(subject.createService(ids.provider, { healthCheckPackageId: ids.package, fulfilmentModeId: ids.mode })).rejects.toBeInstanceOf(BadRequestException); });
  it('activates and deactivates a capability', async () => { expect((await subject.deactivateService(ids.service)).isActive).toBe(false); services.findOne.mockResolvedValue(service({ isActive: false })); expect((await subject.activateService(ids.service)).isActive).toBe(true); });
  it('creates and toggles a provider location', async () => { const created = await subject.createLocation(ids.provider, { name: 'Clinic', addressLine1: 'Road', city: 'Lagos', state: 'Lagos', countryCode: 'NG' }); expect(created.isActive).toBe(true); expect((await subject.deactivateLocation(ids.location)).isActive).toBe(false); locations.findOne.mockResolvedValue(location({ isActive: false })); expect((await subject.activateLocation(ids.location)).isActive).toBe(true); });
  it('links and unlinks a provider location', async () => { expect((await subject.linkLocation(ids.service, ids.location)).id).toBe(ids.service); await subject.unlinkLocation(ids.service, ids.location); expect(links.delete).toHaveBeenCalled(); });
  it('rejects cross-provider links', async () => { locations.findOne.mockResolvedValue(location({ providerId: ids.other })); await expect(subject.linkLocation(ids.service, ids.location)).rejects.toBeInstanceOf(ConflictException); });
  it('rejects duplicate links', async () => { links.exists.mockResolvedValue(true); await expect(subject.linkLocation(ids.service, ids.location)).rejects.toBeInstanceOf(ConflictException); });
  it('rejects locations for HOME_VISIT capabilities', async () => { modes.findOneBy.mockResolvedValue({ code: 'HOME_VISIT' }); await expect(subject.linkLocation(ids.service, ids.location)).rejects.toBeInstanceOf(BadRequestException); });
  it('reports a missing link when unlinking', async () => { links.delete.mockResolvedValue({ affected: 0 }); await expect(subject.unlinkLocation(ids.service, ids.location)).rejects.toBeInstanceOf(NotFoundException); });
  it('returns eligible active matching providers and applies all eligibility predicates', async () => { const qb: any = {}; for (const method of ['distinct', 'innerJoinAndSelect', 'leftJoinAndSelect', 'where', 'andWhere', 'orderBy']) qb[method] = jest.fn().mockReturnValue(qb); qb.getMany = jest.fn().mockResolvedValue([service()]); services.createQueryBuilder.mockReturnValue(qb); expect(await subject.findEligibleProviders(ids.package, ids.mode)).toHaveLength(1); expect(qb.andWhere.mock.calls.map((call: any[]) => call[0]).join(' ')).toContain('provider.status'); expect(qb.andWhere.mock.calls.map((call: any[]) => call[0]).join(' ')).toContain('service.isActive'); expect(qb.andWhere.mock.calls.map((call: any[]) => call[0]).join(' ')).toContain('package.isActive'); expect(qb.andWhere.mock.calls.map((call: any[]) => call[0]).join(' ')).toContain('mode.isActive'); });
  it('excludes pending invited, submitted, and rejected providers by requiring operational ACTIVE status', async () => { const qb: any = {}; for (const method of ['distinct', 'innerJoinAndSelect', 'leftJoinAndSelect', 'where', 'andWhere', 'orderBy']) qb[method] = jest.fn().mockReturnValue(qb); qb.getMany = jest.fn().mockResolvedValue([]); services.createQueryBuilder.mockReturnValue(qb); await subject.findEligibleProviders(ids.package, ids.mode); expect(qb.andWhere).toHaveBeenCalledWith('provider.status = :status', { status: ProviderStatus.ACTIVE }); });
  it.each(['inactive provider', 'inactive capability', 'wrong package', 'wrong fulfilment mode'])('returns no providers for %s after database filtering', async () => { const qb: any = {}; for (const method of ['distinct', 'innerJoinAndSelect', 'leftJoinAndSelect', 'where', 'andWhere', 'orderBy']) qb[method] = jest.fn().mockReturnValue(qb); qb.getMany = jest.fn().mockResolvedValue([]); services.createQueryBuilder.mockReturnValue(qb); expect(await subject.findEligibleProviders(ids.package, ids.mode)).toEqual([]); });
  it('applies recurring, exception, and only active capacity-reservation predicates', async () => { const qb: any = {}; for (const method of ['distinct', 'innerJoinAndSelect', 'leftJoinAndSelect', 'where', 'andWhere', 'orderBy']) qb[method] = jest.fn().mockReturnValue(qb); qb.getMany = jest.fn().mockResolvedValue([service()]); services.createQueryBuilder.mockReturnValue(qb); expect(await subject.findEligibleProviders(ids.package, ids.mode, { requestedDate: '2026-08-17', requestedStartTime: '10:00', requestedEndTime: '11:00', requestedTimezone: 'Africa/Lagos' })).toHaveLength(1); const sql = qb.andWhere.mock.calls.map((c: any[]) => c[0]).join(' '); expect(sql).toContain('provider_availability scope'); expect(sql).toContain("scope.type = 'AVAILABLE'"); expect(sql).toContain("scope.type = 'UNAVAILABLE'"); expect(sql).toContain('provider_booking_reservations reservation'); expect(sql).toContain("reservation.status IN ('HELD', 'CONFIRMED')"); expect(sql).not.toContain("reservation.status IN ('RELEASED'"); });
  it.each(['outside requested time', 'inactive availability'])('excludes a provider with %s after availability filtering', async () => { const qb: any = {}; for (const method of ['distinct', 'innerJoinAndSelect', 'leftJoinAndSelect', 'innerJoin', 'leftJoin', 'where', 'andWhere', 'orderBy']) qb[method] = jest.fn().mockReturnValue(qb); qb.getMany = jest.fn().mockResolvedValue([]); services.createQueryBuilder.mockReturnValue(qb); expect(await subject.findEligibleProviders(ids.package, ids.mode, { requestedDate: '2026-08-17', requestedStartTime: '10:00', requestedEndTime: '11:00', requestedTimezone: 'Africa/Lagos' })).toEqual([]); });
});
