import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { QueryFailedError, Repository } from 'typeorm';
import { CreateProviderAvailabilityExceptionDto } from './dto/create-provider-availability-exception.dto';
import { ProviderAvailabilityExceptionResponseDto } from './dto/provider-availability-exception-response.dto';
import { UpdateProviderAvailabilityExceptionDto } from './dto/update-provider-availability-exception.dto';
import { ProviderAvailabilityException } from './entities/provider-availability-exception.entity';
import { ProviderLocation } from './entities/provider-location.entity';
import { ProviderService } from './entities/provider-service.entity';
import { Provider } from './entities/provider.entity';
import { ProviderStatus } from './enums/provider-status.enum';

@Injectable()
export class ProviderAvailabilityExceptionsService {
  constructor(@InjectRepository(ProviderAvailabilityException) private readonly exceptions: Repository<ProviderAvailabilityException>, @InjectRepository(Provider) private readonly providers: Repository<Provider>, @InjectRepository(ProviderService) private readonly services: Repository<ProviderService>, @InjectRepository(ProviderLocation) private readonly locations: Repository<ProviderLocation>) {}
  async list(providerId: string) { await this.requireProvider(providerId); return (await this.exceptions.find({ where: { providerId }, order: { date: 'ASC', startTime: 'ASC' } })).map(ProviderAvailabilityExceptionResponseDto.fromEntity); }
  async get(id: string) { return ProviderAvailabilityExceptionResponseDto.fromEntity(await this.requireException(id)); }
  async create(providerId: string, dto: CreateProviderAvailabilityExceptionDto) {
    await this.validateActiveScope(providerId, dto.providerServiceId ?? null, dto.providerLocationId ?? null); this.validateTimes(dto.startTime ?? null, dto.endTime ?? null);
    await this.rejectConflict(providerId, dto.date, dto.timezone, dto.startTime ?? null, dto.endTime ?? null, dto.providerServiceId ?? null, dto.providerLocationId ?? null);
    try { return ProviderAvailabilityExceptionResponseDto.fromEntity(await this.exceptions.save(this.exceptions.create({ ...dto, providerId, providerServiceId: dto.providerServiceId ?? null, providerLocationId: dto.providerLocationId ?? null, startTime: dto.startTime ?? null, endTime: dto.endTime ?? null, reason: dto.reason ?? null, isActive: true }))); } catch (e) { this.rethrowConflict(e); }
  }
  async update(id: string, dto: UpdateProviderAvailabilityExceptionDto) {
    const value = await this.requireException(id); const candidate = { providerServiceId: dto.providerServiceId !== undefined ? dto.providerServiceId : value.providerServiceId, providerLocationId: dto.providerLocationId !== undefined ? dto.providerLocationId : value.providerLocationId, date: dto.date ?? value.date, startTime: dto.startTime !== undefined ? dto.startTime : value.startTime, endTime: dto.endTime !== undefined ? dto.endTime : value.endTime, timezone: dto.timezone ?? value.timezone, type: dto.type ?? value.type, reason: dto.reason !== undefined ? dto.reason : value.reason };
    this.validateTimes(candidate.startTime ?? null, candidate.endTime ?? null); if (value.isActive) { await this.validateActiveScope(value.providerId, candidate.providerServiceId ?? null, candidate.providerLocationId ?? null); await this.rejectConflict(value.providerId, candidate.date, candidate.timezone, candidate.startTime ?? null, candidate.endTime ?? null, candidate.providerServiceId ?? null, candidate.providerLocationId ?? null, value.id); }
    Object.assign(value, candidate); try { return ProviderAvailabilityExceptionResponseDto.fromEntity(await this.exceptions.save(value)); } catch (e) { this.rethrowConflict(e); }
  }
  async activate(id: string) { const value = await this.requireException(id); await this.validateActiveScope(value.providerId, value.providerServiceId, value.providerLocationId); await this.rejectConflict(value.providerId, value.date, value.timezone, value.startTime, value.endTime, value.providerServiceId, value.providerLocationId, value.id); value.isActive = true; try { return ProviderAvailabilityExceptionResponseDto.fromEntity(await this.exceptions.save(value)); } catch (e) { this.rethrowConflict(e); } }
  async deactivate(id: string) { const value = await this.requireException(id); value.isActive = false; return ProviderAvailabilityExceptionResponseDto.fromEntity(await this.exceptions.save(value)); }
  private validateTimes(start: string | null, end: string | null) { if ((start === null) !== (end === null)) throw new BadRequestException('startTime and endTime must both be supplied or both omitted'); if (start && end && this.seconds(start) >= this.seconds(end)) throw new BadRequestException('startTime must be before endTime; overnight exceptions are not supported'); }
  private seconds(v: string) { const [h, m, s = '0'] = v.split(':'); return +h * 3600 + +m * 60 + +s; }
  private async validateActiveScope(providerId: string, serviceId: string | null, locationId: string | null) { const p = await this.requireProvider(providerId); if (![ProviderStatus.ACTIVE, ProviderStatus.PENDING].includes(p.status)) throw new BadRequestException('Provider must be active or pending to manage exceptions'); if (serviceId) { const s = await this.services.findOne({ where: { id: serviceId } }); if (!s) throw new NotFoundException('Provider service not found'); if (s.providerId !== providerId) throw new ConflictException('Provider service belongs to a different provider'); if (!s.isActive) throw new BadRequestException('Provider service is inactive'); } if (locationId) { const l = await this.locations.findOne({ where: { id: locationId } }); if (!l) throw new NotFoundException('Provider location not found'); if (l.providerId !== providerId) throw new ConflictException('Provider location belongs to a different provider'); if (!l.isActive) throw new BadRequestException('Provider location is inactive'); } }
  private async rejectConflict(providerId: string, date: string, timezone: string, start: string | null, end: string | null, serviceId: string | null, locationId: string | null, excludeId?: string) { const q = this.exceptions.createQueryBuilder('exception').where('exception.providerId = :providerId', { providerId }).andWhere('exception.date = :date', { date }).andWhere('exception.timezone = :timezone', { timezone }).andWhere('exception.providerServiceId IS NOT DISTINCT FROM :serviceId', { serviceId }).andWhere('exception.providerLocationId IS NOT DISTINCT FROM :locationId', { locationId }).andWhere('exception.isActive = true'); if (start && end) q.andWhere('(exception.startTime IS NULL OR (exception.startTime < :end AND exception.endTime > :start))', { start, end }); if (excludeId) q.andWhere('exception.id != :excludeId', { excludeId }); if (await q.getExists()) throw new ConflictException('Exception conflicts with an active exception for the same scope'); }
  private async requireProvider(id: string) { const v = await this.providers.findOne({ where: { id } }); if (!v) throw new NotFoundException('Provider not found'); return v; }
  private async requireException(id: string) { const v = await this.exceptions.findOne({ where: { id } }); if (!v) throw new NotFoundException('Provider availability exception not found'); return v; }
  private rethrowConflict(e: unknown): never { if (e instanceof QueryFailedError && (e.driverError as { constraint?: string }).constraint === 'EX_provider_availability_exceptions_active_overlap') throw new ConflictException('Exception conflicts with an active exception for the same scope'); throw e; }
}
