import { BadRequestException, ConflictException, NotFoundException } from '@nestjs/common';
import { ProviderServiceAreasService } from './provider-service-areas.service';
describe('ProviderServiceAreasService', () => {
  const area = { id: 'area-1', providerId: 'provider-1', providerServiceId: 'service-1', countryCode: 'NG', stateOrRegion: 'Lagos', city: 'Ikeja', postalCode: null, isActive: true };
  let areas: any; let services: any; let subject: ProviderServiceAreasService;
  beforeEach(() => { areas = { find: jest.fn().mockResolvedValue([area]), findOne: jest.fn().mockResolvedValue({ ...area }), create: jest.fn((v) => v), save: jest.fn(async (v) => v) }; services = { findOne: jest.fn().mockResolvedValue({ id: 'service-1', providerId: 'provider-1', isActive: true, fulfilmentMode: { code: 'HOME_VISIT', isActive: true }, healthCheckPackage: { isActive: true } }) }; subject = new ProviderServiceAreasService(areas, services); });
  it('creates and normalizes an owned HOME_VISIT area', async () => expect(await subject.create('provider-1', { providerServiceId: 'service-1', countryCode: 'ng', stateOrRegion: ' Lagos ', city: ' Ikeja ' })).toMatchObject({ countryCode: 'NG', stateOrRegion: 'Lagos', city: 'Ikeja', isActive: true }));
  it('rejects cross-provider and physical-location capabilities', async () => { services.findOne.mockResolvedValueOnce({ ...(await services.findOne()), providerId: 'other' }); await expect(subject.create('provider-1', { providerServiceId: 'service-1', countryCode: 'NG', stateOrRegion: 'Lagos' })).rejects.toBeInstanceOf(ConflictException); services.findOne.mockResolvedValue({ ...(await services.findOne()), providerId: 'provider-1', fulfilmentMode: { code: 'PROVIDER_LOCATION', isActive: true } }); await expect(subject.create('provider-1', { providerServiceId: 'service-1', countryCode: 'NG', stateOrRegion: 'Lagos' })).rejects.toBeInstanceOf(BadRequestException); });
  it('updates and toggles only owned records', async () => { await expect(subject.update('provider-1', 'area-1', { city: 'Lekki' })).resolves.toMatchObject({ city: 'Lekki' }); await expect(subject.deactivate('provider-1', 'area-1')).resolves.toMatchObject({ isActive: false }); areas.findOne.mockResolvedValue(null); await expect(subject.get('provider-1', 'other')).rejects.toBeInstanceOf(NotFoundException); });
});
