export enum CareRequestStatus {
  SUBMITTED = 'SUBMITTED',
  MATCHING = 'MATCHING',
  PROVIDER_SELECTED = 'PROVIDER_SELECTED',
  AWAITING_PROVIDER_RESPONSE = 'AWAITING_PROVIDER_RESPONSE',
  PROVIDER_ACCEPTED = 'PROVIDER_ACCEPTED',
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  DECLINED = 'DECLINED',
  UNFULFILLABLE = 'UNFULFILLABLE',
}
