import { BadGatewayException, BadRequestException, Inject, Injectable, ServiceUnavailableException } from '@nestjs/common';
import { ConfigType } from '@nestjs/config'; import { createHmac, timingSafeEqual } from 'node:crypto'; import { appConfig } from '../../config/app.config'; import { PaymentAttemptStatus } from '../enums/payment-attempt-status.enum'; import { InitializePaymentInput, InitializePaymentResult, PaymentProviderAdapter, PaymentProviderWebhookEvent, VerifyPaymentResult } from '../payment-provider.adapter';

interface PaystackEnvelope<T> { status: boolean; message?: string; data?: T; }
interface PaystackInitializeData { authorization_url?: string; access_code?: string; reference?: string; }
interface PaystackVerifyData { status?: string; reference?: string; amount?: number | string; currency?: string; paid_at?: string | null; }

export function decimalToSubunit(amount: string): string { if (!/^\d+(?:\.\d{1,2})?$/.test(amount)) throw new BadRequestException('Payment amount is not a valid two-decimal monetary value'); const [whole, fraction=''] = amount.split('.'); return `${BigInt(whole) * 100n + BigInt(fraction.padEnd(2,'0'))}`; }
export function subunitToDecimal(amount: number|string): string { const value=BigInt(String(amount)); return `${value/100n}.${(value%100n).toString().padStart(2,'0')}`; }

@Injectable()
export class PaystackPaymentProviderAdapter implements PaymentProviderAdapter {
  private readonly baseUrl='https://api.paystack.co';
  constructor(@Inject(appConfig.KEY) private readonly config:ConfigType<typeof appConfig>) {}
  async initializePayment(input:InitializePaymentInput):Promise<InitializePaymentResult>{const body:Record<string,unknown>={email:input.customerEmail,amount:decimalToSubunit(input.amount),currency:input.currency,reference:input.paymentReference,metadata:{booking_reference:input.bookingReference}};if(this.config.payments.paystack.callbackUrl)body.callback_url=this.config.payments.paystack.callbackUrl;const envelope=await this.request<PaystackInitializeData>('/transaction/initialize',{method:'POST',body:JSON.stringify(body)});if(!envelope.status||!envelope.data?.reference||!envelope.data.authorization_url)throw new BadGatewayException('Payment provider rejected initialization');return{providerCode:'PAYSTACK',providerReference:envelope.data.reference,status:PaymentAttemptStatus.AWAITING_CUSTOMER_ACTION,checkoutUrl:envelope.data.authorization_url};}
  async verifyPayment(reference:string):Promise<VerifyPaymentResult>{const envelope=await this.request<PaystackVerifyData>(`/transaction/verify/${encodeURIComponent(reference)}`,{method:'GET'});const data=envelope.data;if(!envelope.status||!data?.reference||data.amount===undefined||!data.currency)throw new BadGatewayException('Payment provider verification response was invalid');return{succeeded:data.status==='success',providerReference:data.reference,amount:subunitToDecimal(data.amount),currency:data.currency.toUpperCase(),occurredAt:data.paid_at?new Date(data.paid_at):new Date()};}
  verifyWebhookSignature(rawBody:Buffer,signature:string):boolean{const secret=this.secret();if(!/^[a-f0-9]{128}$/i.test(signature))return false;const expected=createHmac('sha512',secret).update(rawBody).digest('hex');return timingSafeEqual(Buffer.from(expected,'hex'),Buffer.from(signature,'hex'));}
  parseWebhook(rawBody:Buffer):PaymentProviderWebhookEvent{try{const event=JSON.parse(rawBody.toString('utf8')) as {event?:unknown;data?:{reference?:unknown}};return{type:typeof event.event==='string'?event.event:'unsupported',reference:typeof event.data?.reference==='string'?event.data.reference:null};}catch{throw new BadRequestException('Malformed payment webhook');}}
  private secret():string{const secret=this.config.payments.paystack.secretKey;if(!secret)throw new ServiceUnavailableException('Payment provider is not configured');return secret;}
  private async request<T>(path:string,init:RequestInit):Promise<PaystackEnvelope<T>>{const secret=this.secret();try{const response=await fetch(`${this.baseUrl}${path}`,{...init,headers:{Authorization:`Bearer ${secret}`,'Content-Type':'application/json'},signal:AbortSignal.timeout(10000)});if(!response.ok)throw new BadGatewayException('Payment provider request failed');const body=await response.json() as PaystackEnvelope<T>;if(!body||typeof body.status!=='boolean')throw new BadGatewayException('Payment provider returned a malformed response');return body;}catch(error){if(error instanceof BadGatewayException)throw error;throw new ServiceUnavailableException('Payment provider is temporarily unavailable');}}
}
