import { ConflictException } from '@nestjs/common';
import { Provider } from '../providers/entities/provider.entity'; import { ProviderPayoutAccountHistory } from './entities/provider-payout-account-history.entity'; import { ProviderPayoutAccount } from './entities/provider-payout-account.entity'; import { ProviderPayoutAccountStatus, ProviderPayoutAccountType } from './enums/provider-payout-account.enum'; import { ProviderPayoutAccountsService } from './provider-payout-accounts.service';
describe('ProviderPayoutAccountsService', () => {
  let subject: ProviderPayoutAccountsService; let accounts: any; let accountRepo: any; let manager: any; let history: any; const provider = { id: 'provider-1', providerReference: 'SCPR-ONE', displayName: 'Prime', deletedAt: null }; const user = { id: 'user-1' } as any;
  const account = (changes: any = {}) => ({ id: 'account-1', reference: 'SC-PACCT-ONE', providerId: provider.id, provider, type: ProviderPayoutAccountType.BANK_ACCOUNT, countryCode: 'NG', currency: 'NGN', bankCode: '058', bankName: 'Example Bank', encryptedAccountNumber: 'ciphertext', encryptionIv: 'iv', encryptionAuthTag: 'tag', accountFingerprint: 'f'.repeat(64), accountNumberLast4: '6789', accountName: 'Ada Clinic', status: ProviderPayoutAccountStatus.PENDING_VERIFICATION, isDefault: false, verifiedAt: null, disabledAt: null, createdAt: new Date(), updatedAt: new Date(), history: [], ...changes });
  beforeEach(() => { accountRepo = { create: jest.fn(value => value), save: jest.fn(async value => Object.assign(value, { id: value.id ?? 'account-1', reference: value.reference ?? 'SC-PACCT-ONE' })), findOne: jest.fn(), createQueryBuilder: jest.fn() }; history = { create: jest.fn(value => value), save: jest.fn(async value => value) }; manager = { getRepository: jest.fn(entity => entity === ProviderPayoutAccount ? accountRepo : history) }; accounts = { manager: { transaction: jest.fn((cb: any) => cb(manager)) }, createQueryBuilder: jest.fn() }; const providers = { findOne: jest.fn().mockResolvedValue(provider) }; const crypto = { protect: jest.fn().mockReturnValue({ encryptedAccountNumber: 'ciphertext', encryptionIv: 'iv', encryptionAuthTag: 'tag', accountFingerprint: 'f'.repeat(64), accountNumberLast4: '6789' }) }; subject = new ProviderPayoutAccountsService(accounts, providers as any, crypto as any); (subject as any).detail = jest.fn(async (reference: string) => ({ reference })); });
  it('creates a pending encrypted account without returning or persisting plaintext', async () => { await subject.create(user, { type: ProviderPayoutAccountType.BANK_ACCOUNT, countryCode: 'NG', currency: 'NGN', bankCode: '058', bankName: 'Bank', accountNumber: '0123456789', accountName: 'Clinic' }); expect(accountRepo.create).toHaveBeenCalledWith(expect.objectContaining({ status: ProviderPayoutAccountStatus.PENDING_VERIFICATION, encryptedAccountNumber: 'ciphertext', accountNumberLast4: '6789', isDefault: false })); expect(accountRepo.create.mock.calls[0][0]).not.toHaveProperty('accountNumber'); expect(history.save).toHaveBeenCalledWith(expect.objectContaining({ eventType: 'ACCOUNT_CREATED' })); });
  it('masks account number for Provider and Admin projections', () => { const row = account(); const providerView = (subject as any).view(row, false); const adminView = (subject as any).view(row, true); for (const view of [providerView, adminView]) { expect(view.maskedAccountNumber).toBe('****6789'); expect(JSON.stringify(view)).not.toContain('0123456789'); expect(view).not.toHaveProperty('encryptedAccountNumber'); expect(view).not.toHaveProperty('accountFingerprint'); } });
  it('permits pending correction but makes verified identity immutable', async () => { accountRepo.findOne.mockResolvedValue(account()); await subject.update(user, 'SC-PACCT-ONE', { bankName: 'New Bank' }); expect(accountRepo.save).toHaveBeenCalledWith(expect.objectContaining({ bankName: 'New Bank' })); accountRepo.findOne.mockResolvedValue(account({ status: ProviderPayoutAccountStatus.VERIFIED })); await expect(subject.update(user, 'SC-PACCT-ONE', { bankName: 'Other' })).rejects.toBeInstanceOf(ConflictException); });
  it('requires Admin verification and records the transition', async () => { const row = account(); accountRepo.findOne.mockResolvedValue(row); jest.spyOn(subject, 'adminDetail').mockResolvedValue({ reference: row.reference } as any); await subject.verify(row.reference, 'admin-1', 'Reviewed'); expect(row.status).toBe(ProviderPayoutAccountStatus.VERIFIED); expect(row.verifiedAt).toBeInstanceOf(Date); expect(history.save).toHaveBeenCalledWith(expect.objectContaining({ eventType: 'ACCOUNT_VERIFIED', actorUserId: 'admin-1' })); });
  it('sets only a verified account as default and clears the prior default transactionally', async () => { const target = account({ status: ProviderPayoutAccountStatus.VERIFIED }); const previous = account({ id: 'account-2', reference: 'SC-PACCT-TWO', status: ProviderPayoutAccountStatus.VERIFIED, isDefault: true }); accountRepo.findOne.mockResolvedValue(target); const qb: any = { where: jest.fn().mockReturnThis(), andWhere: jest.fn().mockReturnThis(), setLock: jest.fn().mockReturnThis(), getMany: jest.fn().mockResolvedValue([target, previous]) }; accountRepo.createQueryBuilder.mockReturnValue(qb); jest.spyOn(subject, 'detailMine').mockResolvedValue({ reference: target.reference } as any); await subject.setDefault(user, target.reference); expect(qb.setLock).toHaveBeenCalledWith('pessimistic_write'); expect(target.isDefault).toBe(true); expect(previous.isDefault).toBe(false); expect(history.save).toHaveBeenCalledWith(expect.objectContaining({ eventType: 'ACCOUNT_SET_DEFAULT' })); });
  it('disables without deleting history and clears default', async () => { const row = account({ status: ProviderPayoutAccountStatus.VERIFIED, isDefault: true }); accountRepo.findOne.mockResolvedValue(row); await subject.disableMine(user, row.reference, 'Changed account'); expect(row).toMatchObject({ status: ProviderPayoutAccountStatus.DISABLED, isDefault: false }); expect(history.save).toHaveBeenCalledWith(expect.objectContaining({ eventType: 'ACCOUNT_DISABLED' })); });
});
