import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { EntityManager, QueryFailedError, Repository } from 'typeorm';
import { Provider } from '../providers/entities/provider.entity';
import { User } from '../users/entities/user.entity';
import { AdminProviderPayoutAccountListQueryDto, CreateProviderPayoutAccountDto, ProviderPayoutAccountListQueryDto, UpdateProviderPayoutAccountDto } from './dto/provider-payout-account.dto';
import { ProviderPayoutAccountHistory } from './entities/provider-payout-account-history.entity';
import { ProviderPayoutAccount } from './entities/provider-payout-account.entity';
import { ProviderPayoutAccountStatus } from './enums/provider-payout-account.enum';
import { ProviderPayoutAccountCryptoService } from './provider-payout-account-crypto.service';

@Injectable()
export class ProviderPayoutAccountsService {
  constructor(@InjectRepository(ProviderPayoutAccount) private readonly accounts: Repository<ProviderPayoutAccount>, @InjectRepository(Provider) private readonly providers: Repository<Provider>, private readonly crypto: ProviderPayoutAccountCryptoService) {}
  async create(user: User, input: CreateProviderPayoutAccountDto) { const provider = await this.resolveProvider(user); const protectedNumber = this.crypto.protect(input.accountNumber); return this.persist(async manager => { const repository = manager.getRepository(ProviderPayoutAccount); const account = await repository.save(repository.create({ providerId: provider.id, type: input.type, countryCode: input.countryCode, currency: input.currency, bankCode: input.bankCode, bankName: input.bankName.trim(), ...protectedNumber, accountName: input.accountName.trim(), status: ProviderPayoutAccountStatus.PENDING_VERIFICATION, isDefault: false, verifiedAt: null, disabledAt: null })); await this.history(manager, account, 'ACCOUNT_CREATED', null, account.status, user.id, null); return account.reference; }); }
  async update(user: User, reference: string, input: UpdateProviderPayoutAccountDto) { const provider = await this.resolveProvider(user); return this.persist(async manager => { const account = await this.lock(manager, reference, provider.id); if (account.status !== ProviderPayoutAccountStatus.PENDING_VERIFICATION) throw new ConflictException('Only a pending payout account can be corrected'); if (input.type !== undefined) account.type = input.type; if (input.countryCode !== undefined) account.countryCode = input.countryCode; if (input.currency !== undefined) account.currency = input.currency; if (input.bankCode !== undefined) account.bankCode = input.bankCode; if (input.bankName !== undefined) account.bankName = input.bankName.trim(); if (input.accountName !== undefined) account.accountName = input.accountName.trim(); if (input.accountNumber !== undefined) Object.assign(account, this.crypto.protect(input.accountNumber)); await manager.getRepository(ProviderPayoutAccount).save(account); await this.history(manager, account, 'ACCOUNT_CORRECTED', account.status, account.status, user.id, null); return account.reference; }); }
  async setDefault(user: User, reference: string) { const provider = await this.resolveProvider(user); const result = await this.accounts.manager.transaction(async manager => { const account = await this.lock(manager, reference, provider.id); if (account.status !== ProviderPayoutAccountStatus.VERIFIED) throw new ConflictException('Only a verified payout account can be default'); if (account.isDefault) return account.reference; const rows = await manager.getRepository(ProviderPayoutAccount).createQueryBuilder('account').where('account.providerId = :providerId', { providerId: provider.id }).andWhere('account.currency = :currency', { currency: account.currency }).setLock('pessimistic_write').getMany(); for (const row of rows) if (row.isDefault) { row.isDefault = false; await manager.getRepository(ProviderPayoutAccount).save(row); await this.history(manager, row, 'ACCOUNT_DEFAULT_CLEARED', row.status, row.status, user.id, null); } account.isDefault = true; await manager.getRepository(ProviderPayoutAccount).save(account); await this.history(manager, account, 'ACCOUNT_SET_DEFAULT', account.status, account.status, user.id, null); return account.reference; }); return this.detailMine(user, result); }
  async disableMine(user: User, reference: string, reason?: string) { const provider = await this.resolveProvider(user); return this.disable(reference, user.id, reason, provider.id, false); }
  async verify(reference: string, actorUserId: string, note?: string) { const result = await this.accounts.manager.transaction(async manager => { const account = await this.lock(manager, reference); if (account.status === ProviderPayoutAccountStatus.VERIFIED) return account.reference; if (account.status !== ProviderPayoutAccountStatus.PENDING_VERIFICATION) throw new ConflictException('Payout account cannot be verified from its current status'); const from = account.status; account.status = ProviderPayoutAccountStatus.VERIFIED; account.verifiedAt = new Date(); await manager.getRepository(ProviderPayoutAccount).save(account); await this.history(manager, account, 'ACCOUNT_VERIFIED', from, account.status, actorUserId, note?.trim() || null); return account.reference; }); return this.adminDetail(result); }
  disableAdmin(reference: string, actorUserId: string, reason?: string) { return this.disable(reference, actorUserId, reason, undefined, true); }
  async listMine(user: User, query: ProviderPayoutAccountListQueryDto) { const provider = await this.resolveProvider(user); return this.list(query, provider.id, false); }
  async detailMine(user: User, reference: string) { const provider = await this.resolveProvider(user); return this.detail(reference, provider.id, false); }
  adminList(query: AdminProviderPayoutAccountListQueryDto) { return this.list(query, undefined, true); }
  adminDetail(reference: string) { return this.detail(reference, undefined, true); }
  private async disable(reference: string, actorUserId: string, reason: string | undefined, providerId: string | undefined, admin: boolean) { const result = await this.accounts.manager.transaction(async manager => { const account = await this.lock(manager, reference, providerId); if (account.status === ProviderPayoutAccountStatus.DISABLED) return account.reference; const from = account.status; account.status = ProviderPayoutAccountStatus.DISABLED; account.disabledAt = new Date(); account.isDefault = false; await manager.getRepository(ProviderPayoutAccount).save(account); await this.history(manager, account, 'ACCOUNT_DISABLED', from, account.status, actorUserId, reason?.trim() || null); return account.reference; }); return admin ? this.adminDetail(result) : this.detailByProviderReference(result, providerId!); }
  private async list(query: ProviderPayoutAccountListQueryDto | AdminProviderPayoutAccountListQueryDto, providerId?: string, admin = false) { const qb = this.accounts.createQueryBuilder('account'); if (admin) qb.innerJoinAndSelect('account.provider', 'provider'); if (providerId) qb.andWhere('account.providerId = :providerId', { providerId }); const adminQuery = query as AdminProviderPayoutAccountListQueryDto; if (adminQuery.providerReference) qb.andWhere('provider.providerReference = :providerReference', { providerReference: adminQuery.providerReference }); if (query.status) qb.andWhere('account.status = :status', { status: query.status }); if (query.currency) qb.andWhere('account.currency = :currency', { currency: query.currency }); if (query.countryCode) qb.andWhere('account.countryCode = :countryCode', { countryCode: query.countryCode }); qb.orderBy('account.createdAt', 'DESC').addOrderBy('account.id', 'DESC').skip((query.page - 1) * query.limit).take(query.limit); const [rows, total] = await qb.getManyAndCount(); return { items: rows.map(row => this.view(row, admin)), page: query.page, limit: query.limit, total, totalPages: total ? Math.ceil(total / query.limit) : 0 }; }
  private async detail(reference: string, providerId?: string, admin = false) { const qb = this.accounts.createQueryBuilder('account').innerJoinAndSelect('account.provider', 'provider').leftJoinAndSelect('account.history', 'history').where('account.reference = :reference', { reference: reference.toUpperCase() }); if (providerId) qb.andWhere('account.providerId = :providerId', { providerId }); const account = await qb.getOne(); if (!account) throw new NotFoundException('Provider payout account not found'); account.history.sort((a, b) => a.createdAt.getTime() - b.createdAt.getTime()); return { ...this.view(account, admin), history: account.history.map(row => ({ eventType: row.eventType, fromStatus: row.fromStatus, toStatus: row.toStatus, reasonNote: row.reasonNote, createdAt: row.createdAt })) }; }
  private detailByProviderReference(reference: string, providerId: string) { return this.detail(reference, providerId, false); }
  private view(account: ProviderPayoutAccount, admin: boolean) { return { reference: account.reference, ...(admin ? { provider: { reference: account.provider.providerReference, displayName: account.provider.displayName } } : {}), type: account.type, countryCode: account.countryCode, currency: account.currency, bankCode: account.bankCode, bankName: account.bankName, maskedAccountNumber: `****${account.accountNumberLast4}`, accountName: account.accountName, status: account.status, isDefault: account.isDefault, verifiedAt: account.verifiedAt, disabledAt: account.disabledAt, createdAt: account.createdAt, updatedAt: account.updatedAt }; }
  private async lock(manager: EntityManager, reference: string, providerId?: string) { const account = await manager.getRepository(ProviderPayoutAccount).findOne({ where: { reference: reference.toUpperCase(), ...(providerId ? { providerId } : {}) }, lock: { mode: 'pessimistic_write' } }); if (!account) throw new NotFoundException('Provider payout account not found'); return account; }
  private async resolveProvider(user: User) { const provider = await this.providers.findOne({ where: { userId: user.id }, withDeleted: true }); if (!provider || provider.deletedAt) throw new NotFoundException('Provider payout accounts were not found'); return provider; }
  private async history(manager: EntityManager, account: ProviderPayoutAccount, eventType: string, fromStatus: ProviderPayoutAccountStatus | null, toStatus: ProviderPayoutAccountStatus, actorUserId: string, reasonNote: string | null) { const repository = manager.getRepository(ProviderPayoutAccountHistory); await repository.save(repository.create({ accountId: account.id, eventType, fromStatus, toStatus, actorUserId, reasonNote })); }
  private async persist(operation: (manager: EntityManager) => Promise<string>) { try { const reference = await this.accounts.manager.transaction(operation); return this.detail(reference, undefined, false); } catch (error) { if (error instanceof QueryFailedError && (error as any).driverError?.code === '23505') throw new ConflictException('An active payout account with these bank details already exists'); throw error; } }
}
