export enum PharmacyQuoteStatus { DRAFT='DRAFT',SUBMITTED='SUBMITTED',ACCEPTED_BY_PATIENT='ACCEPTED_BY_PATIENT',EXPIRED='EXPIRED',CANCELLED='CANCELLED' }
export enum PharmacyQuoteItemAvailability { AVAILABLE='AVAILABLE',UNAVAILABLE='UNAVAILABLE' }
export enum PharmacyFundingStatus { PENDING='PENDING',PAID='PAID',SATISFIED_FREE='SATISFIED_FREE',CANCELLED='CANCELLED',REQUIRES_REFUND_REVIEW='REQUIRES_REFUND_REVIEW' }
export enum PharmacyDispensingStatus { READY_TO_DISPENSE='READY_TO_DISPENSE',DISPENSING='DISPENSING',READY_FOR_PICKUP='READY_FOR_PICKUP',COMPLETED='COMPLETED',CANCELLED='CANCELLED',REQUIRES_REFUND_REVIEW='REQUIRES_REFUND_REVIEW' }
export enum PharmacyFulfillmentMethod { PICKUP='PICKUP' }
