import { BookingStatus } from '../bookings/enums/booking-status.enum';
import { PatientStatus } from '../patients/enums/patient-status.enum';
import { ProviderAssignmentStatus } from '../providers/enums/provider-assignment-status.enum';
import { HealthCheckEncounterStatus } from './enums/health-check-encounter-status.enum';
import { PatientHealthCheckHistoryService } from './patient-health-check-history.service';

describe('PatientHealthCheckHistoryService', () => {
  const user: any = { id: 'user-a' }; let patient: any, bookingRows: any[], encounterRows: any[], assignmentRows: any[], builder: any, bookings: any, patients: any, encounters: any, assignments: any, subject: PatientHealthCheckHistoryService;
  const booking = (id: string, reference: string, status = BookingStatus.COMPLETED, createdAt = new Date()) => ({ id, bookingReference: reference, participantPatientId: 'patient-a', status, createdAt, updatedAt: createdAt, healthCheckPackage: { code: 'ESSENTIAL', name: 'Essential' }, fulfilmentMode: { code: 'HOME_VISIT', name: 'Home Visit' }, preferredDate: '2026-08-18', preferredTimeWindowStart: '10:00:00', preferredTimeWindowEnd: '10:30:00', preferredTimezone: 'Africa/Lagos' });
  beforeEach(() => {
    patient = { id: 'patient-a', userId: user.id, status: PatientStatus.ACTIVE, deletedAt: null };
    bookingRows = [booking('booking-new', 'SC-2026-FFFFFFFFFFFF', BookingStatus.COMPLETED, new Date('2026-08-19')), booking('booking-old', 'SC-2026-AAAAAAAAAAAA', BookingStatus.CANCELLED, new Date('2026-08-18'))]; encounterRows = []; assignmentRows = [];
    builder = { innerJoinAndSelect: jest.fn().mockReturnThis(), where: jest.fn().mockReturnThis(), andWhere: jest.fn().mockReturnThis(), orderBy: jest.fn().mockReturnThis(), addOrderBy: jest.fn().mockReturnThis(), skip: jest.fn().mockReturnThis(), take: jest.fn().mockReturnThis(), getManyAndCount: jest.fn(async () => [bookingRows, bookingRows.length]) };
    bookings = { createQueryBuilder: jest.fn(() => builder) }; patients = { findOne: jest.fn(async () => patient) }; encounters = { find: jest.fn(async () => encounterRows) }; assignments = { find: jest.fn(async () => assignmentRows) };
    subject = new PatientHealthCheckHistoryService(bookings, patients, encounters, assignments);
  });

  it('scopes the query to the linked Patient and returns newest-first deterministic ordering', async () => { const result = await subject.list(user, { page: 1, limit: 20 }); expect(builder.where).toHaveBeenCalledWith('booking.participantPatientId = :patientId', { patientId: 'patient-a' }); expect(builder.orderBy).toHaveBeenCalledWith('booking.createdAt', 'DESC'); expect(builder.addOrderBy).toHaveBeenCalledWith('booking.bookingReference', 'DESC'); expect(result.items.map((item) => item.bookingReference)).toEqual(['SC-2026-FFFFFFFFFFFF', 'SC-2026-AAAAAAAAAAAA']); });
  it('returns a safe empty page for a User without an active linked Patient', async () => { patients.findOne.mockResolvedValue(null); await expect(subject.list(user, { page: 2, limit: 10 })).resolves.toEqual({ items: [], page: 2, limit: 10, total: 0, totalPages: 0 }); expect(bookings.createQueryBuilder).not.toHaveBeenCalled(); });
  it('applies bounded pagination metadata and database offsets', async () => { bookingRows = [booking('booking-1', 'SC-2026-BBBBBBBBBBBB')]; builder.getManyAndCount.mockResolvedValue([bookingRows, 41]); const result = await subject.list(user, { page: 2, limit: 20 }); expect(builder.skip).toHaveBeenCalledWith(20); expect(builder.take).toHaveBeenCalledWith(20); expect(result).toMatchObject({ page: 2, limit: 20, total: 41, totalPages: 3 }); });
  it('applies booking and encounter status filters without accepting patient identity input', async () => { await subject.list(user, { page: 1, limit: 20, bookingStatus: BookingStatus.EXPIRED, encounterStatus: HealthCheckEncounterStatus.IN_PROGRESS }); expect(builder.andWhere).toHaveBeenCalledWith('booking.status = :bookingStatus', { bookingStatus: BookingStatus.EXPIRED }); expect(builder.andWhere).toHaveBeenCalledWith(expect.stringContaining('health_check_encounters'), { encounterStatus: HealthCheckEncounterStatus.IN_PROGRESS }); });
  it('maps no encounter and incomplete encounter with result availability false', async () => { let result = await subject.list(user, { page: 1, limit: 20 }); expect(result.items[0]).toMatchObject({ encounterStatus: null, startedAt: null, completedAt: null, hasCompletedResult: false }); encounterRows = [{ bookingId: 'booking-new', status: HealthCheckEncounterStatus.IN_PROGRESS, startedAt: new Date(), completedAt: null }]; result = await subject.list(user, { page: 1, limit: 20 }); expect(result.items[0]).toMatchObject({ encounterStatus: HealthCheckEncounterStatus.IN_PROGRESS, hasCompletedResult: false }); });
  it('marks results available only from a completed encounter, not booking status alone', async () => { encounterRows = [{ bookingId: 'booking-new', status: HealthCheckEncounterStatus.COMPLETED, startedAt: new Date(), completedAt: new Date() }]; const result = await subject.list(user, { page: 1, limit: 20 }); expect(result.items[0]).toMatchObject({ bookingStatus: BookingStatus.COMPLETED, encounterStatus: HealthCheckEncounterStatus.COMPLETED, hasCompletedResult: true, completedAt: expect.any(Date) }); expect(result.items[1].hasCompletedResult).toBe(false); });
  it('maps only the confirmed provider display name and otherwise returns null', async () => { assignmentRows = [{ bookingId: 'booking-new', status: ProviderAssignmentStatus.CONFIRMED, provider: { id: 'provider-secret', displayName: 'SmartClinic Ikeja' }, id: 'assignment-secret' }]; const result: any = await subject.list(user, { page: 1, limit: 20 }); expect(result.items[0].providerDisplayName).toBe('SmartClinic Ikeja'); expect(result.items[1].providerDisplayName).toBeNull(); expect(JSON.stringify(result)).not.toContain('provider-secret'); expect(JSON.stringify(result)).not.toContain('assignment-secret'); });
  it('represents cancelled and expired bookings without leaking sensitive domains', async () => { bookingRows = [booking('cancelled', 'SC-2026-CCCCCCCCCCCC', BookingStatus.CANCELLED), booking('expired', 'SC-2026-EEEEEEEEEEEE', BookingStatus.EXPIRED)]; const result: any = await subject.list(user, { page: 1, limit: 20 }); expect(result.items.map((item: any) => item.bookingStatus)).toEqual([BookingStatus.CANCELLED, BookingStatus.EXPIRED]); for (const item of result.items) for (const field of ['id', 'participantPatientId', 'funding', 'payment', 'contact', 'providerId', 'assignmentId', 'history', 'resultAccessToken']) expect(item).not.toHaveProperty(field); });
});
