export enum PaymentAttemptStatus {
  CREATED = 'CREATED',
  AWAITING_CUSTOMER_ACTION = 'AWAITING_CUSTOMER_ACTION',
  PENDING_CONFIRMATION = 'PENDING_CONFIRMATION',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}
