export enum ClinicalRecordType {
  CONSULTATION = 'CONSULTATION',
  LAB_RESULT = 'LAB_RESULT',
  IMAGING_RESULT = 'IMAGING_RESULT',
  PROCEDURE = 'PROCEDURE',
  PHARMACY = 'PHARMACY',
  FOLLOW_UP = 'FOLLOW_UP',
  OTHER = 'OTHER',
}
