import { GuidedSelfCheckContactWorkItemsService } from './guided-self-check-contact-work-items.service';
import { GuidedSelfCheckClassification } from './enums/guided-self-check-classification.enum';
import { GuidedSelfCheckContactWorkItemOutcome, GuidedSelfCheckContactWorkItemStatus } from './enums/guided-self-check-contact-work-item.enum';
import { GuidedSelfCheckNextActionType } from './enums/guided-self-check-next-action.enum';

describe('Guided Self-Check professional contact work items',()=>{
 function harness(){let current:any=null;const items={findOne:jest.fn(async(options:any)=>options?.where?.nextActionId?current?.nextActionId===options.where.nextActionId?current:null:current),create:jest.fn((x:any)=>x),save:jest.fn(async(x:any)=>current={id:x.id??'contact',reference:x.reference??'SC-GCW-ABCDEF123456',selfCheck:x.selfCheck??{reference:'SC-GSC-X'},createdAt:x.createdAt??new Date(),...x})};const classification={findOne:jest.fn().mockResolvedValue({classification:GuidedSelfCheckClassification.AMBER})};const history={save:jest.fn()};const manager:any={getRepository:jest.fn((e:any)=>e.name==='GuidedSelfCheckContactWorkItem'?items:e.name==='GuidedSelfCheckClassificationResult'?classification:history),save:items.save};const data:any={transaction:jest.fn((fn:any)=>fn(manager))};return{service:new GuidedSelfCheckContactWorkItemsService(items as never,data),items,classification,history,manager,get current(){return current;}};}
 const action=(type=GuidedSelfCheckNextActionType.REQUEST_PROFESSIONAL_CONTACT)=>({id:type===GuidedSelfCheckNextActionType.REQUEST_PROFESSIONAL_CONTACT?'action':'replacement-action',guidedSelfCheckId:'check',classificationId:'classification',professionalReviewId:null,type,source:'AI_ANALYSIS'}as any);
 it('creates exactly one current internal work item for the authoritative contact action',async()=>{const h=harness();await h.service.reconcileCurrent(h.manager,action());await h.service.reconcileCurrent(h.manager,action());expect(h.items.save).toHaveBeenCalledTimes(1);expect(h.current).toMatchObject({status:'PENDING',priority:'ROUTINE',nextActionId:'action',professionalReviewId:null});expect(h.history.save).toHaveBeenCalledWith(expect.objectContaining({event:'PROFESSIONAL_CONTACT_CREATED'}));});
 it('cancels current contact work when the authoritative action is replaced',async()=>{const h=harness();await h.service.reconcileCurrent(h.manager,action());await h.service.reconcileCurrent(h.manager,action(GuidedSelfCheckNextActionType.FIND_CARE));expect(h.current.status).toBe(GuidedSelfCheckContactWorkItemStatus.CANCELLED);expect(h.history.save).toHaveBeenCalledWith(expect.objectContaining({event:'PROFESSIONAL_CONTACT_CANCELLED'}));});
 it('supports auditable operational contact lifecycle without clinical or care side effects',async()=>{const h=harness();await h.service.reconcileCurrent(h.manager,action());await h.service.acknowledge(h.current.reference,'operations');await h.service.start(h.current.reference,'operations');await h.service.complete(h.current.reference,'operations',GuidedSelfCheckContactWorkItemOutcome.CONTACTED,'Contact confirmed.');expect(h.current).toMatchObject({status:'COMPLETED',outcome:'CONTACTED',completedByUserId:'operations'});expect(JSON.stringify(h.current)).not.toMatch(/diagnosis|prescription|providerId|appointmentId|careRequestId|payment/i);});
});
