import { ConflictException,ForbiddenException } from '@nestjs/common';import { GuidedSelfCheckProfessionalReviewsService } from './guided-self-check-professional-reviews.service';import { GuidedSelfCheckClassification } from './enums/guided-self-check-classification.enum';import { GuidedSelfCheckReviewDecision,GuidedSelfCheckReviewPriority,GuidedSelfCheckReviewStatus } from './enums/guided-self-check-review.enum';import { GuidedSelfCheckReviewerAuthorizationStatus } from './enums/guided-self-check-reviewer-authorization.enum';import { ProviderStatus } from '../providers/enums/provider-status.enum';import { ProviderOnboardingStatus } from '../providers/enums/provider-onboarding-status.enum';
describe('GuidedSelfCheckProfessionalReviewsService',()=>{
 const classification=(value=GuidedSelfCheckClassification.AMBER,required=true)=>({id:'c',guidedSelfCheckId:'s',classification:value,requiresProfessionalReview:required} as any);
 const creation=()=>{const rows:any[]=[];const history:any[]=[];const repo={findOne:jest.fn(async()=>rows[0]??null),create:jest.fn((x:any)=>x),save:jest.fn(async(x:any)=>{const v={...x,id:'r'};rows[0]=v;return v;})};const m:any={getRepository:jest.fn((e:any)=>e.name==='GuidedSelfCheckProfessionalReview'?repo:{save:jest.fn(async(x:any)=>history.push(x))})};return{rows,history,repo,m};};
 it('creates one ROUTINE AMBER review and an URGENT RED review',async()=>{const h=creation();const s=new GuidedSelfCheckProfessionalReviewsService(h.repo as never,{} as never);await s.ensureForClassification(h.m,classification());expect(h.rows[0].priority).toBe(GuidedSelfCheckReviewPriority.ROUTINE);const h2=creation();await new GuidedSelfCheckProfessionalReviewsService(h2.repo as never,{} as never).ensureForClassification(h2.m,classification(GuidedSelfCheckClassification.RED));expect(h2.rows[0].priority).toBe(GuidedSelfCheckReviewPriority.URGENT);});
 it('does not queue GREEN and remains idempotent',async()=>{const h=creation();const s=new GuidedSelfCheckProfessionalReviewsService(h.repo as never,{} as never);await s.ensureForClassification(h.m,classification(GuidedSelfCheckClassification.GREEN,false));expect(h.rows).toHaveLength(0);await s.ensureForClassification(h.m,classification());await s.ensureForClassification(h.m,classification());expect(h.rows).toHaveLength(1);});
 it('active approved Provider affiliation alone is insufficient',async()=>{const authorizationRepo={findOne:jest.fn().mockResolvedValue(null)};const data:any={manager:{getRepository:jest.fn(()=>authorizationRepo)}};const s=new GuidedSelfCheckProfessionalReviewsService({} as never,data);await expect(s.start('SC-GSR-X',{id:'u'} as any)).rejects.toBeInstanceOf(ForbiddenException);});
 it('disabled authorization is insufficient even with operational affiliation',async()=>{const a={status:GuidedSelfCheckReviewerAuthorizationStatus.DISABLED,userId:'u',providerId:'p',provider:{userId:'u',status:ProviderStatus.ACTIVE,onboardingStatus:ProviderOnboardingStatus.APPROVED,deletedAt:null}};const data:any={manager:{getRepository:jest.fn(()=>({findOne:jest.fn().mockResolvedValue(a)}))}};await expect(new GuidedSelfCheckProfessionalReviewsService({} as never,data).start('x',{id:'u'} as any)).rejects.toBeInstanceOf(ForbiddenException);});
 it('authorized exact assignee reaches state validation',async()=>{const a={id:'a',reference:'SC-GCR-X',status:GuidedSelfCheckReviewerAuthorizationStatus.AUTHORIZED,userId:'u',providerId:'p',provider:{providerReference:'SCPR-X',userId:'u',status:ProviderStatus.ACTIVE,onboardingStatus:ProviderOnboardingStatus.APPROVED,deletedAt:null},user:{id:'u'}};const review={id:'r',reference:'SC-GSR-X',status:GuidedSelfCheckReviewStatus.ASSIGNED,assignedReviewerUserId:'u',assignedReviewerProviderId:'p',assignedReviewerAuthorizationId:'a',selfCheck:{reference:'SC-GSC-X'},classificationResult:{},assignedReviewerAuthorization:a};const reviewRepo={findOne:jest.fn().mockResolvedValue(review)};const authRepo={findOne:jest.fn().mockResolvedValue(a)};const data:any={manager:{getRepository:jest.fn(()=>authRepo)},transaction:jest.fn((fn:any)=>fn({getRepository:jest.fn((e:any)=>e.name==='GuidedSelfCheckProfessionalReview'?reviewRepo:authRepo)}))};await expect(new GuidedSelfCheckProfessionalReviewsService(reviewRepo as never,data).complete('x',{id:'u'} as any,{decision:GuidedSelfCheckReviewDecision.NO_FURTHER_REVIEW_REQUIRED})).rejects.toBeInstanceOf(ConflictException);});
 it('decision model contains no diagnosis or prescribing outcome',()=>{expect(Object.values(GuidedSelfCheckReviewDecision)).not.toContain('DIAGNOSIS');});
});
