import { ForbiddenException } from '@nestjs/common';
import { GuidedSelfCheckClinicalGovernanceService } from './guided-self-check-clinical-governance.service';
import { GuidedSelfCheckClinicalRuleset } from './entities/guided-self-check-clinical-ruleset.entity';
import { GuidedSelfCheckQuestionnaireVersion } from './entities/guided-self-check-questionnaire-version.entity';
import { GuidedSelfCheckQuestion } from './entities/guided-self-check-question.entity';
import { GuidedSelfCheckClinicalGovernanceAuthorization } from './entities/guided-self-check-clinical-governance-authorization.entity';
import { GuidedSelfCheckAnswerState, GuidedSelfCheckQuestionType } from './enums/guided-self-check-questionnaire.enum';
import { GuidedSelfCheckClassification, GuidedSelfCheckPatientMessageKey, GuidedSelfCheckRulesetGovernanceStatus } from './enums/guided-self-check-classification.enum';

describe('Guided Self-Check clinical governance API readiness',()=>{
 const questionnaire:any={id:'questionnaire-id',version:1,schemaVersion:1,isActive:true,createdAt:new Date(),groups:[{key:'history',title:'Health history',helperText:null,sortOrder:1,questions:[{key:'condition',text:'Have you been told about a condition?',helperText:null,type:GuidedSelfCheckQuestionType.SINGLE_CHOICE,required:true,allowsDontKnow:true,options:['YES','NO'],measurementMetadata:null,validationMetadata:null,sortOrder:1},{key:'bp',text:'Blood pressure',helperText:null,type:GuidedSelfCheckQuestionType.BLOOD_PRESSURE,required:false,allowsDontKnow:true,options:null,measurementMetadata:{unit:'mmHg'},validationMetadata:null,sortOrder:2}]}]};
 const ruleset=(status=GuidedSelfCheckRulesetGovernanceStatus.DRAFT):any=>({id:'internal-id',reference:'SC-GCRS-ABCDEF123456',version:2,name:'Governed test fixture',description:'Non-production test fixture',questionnaireVersionId:questionnaire.id,questionnaireVersion:questionnaire,isActive:false,governanceStatus:status,rules:[],patientMessageKeys:{green:GuidedSelfCheckPatientMessageKey.GREEN_COMPLETE,amber:GuidedSelfCheckPatientMessageKey.AMBER_REVIEW,red:GuidedSelfCheckPatientMessageKey.RED_URGENT},contentHash:'hash',approvedContentHash:null,approvedAt:null,activatedAt:null,retiredAt:null,createdAt:new Date(),updatedAt:new Date()});
 function service(manager:any={},classifier:any={evaluateRulesForGovernance:jest.fn().mockReturnValue([])}){const subject=new GuidedSelfCheckClinicalGovernanceService({}as never,{manager}as never,classifier as never)as any;subject.requireEligible=jest.fn();return subject;}

 it('exposes authoritative DSL, messages, limits and questionnaire summaries without patient data',async()=>{const repo={find:jest.fn().mockResolvedValue([questionnaire])};const subject=service({getRepository:jest.fn(()=>repo)});const result=await subject.metadata('governor');expect(result.operators).toEqual(expect.arrayContaining(['STATE_EQUALS','BETWEEN','AND','OR']));expect(result.patientMessages).toEqual(expect.arrayContaining([expect.objectContaining({key:'SELF_CHECK_RED_URGENT'})]));expect(result.validationLimits).toMatchObject({maxRules:200,maxConditionDepth:8,maxGroupBranches:20,maxSimulationAnswers:300});expect(result.measurementTargets.BLOOD_PRESSURE).toEqual(['systolic','diastolic']);expect(JSON.stringify(result)).not.toMatch(/patientAnswer|payment|providerReference|password/i);});

 it('projects versioned questionnaire authoring metadata with stable keys, choices, answer states and measurement targets',async()=>{const repo={findOne:jest.fn().mockResolvedValue(questionnaire)};const subject=service({getRepository:jest.fn(()=>repo)});const result=await subject.questionnaireMetadata(1,'governor');expect(result.groups[0].questions[0]).toMatchObject({key:'condition',type:'SINGLE_CHOICE',options:['YES','NO'],supportedAnswerStates:['KNOWN','DONT_KNOW']});expect(result.groups[0].questions[1]).toMatchObject({key:'bp',measurementTargets:['systolic','diastolic']});expect(JSON.stringify(result)).not.toContain('questionnaire-id');});

 it('derives lifecycle actions/readiness and never exposes internal ruleset IDs',()=>{const subject=service();const draft=subject.view(ruleset(),true);expect(draft.allowedActions).toMatchObject({edit:true,submitForReview:true,approve:false,activate:false});expect(draft.readiness.classificationReady).toBe(false);expect(draft).not.toHaveProperty('id');const ready=ruleset(GuidedSelfCheckRulesetGovernanceStatus.READY);ready.contentHash=subject.hash(1,ready.rules,ready.patientMessageKeys);ready.approvedContentHash=ready.contentHash;ready.approvedAt=new Date();const view=subject.view(ready);expect(view.allowedActions.activate).toBe(true);expect(view.readiness).toMatchObject({statusReady:true,approvalHashMatches:true,contentHashValid:true,classificationReady:false});});

 it('rejects a stale DRAFT edit using the server-owned content hash precondition',async()=>{const r=ruleset();r.contentHash='a'.repeat(64);const manager={getRepository:jest.fn(),save:jest.fn()};const subject=service();subject.data={transaction:jest.fn((fn:any)=>fn(manager))};subject.lockRuleset=jest.fn().mockResolvedValue(r);await expect(subject.update(r.reference,{expectedContentHash:'b'.repeat(64),name:'Stale edit'},'governor')).rejects.toThrow('reload before editing');expect(manager.save).not.toHaveBeenCalled();});

 it('requires both internal Admin/Operations role and exact active governance authorization',async()=>{const auth=(roles:string[],disabledAt:any=null)=>({disabledAt,status:'AUTHORIZED',user:{status:'ACTIVE',deletedAt:null,roles},provider:null});const repo={findOne:jest.fn()};const manager={getRepository:jest.fn((e:any)=>e===GuidedSelfCheckClinicalGovernanceAuthorization?repo:{})};const subject=new GuidedSelfCheckClinicalGovernanceService({}as never,{manager}as never,{}as never)as any;for(const roles of [['USER'],['PROVIDER']]){repo.findOne.mockResolvedValueOnce(auth(roles));await expect(subject.requireEligible('user')).rejects.toBeInstanceOf(ForbiddenException);}repo.findOne.mockResolvedValueOnce(auth(['ADMIN']));await expect(subject.requireEligible('admin')).resolves.toBeDefined();repo.findOne.mockResolvedValueOnce(auth(['OPERATIONS'],new Date()));await expect(subject.requireEligible('disabled')).rejects.toBeInstanceOf(ForbiddenException);});

 it('simulates deterministic governed data without persistence or patient workflow side effects',async()=>{
  const r=ruleset();const hashService=service();r.contentHash=hashService.hash(1,r.rules,r.patientMessageKeys);
  const rulesets={findOne:jest.fn().mockResolvedValue(r)};
  const questions={find:jest.fn().mockResolvedValue(questionnaire.groups[0].questions.map((q:any,i:number)=>({...q,id:`q${i}`,questionnaireVersionId:questionnaire.id})))};
  const manager={getRepository:jest.fn((e:any)=>e===GuidedSelfCheckClinicalRuleset?rulesets:e===GuidedSelfCheckQuestion?questions:e===GuidedSelfCheckQuestionnaireVersion?{}:{save:jest.fn()})};
  const classifier={evaluateRulesForGovernance:jest.fn().mockReturnValue([])};const subject=service(manager,classifier);
  const result=await subject.simulate(r.reference,{answers:[{questionKey:'condition',state:GuidedSelfCheckAnswerState.KNOWN,value:'YES'}]},'governor');
  expect(result).toMatchObject({classification:GuidedSelfCheckClassification.GREEN,matchedRules:[],patientMessageKey:GuidedSelfCheckPatientMessageKey.GREEN_COMPLETE,sideEffects:false});expect(classifier.evaluateRulesForGovernance).toHaveBeenCalled();expect(JSON.stringify(result)).not.toMatch(/classificationId|reviewReference|analysisReference|nextAction|contact/i);
 });
});
