import { ConflictException,Injectable,NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource,In,Repository } from 'typeorm';
import { GuidedSelfCheckBatchReprocessDto,GuidedSelfCheckProcessingQueueQueryDto } from './dto/guided-self-check-reprocessing.dto';
import { GuidedSelfCheckClassificationResult } from './entities/guided-self-check-classification.entity';import { GuidedSelfCheckClinicalRuleset } from './entities/guided-self-check-clinical-ruleset.entity';import { GuidedSelfCheckHistory } from './entities/guided-self-check-history.entity';import { GuidedSelfCheckQuestionnaireVersion } from './entities/guided-self-check-questionnaire-version.entity';import { GuidedSelfCheck } from './entities/guided-self-check.entity';
import { GuidedSelfCheckClassificationStatus,GuidedSelfCheckRulesetGovernanceStatus } from './enums/guided-self-check-classification.enum';import { GuidedSelfCheckClassificationFailureCode,GuidedSelfCheckReprocessingOutcome } from './enums/guided-self-check-reprocessing.enum';import { GuidedSelfCheckWorkflowStatus } from './enums/guided-self-check.enum';import { GuidedSelfCheckClassificationsService } from './guided-self-check-classifications.service';import { GuidedSelfCheckNextActionsService } from './guided-self-check-next-actions.service';
@Injectable()
export class GuidedSelfCheckClassificationReprocessingService{
 constructor(@InjectRepository(GuidedSelfCheck)private checks:Repository<GuidedSelfCheck>,private data:DataSource,private classifications:GuidedSelfCheckClassificationsService,private actions:GuidedSelfCheckNextActionsService){}
 async list(q:GuidedSelfCheckProcessingQueueQueryDto){
  const statuses=q.status?[q.status]:[GuidedSelfCheckClassificationStatus.CONFIGURATION_REQUIRED,GuidedSelfCheckClassificationStatus.FAILED,GuidedSelfCheckClassificationStatus.PENDING];
  const qb=this.checks.createQueryBuilder('check').leftJoinAndSelect('check.questionnaireVersion','questionnaire').where('check.workflowStatus = :completed',{completed:GuidedSelfCheckWorkflowStatus.COMPLETED}).andWhere('check.classificationStatus IN (:...statuses)',{statuses}).andWhere('NOT EXISTS (SELECT 1 FROM guided_self_check_classifications c WHERE c.guided_self_check_id = check.id)');
  if(q.questionnaireVersion)qb.andWhere('questionnaire.version = :version',{version:q.questionnaireVersion});
  qb.orderBy('check.completedAt','ASC','NULLS LAST').addOrderBy('check.id','ASC').skip((q.page-1)*q.limit).take(q.limit);
  const[rows,total]=await qb.getManyAndCount();const ids=[...new Set(rows.map(x=>x.questionnaireVersionId).filter(Boolean))]as string[];const usable=new Map<string,GuidedSelfCheckClinicalRuleset>();
  if(ids.length){const rulesets=await this.data.manager.getRepository(GuidedSelfCheckClinicalRuleset).find({where:{questionnaireVersionId:In(ids),isActive:true,governanceStatus:GuidedSelfCheckRulesetGovernanceStatus.READY},relations:{questionnaireVersion:true}});for(const r of rulesets)if(this.classifications.isRulesetUsable(r))usable.set(r.questionnaireVersionId,r);}
  return{items:rows.map(x=>{const r=usable.get(x.questionnaireVersionId!);return{reference:x.reference,questionnaireVersion:x.questionnaireVersion?.version??null,completedAt:x.completedAt,classificationStatus:x.classificationStatus,lastProcessingAttemptAt:x.classificationLastAttemptAt,failureCode:x.classificationFailureCode,attemptCount:x.classificationRetryCount,usableRuleset:r?{reference:r.reference,version:r.version}:null};}),total,page:q.page,limit:q.limit};
 }
 async reprocess(reference:string,actorUserId:string,expectedRulesetReference?:string){
  const initial=await this.checks.findOne({where:{reference},relations:{questionnaireVersion:true}});if(!initial)throw new NotFoundException('Guided Self-Check was not found');
  const existing=await this.result(initial.id);if(existing){await this.actions.ensureForReference(reference);return this.existingOutcome(reference,existing);}
  if(initial.workflowStatus!==GuidedSelfCheckWorkflowStatus.COMPLETED||!initial.questionnaireVersionId||![GuidedSelfCheckClassificationStatus.CONFIGURATION_REQUIRED,GuidedSelfCheckClassificationStatus.PENDING,GuidedSelfCheckClassificationStatus.FAILED].includes(initial.classificationStatus))return{reference,outcome:GuidedSelfCheckReprocessingOutcome.NOT_ELIGIBLE,classificationStatus:initial.classificationStatus};
  await this.recordStart(initial.id,actorUserId,expectedRulesetReference);
  try{
   const result=await this.classifications.classifyCompleted(reference,expectedRulesetReference);
   if(!result)return{reference,outcome:GuidedSelfCheckReprocessingOutcome.STILL_CONFIGURATION_REQUIRED,classificationStatus:GuidedSelfCheckClassificationStatus.CONFIGURATION_REQUIRED};
   await this.actions.ensureForReference(reference);await this.recordComplete(initial.id,actorUserId,result.ruleset.reference,result.ruleset.version,result.classification);
   return{reference,outcome:GuidedSelfCheckReprocessingOutcome.CLASSIFIED,classificationStatus:GuidedSelfCheckClassificationStatus.CLASSIFIED,classification:result.classification,ruleset:{reference:result.ruleset.reference,version:result.ruleset.version}};
  }catch(error){
   const persisted=await this.result(initial.id);if(persisted){await this.actions.ensureForReference(reference);return this.existingOutcome(reference,persisted);}
   const code=error instanceof ConflictException&&error.message==='RULESET_CHANGED'?GuidedSelfCheckClassificationFailureCode.RULESET_CHANGED:error instanceof ConflictException?GuidedSelfCheckClassificationFailureCode.INVALID_FROZEN_ANSWERS:GuidedSelfCheckClassificationFailureCode.CLASSIFICATION_PROCESSING_ERROR;
   await this.recordFailure(initial.id,actorUserId,code);return{reference,outcome:GuidedSelfCheckReprocessingOutcome.FAILED,classificationStatus:GuidedSelfCheckClassificationStatus.FAILED,failureCode:code};
  }
 }
 async batch(dto:GuidedSelfCheckBatchReprocessDto,actorUserId:string){
  const questionnaire=await this.data.manager.getRepository(GuidedSelfCheckQuestionnaireVersion).findOne({where:{version:dto.questionnaireVersion}});if(!questionnaire)throw new NotFoundException('Questionnaire version was not found');
  const ruleset=await this.data.manager.getRepository(GuidedSelfCheckClinicalRuleset).findOne({where:{questionnaireVersionId:questionnaire.id,isActive:true,governanceStatus:GuidedSelfCheckRulesetGovernanceStatus.READY},relations:{questionnaireVersion:true}});if(!ruleset||!this.classifications.isRulesetUsable(ruleset))throw new ConflictException('No usable governed ruleset exists for this questionnaire version');
  const rows=await this.checks.createQueryBuilder('check').where('check.questionnaireVersionId = :versionId',{versionId:questionnaire.id}).andWhere('check.workflowStatus = :completed',{completed:GuidedSelfCheckWorkflowStatus.COMPLETED}).andWhere('check.classificationStatus IN (:...statuses)',{statuses:[GuidedSelfCheckClassificationStatus.CONFIGURATION_REQUIRED,GuidedSelfCheckClassificationStatus.PENDING,GuidedSelfCheckClassificationStatus.FAILED]}).andWhere('NOT EXISTS (SELECT 1 FROM guided_self_check_classifications c WHERE c.guided_self_check_id = check.id)').orderBy('check.completedAt','ASC','NULLS LAST').addOrderBy('check.id','ASC').take(dto.limit).getMany();
  const outcomes=[];for(const row of rows){const outcome=await this.reprocess(row.reference,actorUserId,ruleset.reference);outcomes.push(outcome);if('failureCode' in outcome&&outcome.failureCode===GuidedSelfCheckClassificationFailureCode.RULESET_CHANGED)break;}
  return{questionnaireVersion:dto.questionnaireVersion,ruleset:{reference:ruleset.reference,version:ruleset.version},requestedLimit:dto.limit,processed:outcomes.length,classified:outcomes.filter(x=>x.outcome===GuidedSelfCheckReprocessingOutcome.CLASSIFIED).length,failed:outcomes.filter(x=>x.outcome===GuidedSelfCheckReprocessingOutcome.FAILED).length,results:outcomes};
 }
 private result(id:string){return this.data.manager.getRepository(GuidedSelfCheckClassificationResult).findOne({where:{guidedSelfCheckId:id},relations:{ruleset:true}});}
 private existingOutcome(reference:string,r:GuidedSelfCheckClassificationResult){return{reference,outcome:GuidedSelfCheckReprocessingOutcome.ALREADY_CLASSIFIED,classificationStatus:GuidedSelfCheckClassificationStatus.CLASSIFIED,classification:r.classification,ruleset:{reference:r.ruleset.reference,version:r.ruleset.version}};}
 private recordStart(id:string,actor:string,rulesetReference?:string){return this.data.transaction(async m=>{const repo=m.getRepository(GuidedSelfCheck);const s=await repo.findOne({where:{id},lock:{mode:'pessimistic_write'}});if(!s)return;s.classificationLastAttemptAt=new Date();s.classificationRetryCount=(s.classificationRetryCount??0)+1;s.classificationFailureCode=null;await repo.save(s);await m.getRepository(GuidedSelfCheckHistory).save({guidedSelfCheckId:id,event:'CLASSIFICATION_REPROCESS_STARTED',actorUserId:actor,metadata:{rulesetReference:rulesetReference??null,attempt:s.classificationRetryCount}});});}
 private recordComplete(id:string,actor:string,rulesetReference:string,rulesetVersion:number,classification:string){return this.data.transaction(async m=>{await m.getRepository(GuidedSelfCheck).findOne({where:{id},lock:{mode:'pessimistic_write'}});const history=m.getRepository(GuidedSelfCheckHistory);if(!await history.exists({where:{guidedSelfCheckId:id,event:'CLASSIFICATION_REPROCESS_COMPLETED'}}))await history.save({guidedSelfCheckId:id,event:'CLASSIFICATION_REPROCESS_COMPLETED',actorUserId:actor,metadata:{rulesetReference,rulesetVersion,classification}});});}
 private recordFailure(id:string,actor:string,code:GuidedSelfCheckClassificationFailureCode){return this.data.transaction(async m=>{const repo=m.getRepository(GuidedSelfCheck);const s=await repo.findOne({where:{id},lock:{mode:'pessimistic_write'}});if(!s||await m.getRepository(GuidedSelfCheckClassificationResult).exists({where:{guidedSelfCheckId:id}}))return;s.classificationStatus=GuidedSelfCheckClassificationStatus.FAILED;s.classificationFailureCode=code;s.classificationLastAttemptAt=new Date();await repo.save(s);await m.getRepository(GuidedSelfCheckHistory).save({guidedSelfCheckId:id,event:'CLASSIFICATION_REPROCESS_FAILED',actorUserId:actor,metadata:{failureCode:code}});});}
}
