import { BadRequestException } from '@nestjs/common';import { GuidedSelfCheckNextActionsService } from './guided-self-check-next-actions.service';import { GuidedSelfCheckClassification } from './enums/guided-self-check-classification.enum';import { GuidedSelfCheckNextActionSource,GuidedSelfCheckNextActionType } from './enums/guided-self-check-next-action.enum';import { GuidedSelfCheckReviewDecision } from './enums/guided-self-check-review.enum';
describe('GuidedSelfCheckNextActionsService',()=>{const service=()=>new GuidedSelfCheckNextActionsService({} as never,{} as never);
 it('maps only real classifications to deterministic V1 actions',()=>{const s=service();expect(s.classificationType(GuidedSelfCheckClassification.GREEN)).toBe(GuidedSelfCheckNextActionType.CONTINUE_STAYING_WELL);expect(s.classificationType(GuidedSelfCheckClassification.AMBER)).toBe(GuidedSelfCheckNextActionType.REQUEST_PROFESSIONAL_CONTACT);expect(s.classificationType(GuidedSelfCheckClassification.RED)).toBe(GuidedSelfCheckNextActionType.SEEK_URGENT_ASSESSMENT);});
 it('uses safe static non-diagnostic and non-guaranteed wording',()=>{const s=service();const green=s.project({type:GuidedSelfCheckNextActionType.CONTINUE_STAYING_WELL,source:GuidedSelfCheckNextActionSource.CLASSIFICATION,targetMetadata:{},selectedAt:new Date()} as any);expect(green.message).toContain('not a diagnosis');const red=s.project({type:GuidedSelfCheckNextActionType.SEEK_URGENT_ASSESSMENT,source:GuidedSelfCheckNextActionSource.CLASSIFICATION,targetMetadata:{domain:'CARE_REQUEST'},selectedAt:new Date()} as any);expect(red.message).toContain('does not guarantee');expect(red.cta).toMatchObject({type:'FIND_CARE',domain:'CARE_REQUEST'});});
 it('links Essential by authoritative catalogue code without price',()=>{const x=service().project({type:GuidedSelfCheckNextActionType.BOOK_ESSENTIAL_CHECK,source:GuidedSelfCheckNextActionSource.PROFESSIONAL_REVIEW,targetMetadata:{packageCode:'ESSENTIAL'},selectedAt:new Date()} as any);expect(x.cta).toMatchObject({packageCode:'ESSENTIAL'});expect(JSON.stringify(x)).not.toMatch(/price|8000/i);});
 it('enforces constrained decision/action combinations',()=>{const s=service();expect(s.allowed(GuidedSelfCheckReviewDecision.NO_FURTHER_REVIEW_REQUIRED)).toEqual([GuidedSelfCheckNextActionType.CONTINUE_STAYING_WELL]);expect(s.allowed(GuidedSelfCheckReviewDecision.FOLLOW_UP_RECOMMENDED)).toEqual([GuidedSelfCheckNextActionType.BOOK_ESSENTIAL_CHECK,GuidedSelfCheckNextActionType.REQUEST_PROFESSIONAL_CONTACT]);expect(s.allowed(GuidedSelfCheckReviewDecision.URGENT_ESCALATION_CONFIRMED)).toEqual([GuidedSelfCheckNextActionType.SEEK_URGENT_ASSESSMENT]);});
 it('replaces current action while retaining historical row',async()=>{const rows:any[]=[{id:'old',guidedSelfCheckId:'s',type:GuidedSelfCheckNextActionType.SEEK_URGENT_ASSESSMENT,source:GuidedSelfCheckNextActionSource.CLASSIFICATION,isCurrent:true}];const repo={findOne:jest.fn(async()=>rows.find(x=>x.isCurrent)),create:jest.fn((x:any)=>x),save:jest.fn(async(x:any)=>{if(!rows.includes(x))rows.push({...x,id:'new'});return x;})};const m:any={getRepository:jest.fn(()=>repo)};const s=service();await s.selectForReview(m,{id:'review',guidedSelfCheckId:'s',classificationId:'c',decision:GuidedSelfCheckReviewDecision.NO_FURTHER_REVIEW_REQUIRED} as any,GuidedSelfCheckNextActionType.CONTINUE_STAYING_WELL,'u');expect(rows[0].isCurrent).toBe(false);expect(rows).toHaveLength(2);});
 it('rejects invalid reviewer decision/action combination',async()=>{await expect(service().selectForReview({} as any,{decision:GuidedSelfCheckReviewDecision.URGENT_ESCALATION_CONFIRMED} as any,GuidedSelfCheckNextActionType.BOOK_ESSENTIAL_CHECK,'u')).rejects.toBeInstanceOf(BadRequestException);});
});
