import { BadRequestException,ConflictException,Injectable } from '@nestjs/common';import { InjectRepository } from '@nestjs/typeorm';import { DataSource,EntityManager,Repository } from 'typeorm';import { HealthCheckPackage } from '../health-checks/entities/health-check-package.entity';import { GuidedSelfCheckClassificationResult } from './entities/guided-self-check-classification.entity';import { GuidedSelfCheckNextAction } from './entities/guided-self-check-next-action.entity';import { GuidedSelfCheckProfessionalReview } from './entities/guided-self-check-professional-review.entity';import { GuidedSelfCheckClassification } from './enums/guided-self-check-classification.enum';import { GuidedSelfCheckNextActionSource,GuidedSelfCheckNextActionType } from './enums/guided-self-check-next-action.enum';import { GuidedSelfCheckReviewDecision } from './enums/guided-self-check-review.enum';
const P={
 [GuidedSelfCheckNextActionType.CONTINUE_STAYING_WELL]:{titleKey:'SELF_CHECK_CONTINUE_STAYING_WELL',title:'Continue staying well',message:'Keep supporting your wellbeing and seek care whenever you have concerns. This Self-Check is not a diagnosis.',cta:{type:'NONE'}},
 [GuidedSelfCheckNextActionType.BOOK_ESSENTIAL_CHECK]:{titleKey:'SELF_CHECK_BOOK_ESSENTIAL_CHECK',title:'Book an Essential Health Check',message:'An Essential Health Check is recommended as your next SmartClinic step.',cta:{type:'HEALTH_CHECK_PACKAGE',packageCode:'ESSENTIAL'}},
 [GuidedSelfCheckNextActionType.REQUEST_PROFESSIONAL_CONTACT]:{titleKey:'SELF_CHECK_REQUEST_PROFESSIONAL_CONTACT',title:'Professional review required',message:'A healthcare professional should review or clarify the information you provided.',cta:{type:'PROFESSIONAL_REVIEW'}},
 [GuidedSelfCheckNextActionType.SEEK_URGENT_ASSESSMENT]:{titleKey:'SELF_CHECK_SEEK_URGENT_ASSESSMENT',title:'Seek urgent medical assessment',message:'Please seek urgent medical assessment. SmartClinic does not guarantee immediate provider availability or emergency transport.',cta:{type:'FIND_CARE',domain:'CARE_REQUEST'}},
}as const;
@Injectable()export class GuidedSelfCheckNextActionsService{
 constructor(@InjectRepository(GuidedSelfCheckNextAction)private actions:Repository<GuidedSelfCheckNextAction>,private data:DataSource){}
 classificationType(c:GuidedSelfCheckClassification){return c===GuidedSelfCheckClassification.GREEN?GuidedSelfCheckNextActionType.CONTINUE_STAYING_WELL:c===GuidedSelfCheckClassification.AMBER?GuidedSelfCheckNextActionType.REQUEST_PROFESSIONAL_CONTACT:GuidedSelfCheckNextActionType.SEEK_URGENT_ASSESSMENT;}
 async ensureForReference(reference:string){return this.data.transaction(async m=>{const result=await m.getRepository(GuidedSelfCheckClassificationResult).createQueryBuilder('classification').innerJoin('classification.selfCheck','selfCheck').where('selfCheck.reference = :reference',{reference}).setLock('pessimistic_write').getOne();if(!result)return null;return this.ensureClassificationAction(m,result);});}
 async ensureClassificationAction(m:EntityManager,result:GuidedSelfCheckClassificationResult){const type=this.classificationType(result.classification);const repo=m.getRepository(GuidedSelfCheckNextAction);const current=await repo.findOne({where:{guidedSelfCheckId:result.guidedSelfCheckId,isCurrent:true},lock:{mode:'pessimistic_read'}});if(current)return current;return repo.save(repo.create({guidedSelfCheckId:result.guidedSelfCheckId,classificationId:result.id,professionalReviewId:null,type,source:GuidedSelfCheckNextActionSource.CLASSIFICATION,targetMetadata:this.target(type),isCurrent:true,selectedByUserId:null,selectedAt:new Date()}));}
 allowed(d:GuidedSelfCheckReviewDecision):GuidedSelfCheckNextActionType[]{switch(d){case GuidedSelfCheckReviewDecision.NO_FURTHER_REVIEW_REQUIRED:return[GuidedSelfCheckNextActionType.CONTINUE_STAYING_WELL];case GuidedSelfCheckReviewDecision.FOLLOW_UP_RECOMMENDED:return[GuidedSelfCheckNextActionType.BOOK_ESSENTIAL_CHECK,GuidedSelfCheckNextActionType.REQUEST_PROFESSIONAL_CONTACT];case GuidedSelfCheckReviewDecision.PATIENT_CONTACT_REQUIRED:return[GuidedSelfCheckNextActionType.REQUEST_PROFESSIONAL_CONTACT];case GuidedSelfCheckReviewDecision.URGENT_ESCALATION_CONFIRMED:return[GuidedSelfCheckNextActionType.SEEK_URGENT_ASSESSMENT];}}
 async selectForReview(m:EntityManager,review:GuidedSelfCheckProfessionalReview,type:GuidedSelfCheckNextActionType|undefined,actor:string){if(!type||!this.allowed(review.decision!).includes(type))throw new BadRequestException('Selected next action is not allowed for this review decision');if(type===GuidedSelfCheckNextActionType.BOOK_ESSENTIAL_CHECK&&!await m.getRepository(HealthCheckPackage).findOne({where:{code:'ESSENTIAL',isActive:true}}))throw new ConflictException('The Essential Health Check catalogue item is unavailable');const repo=m.getRepository(GuidedSelfCheckNextAction);const current=await repo.findOne({where:{guidedSelfCheckId:review.guidedSelfCheckId,isCurrent:true},lock:{mode:'pessimistic_write'}});if(current?.source===GuidedSelfCheckNextActionSource.PROFESSIONAL_REVIEW&&current.professionalReviewId===review.id){if(current.type!==type)throw new ConflictException('Completed review next action is immutable');return current;}if(current){current.isCurrent=false;await repo.save(current);}return repo.save(repo.create({guidedSelfCheckId:review.guidedSelfCheckId,classificationId:review.classificationId,professionalReviewId:review.id,type,source:GuidedSelfCheckNextActionSource.PROFESSIONAL_REVIEW,targetMetadata:this.target(type),isCurrent:true,selectedByUserId:actor,selectedAt:new Date()}));}
 async patientForReference(reference:string,userId:string){const x=await this.actions.createQueryBuilder('action').innerJoin('action.selfCheck','selfCheck').where('selfCheck.reference=:reference',{reference}).andWhere('selfCheck.userId=:userId',{userId}).andWhere('action.isCurrent=true').getOne();return x?this.project(x):null;}
 async operational(id:string){const rows=await this.actions.find({where:{guidedSelfCheckId:id},order:{selectedAt:'ASC',id:'ASC'}});return{current:rows.find(x=>x.isCurrent)?this.project(rows.find(x=>x.isCurrent)!):null,history:rows.map(x=>({...this.project(x),isCurrent:x.isCurrent}))};}
 project(x:GuidedSelfCheckNextAction){return{type:x.type,source:x.source,titleKey:P[x.type].titleKey,title:P[x.type].title,message:P[x.type].message,cta:{...P[x.type].cta,...x.targetMetadata},selectedAt:x.selectedAt};}
 private target(t:GuidedSelfCheckNextActionType):Record<string,string>{return t===GuidedSelfCheckNextActionType.BOOK_ESSENTIAL_CHECK?{packageCode:'ESSENTIAL'}:t===GuidedSelfCheckNextActionType.SEEK_URGENT_ASSESSMENT?{domain:'CARE_REQUEST'}:{};}
}
