import { ConflictException } from '@nestjs/common';import { GuidedSelfCheckClinicalGovernanceService } from './guided-self-check-clinical-governance.service';import { GuidedSelfCheckClinicalRuleset } from './entities/guided-self-check-clinical-ruleset.entity';import { GuidedSelfCheckRuleOperator,GuidedSelfCheckRuleSeverity } from './enums/guided-self-check-classification.enum';import { GuidedSelfCheckQuestionType } from './enums/guided-self-check-questionnaire.enum';
describe('GuidedSelfCheckClinicalGovernanceService structural safety',()=>{const service=new GuidedSelfCheckClinicalGovernanceService({} as never,{} as never,{} as never) as any;const question=(type:GuidedSelfCheckQuestionType,options:string[]|null=null)=>({key:'q',type,options});const validate=(condition:any,q:any)=>{const errors:any[]=[];service.validateCondition(condition,new Map([['q',q]]),'condition',errors,0);return errors;};
 it('accepts constrained valid choice rules',()=>expect(validate({questionKey:'q',operator:GuidedSelfCheckRuleOperator.EQUALS,value:'YES'},question(GuidedSelfCheckQuestionType.SINGLE_CHOICE,['YES','NO']))).toEqual([]));
 it('rejects unknown questions',()=>expect(validate({questionKey:'missing',operator:GuidedSelfCheckRuleOperator.EQUALS,value:'YES'},question(GuidedSelfCheckQuestionType.SINGLE_CHOICE,['YES']))).toEqual(expect.arrayContaining([expect.objectContaining({code:'UNKNOWN_QUESTION'})])));
 it('rejects invalid operator/type and choice combinations',()=>{expect(validate({questionKey:'q',operator:GuidedSelfCheckRuleOperator.INCLUDES,value:'YES'},question(GuidedSelfCheckQuestionType.BOOLEAN))).toEqual(expect.arrayContaining([expect.objectContaining({code:'OPERATOR_TYPE_MISMATCH'})]));expect(validate({questionKey:'q',operator:GuidedSelfCheckRuleOperator.EQUALS,value:'UNKNOWN'},question(GuidedSelfCheckQuestionType.SINGLE_CHOICE,['YES']))).toEqual(expect.arrayContaining([expect.objectContaining({code:'INVALID_CHOICE'})]));});
 it('rejects invalid measurement target and malformed groups',()=>{expect(validate({questionKey:'q',operator:GuidedSelfCheckRuleOperator.GTE,field:'value',value:1},question(GuidedSelfCheckQuestionType.BLOOD_PRESSURE))).toEqual(expect.arrayContaining([expect.objectContaining({code:'INVALID_MEASUREMENT_TARGET'})]));expect(validate({operator:GuidedSelfCheckRuleOperator.AND,conditions:[]},question(GuidedSelfCheckQuestionType.BOOLEAN))).toEqual(expect.arrayContaining([expect.objectContaining({code:'EMPTY_GROUP'})]));});
 it('canonical clinical content hash is stable and changes with rules',()=>{const keys={green:'SELF_CHECK_GREEN_COMPLETE',amber:'SELF_CHECK_AMBER_REVIEW',red:'SELF_CHECK_RED_URGENT'};const a=service.hash(1,[],keys);expect(a).toMatch(/^[0-9a-f]{64}$/);expect(service.hash(1,[],keys)).toBe(a);expect(service.hash(1,[{code:'TEST',severity:GuidedSelfCheckRuleSeverity.AMBER,condition:{questionKey:'q',operator:GuidedSelfCheckRuleOperator.UNANSWERED}}],keys)).not.toBe(a);});
 it('rejects stale approval hashes',()=>expect(()=>service.assertApprovedHash({contentHash:'new',approvedContentHash:'old'} as GuidedSelfCheckClinicalRuleset)).toThrow(ConflictException));
});
