import { ConflictException } from '@nestjs/common';import { GuidedSelfCheckProfessionalReviewsService } from './guided-self-check-professional-reviews.service';import { GuidedSelfCheckClassification } from './enums/guided-self-check-classification.enum';import { GuidedSelfCheckReviewDecision,GuidedSelfCheckReviewPriority,GuidedSelfCheckReviewStatus } from './enums/guided-self-check-review.enum';
describe('GuidedSelfCheckProfessionalReviewsService',()=>{
 const classification=(value=GuidedSelfCheckClassification.AMBER,required=true)=>({id:'c',guidedSelfCheckId:'s',classification:value,requiresProfessionalReview:required} as any);
 const creation=()=>{const rows:any[]=[];const history:any[]=[];const repo={findOne:jest.fn(async()=>rows[0]??null),create:jest.fn((x:any)=>x),save:jest.fn(async(x:any)=>{const v={...x,id:'r'};rows[0]=v;return v;})};const m:any={getRepository:jest.fn((e:any)=>e.name==='GuidedSelfCheckProfessionalReview'?repo:{save:jest.fn(async(x:any)=>history.push(x))})};return{rows,history,repo,m};};
 it('does not queue AMBER and creates one internal URGENT RED review',async()=>{const h=creation();const s=new GuidedSelfCheckProfessionalReviewsService(h.repo as never,{} as never);await s.ensureForClassification(h.m,classification());expect(h.rows).toHaveLength(0);const h2=creation();await new GuidedSelfCheckProfessionalReviewsService(h2.repo as never,{} as never).ensureForClassification(h2.m,classification(GuidedSelfCheckClassification.RED));expect(h2.rows[0]).toMatchObject({priority:GuidedSelfCheckReviewPriority.URGENT,reviewModel:'INTERNAL_URGENT'});});
 it('does not queue GREEN and RED creation remains idempotent',async()=>{const h=creation();const s=new GuidedSelfCheckProfessionalReviewsService(h.repo as never,{} as never);await s.ensureForClassification(h.m,classification(GuidedSelfCheckClassification.GREEN,false));expect(h.rows).toHaveLength(0);await s.ensureForClassification(h.m,classification(GuidedSelfCheckClassification.RED));await s.ensureForClassification(h.m,classification(GuidedSelfCheckClassification.RED));expect(h.rows).toHaveLength(1);});
 it('decision model contains no diagnosis or prescribing outcome',()=>{expect(Object.values(GuidedSelfCheckReviewDecision)).not.toContain('DIAGNOSIS');});
 it('allows Operations acknowledgement of an internal RED case without clinical completion',async()=>{const review:any={id:'r',reference:'SC-GSR-X',reviewModel:'INTERNAL_URGENT',classificationSnapshot:GuidedSelfCheckClassification.RED,priority:'URGENT',status:GuidedSelfCheckReviewStatus.PENDING,selfCheck:{reference:'SC-GSC-X'},classificationResult:{urgentAction:true,matchedReasonCodes:[]},history:[]};const reviewRepo={findOne:jest.fn().mockResolvedValue(review),save:jest.fn(async(x:any)=>x)};const historyRepo={save:jest.fn()};const manager:any={getRepository:jest.fn((entity:any)=>entity.name==='GuidedSelfCheckProfessionalReview'?reviewRepo:historyRepo),save:reviewRepo.save};const data:any={transaction:jest.fn((fn:any)=>fn(manager))};const result=await new GuidedSelfCheckProfessionalReviewsService(reviewRepo as never,data).acknowledge('SC-GSR-X','operations-user');expect(result).toMatchObject({status:GuidedSelfCheckReviewStatus.ACKNOWLEDGED,acknowledgedAt:expect.any(Date)});expect(review.decision).toBeUndefined();expect(historyRepo.save).toHaveBeenCalledWith(expect.objectContaining({event:'ACKNOWLEDGED',actorUserId:'operations-user'}));});
 it('does not allow AMBER into the internal urgent acknowledgement workflow',async()=>{const review:any={id:'r',reference:'SC-GSR-X',classificationSnapshot:GuidedSelfCheckClassification.AMBER,status:GuidedSelfCheckReviewStatus.PENDING};const reviewRepo={findOne:jest.fn().mockResolvedValue(review)};const manager:any={getRepository:jest.fn(()=>reviewRepo)};const data:any={transaction:jest.fn((fn:any)=>fn(manager))};await expect(new GuidedSelfCheckProfessionalReviewsService(reviewRepo as never,data).acknowledge('SC-GSR-X','operations-user')).rejects.toBeInstanceOf(ConflictException);});
});
