import { ConflictException } from '@nestjs/common';import { createHash } from 'node:crypto';import { GuidedSelfCheckClassificationsService } from './guided-self-check-classifications.service';import { GuidedSelfCheckAnswerState } from './enums/guided-self-check-questionnaire.enum';import { GuidedSelfCheckClassification,GuidedSelfCheckPatientMessageKey,GuidedSelfCheckRuleOperator,GuidedSelfCheckRuleSeverity } from './enums/guided-self-check-classification.enum';import { GuidedSelfCheckWorkflowStatus } from './enums/guided-self-check.enum';
describe('GuidedSelfCheckClassificationsService',()=>{
 const answer=(value:unknown,state=GuidedSelfCheckAnswerState.KNOWN)=>({questionId:'q1',value,state});const rule=(severity:GuidedSelfCheckRuleSeverity,operator:GuidedSelfCheckRuleOperator,value?:unknown)=>({code:`${severity}_REASON`,severity,condition:{questionKey:'history',operator,value}});const canonical=(v:any):string=>Array.isArray(v)?`[${v.map(canonical).join(',')}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`:JSON.stringify(v);
 const harness=(rules:any[],answers:any[]=[answer('YES')],workflowStatus=GuidedSelfCheckWorkflowStatus.COMPLETED,existing:any=null)=>{const check:any={id:'check',reference:'SC-GSC-X',workflowStatus,questionnaireVersionId:'v1'};const keys={green:'SELF_CHECK_GREEN_COMPLETE',amber:'SELF_CHECK_AMBER_REVIEW',red:'SELF_CHECK_RED_URGENT'};const hash=createHash('sha256').update(canonical({questionnaireVersion:1,rules,patientMessageKeys:keys})).digest('hex');const ruleset:any={id:'ruleset',version:1,questionnaireVersionId:'v1',questionnaireVersion:{version:1},isActive:true,rules,patientMessageKeys:keys,contentHash:hash,approvedContentHash:hash};const questions=[{id:'q1',key:'history'}];const fallback={findOne:jest.fn().mockResolvedValue(null),create:jest.fn((x:any)=>x),save:jest.fn(async(x:any)=>({...x,id:'review'}))};const history={save:jest.fn(),exists:jest.fn().mockResolvedValue(false)};const repos:any={GuidedSelfCheck:{findOne:jest.fn().mockResolvedValue(check)},GuidedSelfCheckClassificationResult:{findOne:jest.fn().mockResolvedValue(existing)},GuidedSelfCheckClinicalRuleset:{findOne:jest.fn().mockResolvedValue(ruleset)},GuidedSelfCheckQuestion:{find:jest.fn().mockResolvedValue(questions)},GuidedSelfCheckAnswer:{find:jest.fn().mockResolvedValue(answers)},GuidedSelfCheckHistory:history,GuidedSelfCheckProfessionalReview:fallback,GuidedSelfCheckProfessionalReviewHistory:{save:jest.fn()}};const manager:any={getRepository:jest.fn((e:any)=>repos[e.name]),create:jest.fn((_e:any,x:any)=>x),save:jest.fn(async(x:any)=>({...x,id:x.id??'classification'}))};return{service:new GuidedSelfCheckClassificationsService({} as never,{} as never,{transaction:jest.fn((fn:any)=>fn(manager))} as never),history,review:fallback};};
 it('classifies GREEN and does not queue review',async()=>{const h=harness([]);await expect(h.service.classifyCompleted('x')).resolves.toMatchObject({classification:GuidedSelfCheckClassification.GREEN,requiresProfessionalReview:false,urgentAction:false,patientMessageKey:GuidedSelfCheckPatientMessageKey.GREEN_COMPLETE});expect(h.review.save).not.toHaveBeenCalled();});
 it('classifies AMBER and queues routine review once',async()=>{const h=harness([rule(GuidedSelfCheckRuleSeverity.AMBER,GuidedSelfCheckRuleOperator.EQUALS,'YES')]);await expect(h.service.classifyCompleted('x')).resolves.toMatchObject({classification:'AMBER',requiresProfessionalReview:true,urgentAction:false});expect(h.review.save).toHaveBeenCalledWith(expect.objectContaining({priority:'ROUTINE',status:'PENDING'}));});
 it('classifies RED and RED overrides AMBER',async()=>{const h=harness([rule(GuidedSelfCheckRuleSeverity.AMBER,GuidedSelfCheckRuleOperator.EQUALS,'YES'),rule(GuidedSelfCheckRuleSeverity.RED,GuidedSelfCheckRuleOperator.EQUALS,'YES')]);await expect(h.service.classifyCompleted('x')).resolves.toMatchObject({classification:'RED',urgentAction:true,matchedReasonCodes:['AMBER_REASON','RED_REASON']});expect(h.review.save).toHaveBeenCalledWith(expect.objectContaining({priority:'URGENT'}));});
 it('DONT_KNOW only matches a configured state rule',async()=>{const configured={code:'IMPORTANT_INFORMATION_MISSING',severity:GuidedSelfCheckRuleSeverity.AMBER,condition:{questionKey:'history',operator:GuidedSelfCheckRuleOperator.STATE_EQUALS,state:GuidedSelfCheckAnswerState.DONT_KNOW}};await expect(harness([],[answer(null,GuidedSelfCheckAnswerState.DONT_KNOW)]).service.classifyCompleted('x')).resolves.toMatchObject({classification:'GREEN'});await expect(harness([configured],[answer(null,GuidedSelfCheckAnswerState.DONT_KNOW)]).service.classifyCompleted('x')).resolves.toMatchObject({classification:'AMBER'});});
 it('supports constrained measurement comparisons',async()=>{const configured={code:'TEST',severity:GuidedSelfCheckRuleSeverity.RED,condition:{questionKey:'history',field:'systolic',operator:GuidedSelfCheckRuleOperator.GTE,value:10}};await expect(harness([configured],[answer({systolic:10})]).service.classifyCompleted('x')).resolves.toMatchObject({classification:'RED'});});
 it('rejects classification before questionnaire completion',async()=>{await expect(harness([],[],GuidedSelfCheckWorkflowStatus.IN_PROGRESS).service.classifyCompleted('x')).rejects.toBeInstanceOf(ConflictException);});
 it('returns historical result idempotently',async()=>{const existing={classification:'AMBER',matchedReasonCodes:['OLD'],rulesetId:'old'};const h=harness([],[],GuidedSelfCheckWorkflowStatus.COMPLETED,existing);await expect(h.service.classifyCompleted('x')).resolves.toBe(existing);expect(h.review.save).not.toHaveBeenCalled();});
 it('records no raw answers in classification history',async()=>{const h=harness([],[answer({private:'answer'})]);await h.service.classifyCompleted('x');expect(JSON.stringify(h.history.save.mock.calls)).not.toContain('private');});
 it('contains no threshold rules in production V1 seed',()=>{expect(require('../database/migrations/1791993600000-GuidedSelfCheckClinicalClassification')).toBeDefined();});
});
