import { ConflictException } from '@nestjs/common';import { GuidedSelfCheckClassificationReprocessingService } from './guided-self-check-classification-reprocessing.service';import { GuidedSelfCheckClassificationStatus } from './enums/guided-self-check-classification.enum';import { GuidedSelfCheckReprocessingOutcome } from './enums/guided-self-check-reprocessing.enum';import { GuidedSelfCheckWorkflowStatus } from './enums/guided-self-check.enum';
describe('GuidedSelfCheckClassificationReprocessingService',()=>{
 const make=(overrides:any={})=>{const check={id:'check',reference:'SC-GSC-X',workflowStatus:GuidedSelfCheckWorkflowStatus.COMPLETED,classificationStatus:GuidedSelfCheckClassificationStatus.CONFIGURATION_REQUIRED,questionnaireVersionId:'qv',questionnaireVersion:{version:1},...overrides};const results={findOne:jest.fn().mockResolvedValue(null),exists:jest.fn().mockResolvedValue(false)};const manager={getRepository:jest.fn((e:any)=>e.name==='GuidedSelfCheckClassificationResult'?results:{} as any)};const classifier={classifyCompleted:jest.fn(),isRulesetUsable:jest.fn().mockReturnValue(true)};const actions={ensureForReference:jest.fn().mockResolvedValue({})};const service=new GuidedSelfCheckClassificationReprocessingService({findOne:jest.fn().mockResolvedValue(check)}as never,{manager}as never,classifier as never,actions as never)as any;service.recordStart=jest.fn();service.recordComplete=jest.fn();service.recordFailure=jest.fn();return{service,classifier,actions,results};};
 it('classifies through the production classifier and ensures its action',async()=>{const h=make();h.classifier.classifyCompleted.mockResolvedValue({rulesetId:'rs',ruleset:{reference:'SC-GCRS-X',version:2},classification:'AMBER'});await expect(h.service.reprocess('SC-GSC-X','actor','SC-GCRS-X')).resolves.toMatchObject({outcome:GuidedSelfCheckReprocessingOutcome.CLASSIFIED,classification:'AMBER',ruleset:{reference:'SC-GCRS-X',version:2}});expect(h.classifier.classifyCompleted).toHaveBeenCalledWith('SC-GSC-X','SC-GCRS-X');expect(h.actions.ensureForReference).toHaveBeenCalledTimes(1);});
 it('leaves missing governed configuration fail-closed',async()=>{const h=make();h.classifier.classifyCompleted.mockResolvedValue(null);await expect(h.service.reprocess('SC-GSC-X','actor')).resolves.toMatchObject({outcome:'STILL_CONFIGURATION_REQUIRED',classificationStatus:'CONFIGURATION_REQUIRED'});expect(h.actions.ensureForReference).not.toHaveBeenCalled();});
 it('does not reclassify an immutable existing classification and repairs its idempotent action',async()=>{const h=make();h.results.findOne.mockResolvedValue({classification:'GREEN',ruleset:{reference:'SC-GCRS-OLD',version:1}});await expect(h.service.reprocess('SC-GSC-X','actor')).resolves.toMatchObject({outcome:'ALREADY_CLASSIFIED',ruleset:{reference:'SC-GCRS-OLD',version:1}});expect(h.classifier.classifyCompleted).not.toHaveBeenCalled();expect(h.actions.ensureForReference).toHaveBeenCalledTimes(1);});
 it('rejects incomplete checks as not eligible',async()=>{const h=make({workflowStatus:GuidedSelfCheckWorkflowStatus.IN_PROGRESS});await expect(h.service.reprocess('SC-GSC-X','actor')).resolves.toMatchObject({outcome:'NOT_ELIGIBLE'});});
 it('records technical/integrity failure as FAILED and never GREEN',async()=>{const h=make();h.classifier.classifyCompleted.mockRejectedValue(new ConflictException('bad frozen answers'));const result=await h.service.reprocess('SC-GSC-X','actor');expect(result).toMatchObject({outcome:'FAILED',classificationStatus:'FAILED',failureCode:'INVALID_FROZEN_ANSWERS'});expect(JSON.stringify(result)).not.toContain('GREEN');expect(h.service.recordFailure).toHaveBeenCalled();});
});
