import { ConflictException,ForbiddenException,Injectable,NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource,EntityManager,Repository } from 'typeorm';
import { ProviderOnboardingStatus } from '../providers/enums/provider-onboarding-status.enum';import { ProviderStatus } from '../providers/enums/provider-status.enum';import { User } from '../users/entities/user.entity';
import { AssignGuidedSelfCheckReviewDto,CancelGuidedSelfCheckReviewDto,CompleteGuidedSelfCheckReviewDto,GuidedSelfCheckReviewListQueryDto } from './dto/guided-self-check-review.dto';
import { GuidedSelfCheckAnswer } from './entities/guided-self-check-answer.entity';import { GuidedSelfCheckClassificationResult } from './entities/guided-self-check-classification.entity';import { GuidedSelfCheckProfessionalReviewHistory } from './entities/guided-self-check-professional-review-history.entity';import { GuidedSelfCheckProfessionalReview } from './entities/guided-self-check-professional-review.entity';import { GuidedSelfCheckQuestionnaireVersion } from './entities/guided-self-check-questionnaire-version.entity';import { GuidedSelfCheckReviewerAuthorization } from './entities/guided-self-check-reviewer-authorization.entity';
import { GuidedSelfCheckClassification } from './enums/guided-self-check-classification.enum';import { GuidedSelfCheckContactStatus,GuidedSelfCheckReviewDecision,GuidedSelfCheckReviewEvent,GuidedSelfCheckReviewOrigin,GuidedSelfCheckReviewPriority,GuidedSelfCheckReviewStatus } from './enums/guided-self-check-review.enum';import { GuidedSelfCheckReviewerAuthorizationStatus } from './enums/guided-self-check-reviewer-authorization.enum';
@Injectable()
export class GuidedSelfCheckProfessionalReviewsService{
 constructor(@InjectRepository(GuidedSelfCheckProfessionalReview)private reviews:Repository<GuidedSelfCheckProfessionalReview>,private data:DataSource){}
 async ensureForClassification(m:EntityManager,result:GuidedSelfCheckClassificationResult){if(!result.requiresProfessionalReview||![GuidedSelfCheckClassification.AMBER,GuidedSelfCheckClassification.RED].includes(result.classification))return null;const repo=m.getRepository(GuidedSelfCheckProfessionalReview);const existing=await repo.findOne({where:{classificationId:result.id}});if(existing)return existing;const priority=result.classification===GuidedSelfCheckClassification.RED?GuidedSelfCheckReviewPriority.URGENT:GuidedSelfCheckReviewPriority.ROUTINE;const review=await repo.save(repo.create({guidedSelfCheckId:result.guidedSelfCheckId,classificationId:result.id,classificationSnapshot:result.classification,priority,origin:GuidedSelfCheckReviewOrigin.CLASSIFICATION_REQUIRED,status:GuidedSelfCheckReviewStatus.PENDING,assignedReviewerUserId:null,assignedReviewerProviderId:null,assignedReviewerAuthorizationId:null,assignedAt:null,startedAt:null,completedAt:null,cancelledAt:null,decision:null,reviewerNotes:null,contactRequired:false,contactStatus:GuidedSelfCheckContactStatus.NOT_REQUIRED,contactedAt:null}));await this.history(m,review.id,GuidedSelfCheckReviewEvent.REVIEW_CREATED,null,null,GuidedSelfCheckReviewStatus.PENDING,{classification:result.classification,priority});return review;}
 async list(q:GuidedSelfCheckReviewListQueryDto){const b=this.reviews.createQueryBuilder('review').innerJoinAndSelect('review.selfCheck','selfCheck').leftJoinAndSelect('review.assignedReviewerUser','reviewer').leftJoinAndSelect('review.assignedReviewerProvider','reviewerProvider').leftJoinAndSelect('review.assignedReviewerAuthorization','reviewerAuthorization');if(q.status)b.andWhere('review.status = :status',{status:q.status});if(q.priority)b.andWhere('review.priority = :priority',{priority:q.priority});if(q.classification)b.andWhere('review.classificationSnapshot = :classification',{classification:q.classification});if(q.assigned!==undefined)b.andWhere(q.assigned?'review.assignedReviewerAuthorizationId IS NOT NULL':'review.assignedReviewerAuthorizationId IS NULL');b.orderBy(`CASE WHEN review.priority = 'URGENT' THEN 0 ELSE 1 END`,'ASC').addOrderBy('review.createdAt','ASC').addOrderBy('review.id','ASC').skip((q.page-1)*q.limit).take(q.limit);const[rows,total]=await b.getManyAndCount();return{items:rows.map(x=>this.queueView(x)),total,page:q.page,limit:q.limit};}
 async getAdmin(reference:string){const r=await this.reviews.findOne({where:{reference},relations:{selfCheck:true,classificationResult:true,assignedReviewerUser:true,assignedReviewerProvider:true,assignedReviewerAuthorization:true,history:{actor:true}},order:{history:{createdAt:'ASC'}}});if(!r)throw new NotFoundException('Professional review was not found');return this.adminView(r);}
 async assign(reference:string,dto:AssignGuidedSelfCheckReviewDto,actorId:string){return this.data.transaction(async m=>{const r=await this.lock(m,reference);if([GuidedSelfCheckReviewStatus.COMPLETED,GuidedSelfCheckReviewStatus.CANCELLED].includes(r.status))throw new ConflictException('Professional review cannot be assigned in its current state');const a=await m.getRepository(GuidedSelfCheckReviewerAuthorization).findOne({where:{reference:dto.reviewerReference},relations:{user:true,provider:true},lock:{mode:'pessimistic_read'}});if(!a||!this.eligible(a))throw new ConflictException('An active authorized clinical reviewer is required');if(r.assignedReviewerAuthorizationId===a.id&&r.status!==GuidedSelfCheckReviewStatus.IN_REVIEW)return this.adminView(r);const from=r.status;const event=r.assignedReviewerUserId?GuidedSelfCheckReviewEvent.REVIEW_REASSIGNED:GuidedSelfCheckReviewEvent.REVIEW_ASSIGNED;const previousReviewerReference=r.assignedReviewerAuthorization?.reference??null;r.assignedReviewerAuthorizationId=a.id;r.assignedReviewerAuthorization=a;r.assignedReviewerProviderId=a.providerId;r.assignedReviewerUserId=a.userId;r.assignedReviewerProvider=a.provider;r.assignedReviewerUser=a.user;r.assignedAt=new Date();r.startedAt=null;r.status=GuidedSelfCheckReviewStatus.ASSIGNED;await m.save(r);await this.history(m,r.id,event,actorId,from,r.status,{previousReviewerReference,reviewerReference:a.reference,providerReference:a.provider.providerReference});return this.adminView(r);});}
 async cancel(reference:string,dto:CancelGuidedSelfCheckReviewDto,actorId:string){return this.data.transaction(async m=>{const r=await this.lock(m,reference);if(r.status===GuidedSelfCheckReviewStatus.CANCELLED)return this.adminView(r);if(r.status===GuidedSelfCheckReviewStatus.COMPLETED)throw new ConflictException('Completed professional review cannot be cancelled');const from=r.status;r.status=GuidedSelfCheckReviewStatus.CANCELLED;r.cancelledAt=new Date();await m.save(r);await this.history(m,r.id,GuidedSelfCheckReviewEvent.REVIEW_CANCELLED,actorId,from,r.status,{reason:dto.reason?.trim()||null});return this.adminView(r);});}
 async getReviewer(reference:string,user:User){const a=await this.requireAuthorizedReviewer(user);const r=await this.loadAssigned(reference,user.id,a.providerId,a.id);const version=await this.data.manager.getRepository(GuidedSelfCheckQuestionnaireVersion).findOne({where:{id:r.classificationResult.questionnaireVersionId},relations:{groups:{questions:true}},order:{groups:{sortOrder:'ASC',questions:{sortOrder:'ASC'}}}});if(!version)throw new ConflictException('Questionnaire version is unavailable');const answers=await this.data.manager.getRepository(GuidedSelfCheckAnswer).find({where:{guidedSelfCheckId:r.guidedSelfCheckId}});const byQuestion=new Map(answers.map(x=>[x.questionId,x]));return{...this.adminView(r),questionnaire:{version:version.version,groups:version.groups.map(g=>({key:g.key,title:g.title,sortOrder:g.sortOrder,questions:g.questions.map(q=>{const x=byQuestion.get(q.id);return{key:q.key,text:q.text,type:q.type,sortOrder:q.sortOrder,answer:x?{state:x.state,value:x.value,provenance:x.provenance,updatedAt:x.updatedAt}:null};})}))}};}
 async start(reference:string,user:User){const a=await this.requireAuthorizedReviewer(user);return this.data.transaction(async m=>{const r=await this.lockAssigned(m,reference,user.id,a.providerId,a.id);if(r.status===GuidedSelfCheckReviewStatus.IN_REVIEW)return this.adminView(r);if(r.status!==GuidedSelfCheckReviewStatus.ASSIGNED)throw new ConflictException('Only an assigned professional review can be started');r.status=GuidedSelfCheckReviewStatus.IN_REVIEW;r.startedAt=new Date();await m.save(r);await this.history(m,r.id,GuidedSelfCheckReviewEvent.REVIEW_STARTED,user.id,GuidedSelfCheckReviewStatus.ASSIGNED,r.status,{reviewerReference:a.reference,providerReference:a.provider.providerReference});return this.adminView(r);});}
 async complete(reference:string,user:User,dto:CompleteGuidedSelfCheckReviewDto){const a=await this.requireAuthorizedReviewer(user);return this.data.transaction(async m=>{const r=await this.lockAssigned(m,reference,user.id,a.providerId,a.id);if(r.status===GuidedSelfCheckReviewStatus.COMPLETED)return this.adminView(r);if(r.status!==GuidedSelfCheckReviewStatus.IN_REVIEW)throw new ConflictException('Only a review in progress can be completed');r.decision=dto.decision;r.reviewerNotes=dto.reviewerNotes?.trim()||null;r.contactRequired=dto.contactRequired===true||dto.decision===GuidedSelfCheckReviewDecision.PATIENT_CONTACT_REQUIRED;r.contactStatus=r.contactRequired?GuidedSelfCheckContactStatus.REQUIRED:GuidedSelfCheckContactStatus.NOT_REQUIRED;r.completedAt=new Date();r.status=GuidedSelfCheckReviewStatus.COMPLETED;await m.save(r);await this.history(m,r.id,GuidedSelfCheckReviewEvent.REVIEW_COMPLETED,user.id,GuidedSelfCheckReviewStatus.IN_REVIEW,r.status,{decision:r.decision,contactRequired:r.contactRequired,reviewerReference:a.reference,providerReference:a.provider.providerReference});return this.adminView(r);});}
 async getPatientState(guidedSelfCheckId:string){const r=await this.reviews.findOne({where:{guidedSelfCheckId}});return r?{required:true,status:r.status,completedAt:r.completedAt}:null;}
 private async requireAuthorizedReviewer(user:User){const a=await this.data.manager.getRepository(GuidedSelfCheckReviewerAuthorization).findOne({where:{userId:user.id,status:GuidedSelfCheckReviewerAuthorizationStatus.AUTHORIZED},relations:{user:true,provider:true}});if(!a||!this.eligible(a))throw new ForbiddenException('Active individual clinical-review authorization is required');return a;}
 private eligible(a:GuidedSelfCheckReviewerAuthorization){return a.status===GuidedSelfCheckReviewerAuthorizationStatus.AUTHORIZED&&!a.provider.deletedAt&&a.provider.status===ProviderStatus.ACTIVE&&a.provider.onboardingStatus===ProviderOnboardingStatus.APPROVED&&a.provider.userId===a.userId;}
 private async lock(m:EntityManager,reference:string){const r=await m.getRepository(GuidedSelfCheckProfessionalReview).findOne({where:{reference},lock:{mode:'pessimistic_write'},relations:{selfCheck:true,classificationResult:true,assignedReviewerUser:true,assignedReviewerProvider:true,assignedReviewerAuthorization:true}});if(!r)throw new NotFoundException('Professional review was not found');return r;}
 private async lockAssigned(m:EntityManager,reference:string,userId:string,providerId:string,authorizationId:string){const r=await this.lock(m,reference);if(r.assignedReviewerUserId!==userId||r.assignedReviewerProviderId!==providerId||r.assignedReviewerAuthorizationId!==authorizationId)throw new ForbiddenException('Professional review is assigned to another reviewer or requires explicit governed reassignment');return r;}
 private async loadAssigned(reference:string,userId:string,providerId:string,authorizationId:string){const r=await this.reviews.findOne({where:{reference,assignedReviewerUserId:userId,assignedReviewerProviderId:providerId,assignedReviewerAuthorizationId:authorizationId},relations:{selfCheck:true,classificationResult:true,assignedReviewerUser:true,assignedReviewerProvider:true,assignedReviewerAuthorization:true,history:{actor:true}},order:{history:{createdAt:'ASC'}}});if(!r)throw new NotFoundException('Assigned professional review was not found');return r;}
 private history(m:EntityManager,reviewId:string,event:GuidedSelfCheckReviewEvent,actorUserId:string|null,fromStatus:GuidedSelfCheckReviewStatus|null,toStatus:GuidedSelfCheckReviewStatus|null,metadata:Record<string,unknown>){return m.getRepository(GuidedSelfCheckProfessionalReviewHistory).save({reviewId,event,actorUserId,fromStatus,toStatus,metadata});}
 private reviewer(r:GuidedSelfCheckProfessionalReview){return r.assignedReviewerProvider&&r.assignedReviewerUser?{reviewerReference:r.assignedReviewerAuthorization?.reference??null,providerReference:r.assignedReviewerProvider.providerReference,displayName:r.assignedReviewerUser.displayName??r.assignedReviewerProvider.displayName}:null;}
 private queueView(r:GuidedSelfCheckProfessionalReview){return{reference:r.reference,selfCheckReference:r.selfCheck.reference,classification:r.classificationSnapshot,priority:r.priority,status:r.status,questionnaireCompletedAt:r.selfCheck.completedAt,assignedReviewer:this.reviewer(r),assignedAt:r.assignedAt,createdAt:r.createdAt};}
 private adminView(r:GuidedSelfCheckProfessionalReview){return{...this.queueView(r),origin:r.origin,matchedReasonCodes:r.classificationResult?.matchedReasonCodes??[],urgentAction:r.classificationResult?.urgentAction??r.priority===GuidedSelfCheckReviewPriority.URGENT,startedAt:r.startedAt,completedAt:r.completedAt,cancelledAt:r.cancelledAt,decision:r.decision,contactRequired:r.contactRequired,contactStatus:r.contactStatus,contactedAt:r.contactedAt,history:r.history?.map(h=>({event:h.event,fromStatus:h.fromStatus,toStatus:h.toStatus,actor:h.actor?{displayName:h.actor.displayName}:null,metadata:h.metadata,createdAt:h.createdAt}))??[]};}
}
