import { ConflictException,Injectable,NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource,Repository } from 'typeorm';
import { Provider } from '../providers/entities/provider.entity';
import { ProviderOnboardingStatus } from '../providers/enums/provider-onboarding-status.enum';
import { ProviderStatus } from '../providers/enums/provider-status.enum';
import { User } from '../users/entities/user.entity';
import { AuthorizeGuidedSelfCheckReviewerDto,DisableGuidedSelfCheckReviewerDto,GuidedSelfCheckReviewerDirectoryQueryDto } from './dto/guided-self-check-reviewer-authorization.dto';
import { GuidedSelfCheckReviewerAuthorizationHistory } from './entities/guided-self-check-reviewer-authorization-history.entity';
import { GuidedSelfCheckReviewerAuthorization } from './entities/guided-self-check-reviewer-authorization.entity';
import { GuidedSelfCheckReviewerAuthorizationEvent,GuidedSelfCheckReviewerAuthorizationStatus } from './enums/guided-self-check-reviewer-authorization.enum';
@Injectable()
export class GuidedSelfCheckReviewerAuthorizationsService{
 constructor(@InjectRepository(GuidedSelfCheckReviewerAuthorization)private authorizations:Repository<GuidedSelfCheckReviewerAuthorization>,private data:DataSource){}
 async list(q:GuidedSelfCheckReviewerDirectoryQueryDto,eligibleOnly=false){const b=this.authorizations.createQueryBuilder('authorization').innerJoinAndSelect('authorization.user','user').innerJoinAndSelect('authorization.provider','provider');if(eligibleOnly)b.andWhere('authorization.status = :authorized',{authorized:GuidedSelfCheckReviewerAuthorizationStatus.AUTHORIZED}).andWhere('provider.status = :active',{active:ProviderStatus.ACTIVE}).andWhere('provider.onboardingStatus = :approved',{approved:ProviderOnboardingStatus.APPROVED}).andWhere('provider.deletedAt IS NULL').andWhere('provider.userId = authorization.userId');else if(q.status)b.andWhere('authorization.status = :status',{status:q.status});if(q.providerReference)b.andWhere('provider.providerReference = :providerReference',{providerReference:q.providerReference});if(q.q)b.andWhere('(user.displayName ILIKE :search OR provider.displayName ILIKE :search)',{search:`%${q.q.trim()}%`});b.orderBy('user.displayName','ASC','NULLS LAST').addOrderBy('authorization.id','ASC').skip((q.page-1)*q.limit).take(q.limit);const[rows,total]=await b.getManyAndCount();return{items:rows.map(x=>this.view(x)),total,page:q.page,limit:q.limit};}
 async get(reference:string){const a=await this.authorizations.findOne({where:{reference},relations:{user:true,provider:true,history:{actor:true}},order:{history:{createdAt:'ASC'}}});if(!a)throw new NotFoundException('Clinical reviewer authorization was not found');return this.view(a,true);}
 async authorize(dto:AuthorizeGuidedSelfCheckReviewerDto,actorUserId:string){return this.data.transaction(async m=>{const p=await m.getRepository(Provider).findOne({where:{providerReference:dto.providerReference},withDeleted:true,lock:{mode:'pessimistic_write'}});const user=p?.user??(p?.userId?await m.getRepository(User).findOne({where:{id:p.userId}}):null);if(p)p.user=user!;if(!p||p.deletedAt||p.status!==ProviderStatus.ACTIVE||p.onboardingStatus!==ProviderOnboardingStatus.APPROVED||!p.userId||!user)throw new ConflictException('Reviewer must have an unambiguous linked active approved Provider affiliation');const repo=m.getRepository(GuidedSelfCheckReviewerAuthorization);let a=await repo.findOne({where:{userId:p.userId,providerId:p.id},lock:{mode:'pessimistic_write'}});if(a?.status===GuidedSelfCheckReviewerAuthorizationStatus.AUTHORIZED){a.user=user;a.provider=p;return this.view(a);}const previous=a?.status??null;const event=a?GuidedSelfCheckReviewerAuthorizationEvent.REVIEWER_REAUTHORIZED:GuidedSelfCheckReviewerAuthorizationEvent.REVIEWER_AUTHORIZED;if(!a)a=repo.create({userId:p.userId,providerId:p.id});a.status=GuidedSelfCheckReviewerAuthorizationStatus.AUTHORIZED;a.approvedByUserId=actorUserId;a.approvedAt=new Date();a.disabledAt=null;a.user=user;a.provider=p;a=await repo.save(a);await m.getRepository(GuidedSelfCheckReviewerAuthorizationHistory).save({authorizationId:a.id,event,actorUserId,fromStatus:previous,toStatus:a.status,reason:dto.reason?.trim()||null});return this.view(a);});}
 async disable(reference:string,dto:DisableGuidedSelfCheckReviewerDto,actorUserId:string){return this.data.transaction(async m=>{const repo=m.getRepository(GuidedSelfCheckReviewerAuthorization);const locked=await repo.findOne({where:{reference},lock:{mode:'pessimistic_write'}});if(!locked)throw new NotFoundException('Clinical reviewer authorization was not found');const a=await repo.findOne({where:{id:locked.id},relations:{user:true,provider:true}});if(!a)throw new NotFoundException('Clinical reviewer authorization was not found');if(a.status===GuidedSelfCheckReviewerAuthorizationStatus.DISABLED)return this.view(a);const from=a.status;a.status=GuidedSelfCheckReviewerAuthorizationStatus.DISABLED;a.disabledAt=new Date();await repo.save(a);await m.getRepository(GuidedSelfCheckReviewerAuthorizationHistory).save({authorizationId:a.id,event:GuidedSelfCheckReviewerAuthorizationEvent.REVIEWER_DISABLED,actorUserId,fromStatus:from,toStatus:a.status,reason:dto.reason.trim()});return this.view(a);});}
 private view(a:GuidedSelfCheckReviewerAuthorization,includeHistory=false){return{reference:a.reference,displayName:a.user.displayName??a.provider.displayName,provider:{reference:a.provider.providerReference,displayName:a.provider.displayName},status:a.status,approvedAt:a.approvedAt,disabledAt:a.disabledAt,createdAt:a.createdAt,...includeHistory?{history:a.history?.map(h=>({event:h.event,fromStatus:h.fromStatus,toStatus:h.toStatus,reason:h.reason,actor:h.actor?{displayName:h.actor.displayName}:null,createdAt:h.createdAt}))??[]}:{}};}
}
