import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, In, Repository } from 'typeorm';
import { Patient } from '../patients/entities/patient.entity';
import { PatientStatus } from '../patients/enums/patient-status.enum';
import { UpdateGuidedSelfCheckProductDto } from './dto/guided-self-check.dto';
import { GuidedSelfCheckHistory } from './entities/guided-self-check-history.entity';
import { GuidedSelfCheckProduct } from './entities/guided-self-check-product.entity';
import { GuidedSelfCheck } from './entities/guided-self-check.entity';
import { GuidedSelfCheckFundingStatus, GuidedSelfCheckWorkflowStatus } from './enums/guided-self-check.enum';
import { generateGuidedSelfCheckReference } from './guided-self-check-reference';

@Injectable()
export class GuidedSelfChecksService {
  constructor(
    @InjectRepository(GuidedSelfCheckProduct) private readonly products: Repository<GuidedSelfCheckProduct>,
    @InjectRepository(GuidedSelfCheck) private readonly checks: Repository<GuidedSelfCheck>,
    private readonly data: DataSource,
  ) {}

  private async product() { const p=await this.products.findOne({where:{code:'GUIDED_SELF_CHECK'}}); if(!p) throw new NotFoundException('Guided Self-Check configuration was not found'); return p; }
  private pricing(p:GuidedSelfCheckProduct,now=new Date()){const active=p.promotionalPriceMinor!==null&&(!p.promotionStartsAt||p.promotionStartsAt<=now)&&(!p.promotionEndsAt||p.promotionEndsAt>now);return{active,effective:active?p.promotionalPriceMinor!:p.standardPriceMinor};}
  private productView(p:GuidedSelfCheckProduct){const x=this.pricing(p);return{name:p.name,currency:p.currency,standardPriceMinor:Number(p.standardPriceMinor),effectivePriceMinor:Number(x.effective),promotionalPriceMinor:x.active?Number(p.promotionalPriceMinor):null,promotionActive:x.active,promotionEndsAt:x.active?p.promotionEndsAt:null,available:p.isActive};}
  async getProduct(){return this.productView(await this.product());}
  async getAdminProduct(){const p=await this.product();return{...this.productView(p),promotionalPriceMinor:p.promotionalPriceMinor===null?null:Number(p.promotionalPriceMinor),promotionStartsAt:p.promotionStartsAt,promotionEndsAt:p.promotionEndsAt,isActive:p.isActive,createdAt:p.createdAt,updatedAt:p.updatedAt};}
  async updateProduct(dto:UpdateGuidedSelfCheckProductDto){return this.data.transaction(async m=>{const p=await m.getRepository(GuidedSelfCheckProduct).findOne({where:{code:'GUIDED_SELF_CHECK'},lock:{mode:'pessimistic_write'}});if(!p)throw new NotFoundException('Guided Self-Check configuration was not found');if(dto.name!==undefined){const name=dto.name.trim();if(!name)throw new BadRequestException('Product name must not be blank');p.name=name;}if(dto.currency!==undefined)p.currency=dto.currency.toUpperCase();if(dto.standardPriceMinor!==undefined)p.standardPriceMinor=String(dto.standardPriceMinor);if(dto.promotionalPriceMinor!==undefined)p.promotionalPriceMinor=dto.promotionalPriceMinor===null?null:String(dto.promotionalPriceMinor);if(dto.promotionStartsAt!==undefined)p.promotionStartsAt=dto.promotionStartsAt===null?null:new Date(dto.promotionStartsAt);if(dto.promotionEndsAt!==undefined)p.promotionEndsAt=dto.promotionEndsAt===null?null:new Date(dto.promotionEndsAt);if(dto.isActive!==undefined)p.isActive=dto.isActive;if(p.promotionalPriceMinor!==null&&BigInt(p.promotionalPriceMinor)>BigInt(p.standardPriceMinor))throw new BadRequestException('Promotional price cannot exceed standard price');if(p.promotionStartsAt&&p.promotionEndsAt&&p.promotionStartsAt>=p.promotionEndsAt)throw new BadRequestException('Promotion end must be after promotion start');await m.save(p);const x=this.pricing(p);return{name:p.name,currency:p.currency,standardPriceMinor:Number(p.standardPriceMinor),effectivePriceMinor:Number(x.effective),promotionalPriceMinor:p.promotionalPriceMinor===null?null:Number(p.promotionalPriceMinor),promotionActive:x.active,promotionStartsAt:p.promotionStartsAt,promotionEndsAt:p.promotionEndsAt,isActive:p.isActive,available:p.isActive,createdAt:p.createdAt,updatedAt:p.updatedAt};});}
  private view(s:GuidedSelfCheck){return{reference:s.reference,currency:s.currency,standardPriceMinor:Number(s.standardPriceMinorSnapshot),promotionalPriceMinor:s.promotionalPriceMinorSnapshot===null?null:Number(s.promotionalPriceMinorSnapshot),effectivePriceMinor:Number(s.effectivePriceMinor),promotionApplied:s.promotionApplied,fundingStatus:s.fundingStatus,workflowStatus:s.workflowStatus,paidAt:s.paidAt,canBegin:[GuidedSelfCheckFundingStatus.PAID,GuidedSelfCheckFundingStatus.SATISFIED_FREE].includes(s.fundingStatus)&&s.workflowStatus===GuidedSelfCheckWorkflowStatus.NOT_STARTED,canResume:s.workflowStatus===GuidedSelfCheckWorkflowStatus.IN_PROGRESS,createdAt:s.createdAt,updatedAt:s.updatedAt};}
  async create(userId:string){return this.data.transaction(async m=>{const patient=await m.getRepository(Patient).findOne({where:{userId,status:PatientStatus.ACTIVE},lock:{mode:'pessimistic_write'}});if(!patient)throw new NotFoundException('Patient profile was not found');const open=await m.getRepository(GuidedSelfCheck).findOne({where:{patientId:patient.id,fundingStatus:In([GuidedSelfCheckFundingStatus.UNPAID,GuidedSelfCheckFundingStatus.PAYMENT_PENDING]),workflowStatus:GuidedSelfCheckWorkflowStatus.NOT_STARTED},order:{createdAt:'DESC'}});if(open)return this.view(open);const p=await m.getRepository(GuidedSelfCheckProduct).findOne({where:{code:'GUIDED_SELF_CHECK'},lock:{mode:'pessimistic_read'}});if(!p||!p.isActive)throw new ConflictException('Guided Self-Check is currently unavailable');const x=this.pricing(p);const free=BigInt(x.effective)===0n;const s=await m.save(m.create(GuidedSelfCheck,{reference:generateGuidedSelfCheckReference(),patientId:patient.id,userId,currency:p.currency,standardPriceMinorSnapshot:p.standardPriceMinor,promotionalPriceMinorSnapshot:x.active?p.promotionalPriceMinor:null,effectivePriceMinor:x.effective,promotionApplied:x.active,fundingStatus:free?GuidedSelfCheckFundingStatus.SATISFIED_FREE:GuidedSelfCheckFundingStatus.UNPAID,workflowStatus:GuidedSelfCheckWorkflowStatus.NOT_STARTED,paidAt:free?new Date():null}));await m.save(m.create(GuidedSelfCheckHistory,{guidedSelfCheckId:s.id,event:free?'CREATED_SATISFIED_FREE':'CREATED',actorUserId:userId,metadata:{}}));return this.view(s);});}
  async list(userId:string){const rows=await this.checks.find({where:{userId},order:{createdAt:'DESC',id:'DESC'},take:50});return{items:rows.map(x=>this.view(x))};}
  async get(reference:string,userId:string){const s=await this.checks.findOne({where:{reference,userId}});if(!s)throw new NotFoundException('Guided Self-Check was not found');return this.view(s);}
}
