export enum FastTrackStatus {
  SUBMITTED = 'SUBMITTED',
  VERIFYING = 'VERIFYING',
  READY_FOR_PAYMENT = 'READY_FOR_PAYMENT',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAID = 'PAID',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}
