import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { EntityManager, Repository } from 'typeorm';
import { ProviderEarningsService } from '../earnings/provider-earnings.service';
import { Patient } from '../patients/entities/patient.entity';
import { PatientStatus } from '../patients/enums/patient-status.enum';
import { CurrentProviderService } from '../providers/current-provider.service';
import { Provider } from '../providers/entities/provider.entity';
import { ProviderOnboardingStatus } from '../providers/enums/provider-onboarding-status.enum';
import { ProviderStatus } from '../providers/enums/provider-status.enum';
import { User } from '../users/entities/user.entity';
import { ConnectionListQueryDto, ConvertConnectionDto, ProviderConnectionDecisionDto, ResubmitExistingPatientLinkDto, StartExistingPatientLinkDto, StartNewPatientRegistrationDto, UpdateProviderConnectionConfigDto } from './dto/patient-provider-connection.dto';
import { PatientProviderConnectionFunding } from './entities/patient-provider-connection-funding.entity';
import { PatientProviderConnectionHistory } from './entities/patient-provider-connection-history.entity';
import { PatientProviderConnection } from './entities/patient-provider-connection.entity';
import { PatientProviderConnectionFundingPurpose, PatientProviderConnectionFundingStatus } from './enums/patient-provider-connection-funding.enum';
import { PatientProviderConnectionStatus } from './enums/patient-provider-connection-status.enum';
import { PatientProviderConnectionType } from './enums/patient-provider-connection-type.enum';
import { generatePatientProviderConnectionReference } from './patient-provider-connection-reference';

@Injectable()
export class PatientProviderConnectionsService {
 constructor(@InjectRepository(PatientProviderConnection) private readonly connections: Repository<PatientProviderConnection>, @InjectRepository(Patient) private readonly patients: Repository<Patient>, @InjectRepository(Provider) private readonly providers: Repository<Provider>, private readonly currentProvider: CurrentProviderService, private readonly earnings: ProviderEarningsService) {}

 async getProviderConfig(user: User) { return this.configView(await this.currentProvider.resolveOperational(user)); }
 async updateProviderConfig(user: User, dto: UpdateProviderConnectionConfigDto) {
  this.validateConfig(dto);
  const provider = await this.currentProvider.resolveOperational(user);
  Object.assign(provider, { newPatientRegistrationEnabled: dto.newPatientRegistrationEnabled, newPatientRegistrationFeeMinor: dto.newPatientRegistrationEnabled ? String(dto.newPatientRegistrationFeeMinor) : null, newPatientRegistrationCurrency: dto.newPatientRegistrationEnabled ? dto.newPatientRegistrationCurrency!.toUpperCase() : null, existingPatientLinkEnabled: dto.existingPatientLinkEnabled, existingPatientLinkFeeMinor: dto.existingPatientLinkEnabled ? String(dto.existingPatientLinkFeeMinor) : null, existingPatientLinkCurrency: dto.existingPatientLinkEnabled ? dto.existingPatientLinkCurrency!.toUpperCase() : null });
  return this.configView(await this.providers.save(provider));
 }
 async directory(user: User, query: ConnectionListQueryDto) {
  await this.patient(user.id); const qb = this.operationalProviders().andWhere('(provider.newPatientRegistrationEnabled = true OR provider.existingPatientLinkEnabled = true)');
  if (query.q) qb.andWhere('provider.displayName ILIKE :search', { search: `%${query.q}%` });
  qb.orderBy('provider.displayName', 'ASC').addOrderBy('provider.providerReference', 'ASC').skip((query.page - 1) * query.limit).take(query.limit);
  const [rows, total] = await qb.getManyAndCount(); return this.page(rows.map(row => ({ ...this.providerView(row), newPatientRegistration: { enabled: row.newPatientRegistrationEnabled, feeMinor: row.newPatientRegistrationEnabled ? Number(row.newPatientRegistrationFeeMinor) : null, currency: row.newPatientRegistrationEnabled ? row.newPatientRegistrationCurrency : null }, existingPatientLink: { enabled: row.existingPatientLinkEnabled, feeMinor: row.existingPatientLinkEnabled ? Number(row.existingPatientLinkFeeMinor) : null, currency: row.existingPatientLinkEnabled ? row.existingPatientLinkCurrency : null } })), query, total);
 }
 async startNew(user: User, dto: StartNewPatientRegistrationDto) { return this.start(user, dto.providerReference, PatientProviderConnectionType.NEW_PATIENT_REGISTRATION, null, dto.consentAcknowledged); }
 async startExisting(user: User, dto: StartExistingPatientLinkDto) { return this.start(user, dto.providerReference, PatientProviderConnectionType.EXISTING_PATIENT_LINK, dto.externalPatientReference, dto.consentAcknowledged); }
 private async start(user: User, providerReference: string, type: PatientProviderConnectionType, claimed: string | null, consent: boolean) {
  if (!consent) throw new BadRequestException('Explicit patient consent is required'); const patient = await this.patient(user.id);
  return this.connections.manager.transaction(async manager => {
   await manager.getRepository(Patient).findOneOrFail({ where: { id: patient.id }, lock: { mode: 'pessimistic_write' } });
   const provider = await this.operationalProviders(manager.getRepository(Provider)).andWhere('provider.providerReference = :reference', { reference: providerReference }).getOne(); if (!provider) throw new NotFoundException('Provider was not found');
   const enabled = type === PatientProviderConnectionType.NEW_PATIENT_REGISTRATION ? provider.newPatientRegistrationEnabled : provider.existingPatientLinkEnabled; const amount = type === PatientProviderConnectionType.NEW_PATIENT_REGISTRATION ? provider.newPatientRegistrationFeeMinor : provider.existingPatientLinkFeeMinor; const currency = type === PatientProviderConnectionType.NEW_PATIENT_REGISTRATION ? provider.newPatientRegistrationCurrency : provider.existingPatientLinkCurrency;
   if (!enabled || amount == null || !currency) throw new ConflictException('Provider does not support this Patient Connection path');
   const active = await manager.getRepository(PatientProviderConnection).createQueryBuilder('connection').where('connection.patientId = :patientId', { patientId: patient.id }).andWhere('connection.providerId = :providerId', { providerId: provider.id }).andWhere('connection.status IN (:...statuses)', { statuses: [PatientProviderConnectionStatus.AWAITING_FUNDING, PatientProviderConnectionStatus.SUBMITTED, PatientProviderConnectionStatus.UNABLE_TO_VERIFY, PatientProviderConnectionStatus.CONNECTED] }).setLock('pessimistic_write').getOne(); if (active) throw new ConflictException('An active Patient connection already exists for this Provider');
   const free = BigInt(amount) === 0n; const status = free ? PatientProviderConnectionStatus.SUBMITTED : PatientProviderConnectionStatus.AWAITING_FUNDING; const now = new Date(); const repo = manager.getRepository(PatientProviderConnection); const connection = await repo.save(repo.create({ reference: generatePatientProviderConnectionReference(), patientId: patient.id, providerId: provider.id, initiatedByUserId: user.id, originalIntent: type, currentPath: type, status, claimedExternalPatientReference: claimed, externalPatientReference: null, demographicSnapshot: this.demographics(patient), consentCapturedAt: now, commercialAmountMinor: amount, commercialCurrency: currency, verificationFailedAt: null, conversionRequestedAt: null, connectedAt: null }));
   await manager.getRepository(PatientProviderConnectionFunding).save({ connectionId: connection.id, purpose: PatientProviderConnectionFundingPurpose.INITIAL, amountMinor: amount, currency, status: free ? PatientProviderConnectionFundingStatus.SATISFIED_FREE : PatientProviderConnectionFundingStatus.PENDING, paidAt: null }); await this.history(manager, connection, null, status, user.id, free ? 'INITIATED_FREE_AND_SUBMITTED' : 'INITIATED_AWAITING_FUNDING'); connection.provider = provider; connection.patient = patient; connection.fundings = []; return this.map(connection);
  });
 }
 async listMine(user: User, query: ConnectionListQueryDto) { const patient = await this.patient(user.id); const qb = this.readBuilder().where('connection.patientId = :patientId', { patientId: patient.id }).orderBy('connection.createdAt', 'DESC').addOrderBy('connection.reference', 'DESC').skip((query.page - 1) * query.limit).take(query.limit); const [rows,total] = await qb.getManyAndCount(); return this.page(rows.map(row => this.map(row)), query, total); }
 async getMine(user: User, reference: string) { const patient = await this.patient(user.id); const row = await this.readBuilder().where('connection.reference = :reference', { reference }).andWhere('connection.patientId = :patientId', { patientId: patient.id }).getOne(); if (!row) this.notFound(); return this.map(row); }
 async cancel(user:User,reference:string){const patient=await this.patient(user.id);return this.connections.manager.transaction(async manager=>{const row=await this.lockPatient(manager,patient.id,reference);if(row.status===PatientProviderConnectionStatus.CANCELLED)return this.map(row);if([PatientProviderConnectionStatus.CONNECTED,PatientProviderConnectionStatus.REJECTED].includes(row.status))throw new ConflictException('Connection can no longer be cancelled');const from=row.status;row.status=PatientProviderConnectionStatus.CANCELLED;await manager.getRepository(PatientProviderConnection).save(row);await this.history(manager,row,from,row.status,user.id,'PATIENT_CANCELLED');return this.map(row);});}
 async listProvider(user: User, query: ConnectionListQueryDto) { const provider = await this.currentProvider.resolveOperational(user); const qb = this.readBuilder().where('connection.providerId = :providerId', { providerId: provider.id }).orderBy('connection.createdAt', 'DESC').addOrderBy('connection.reference', 'DESC').skip((query.page - 1) * query.limit).take(query.limit); const [rows,total] = await qb.getManyAndCount(); return this.page(rows.map(row => this.mapProvider(row)), query, total); }
 async getProvider(user: User, reference: string) { const provider = await this.currentProvider.resolveOperational(user); const row = await this.readBuilder().where('connection.reference = :reference', { reference }).andWhere('connection.providerId = :providerId', { providerId: provider.id }).getOne(); if (!row) this.notFound(); return this.mapProvider(row); }
 async unableToVerify(user: User, reference: string, dto: ProviderConnectionDecisionDto) { return this.providerTransition(user, reference, PatientProviderConnectionStatus.UNABLE_TO_VERIFY, dto, 'PROVIDER_UNABLE_TO_VERIFY'); }
 async reject(user: User, reference: string, dto: ProviderConnectionDecisionDto) { return this.providerTransition(user, reference, PatientProviderConnectionStatus.REJECTED, dto, 'PROVIDER_REJECTED'); }
 async confirm(user: User, reference: string, dto: ProviderConnectionDecisionDto) {
  if (!dto.externalPatientReference) throw new BadRequestException('externalPatientReference is required'); const provider = await this.currentProvider.resolveOperational(user);
  return this.connections.manager.transaction(async manager => { const row = await this.lockProvider(manager, provider.id, reference); if (row.status === PatientProviderConnectionStatus.CONNECTED) return this.mapProvider(row); if (row.status !== PatientProviderConnectionStatus.SUBMITTED) throw new ConflictException('Connection is not ready for Provider confirmation'); if (!(await this.fundingSatisfied(manager, row.id))) throw new ConflictException('Connection funding is not satisfied'); const from = row.status; row.externalPatientReference = dto.externalPatientReference!.trim(); row.status = PatientProviderConnectionStatus.CONNECTED; row.connectedAt = new Date(); await manager.getRepository(PatientProviderConnection).save(row); await this.history(manager,row,from,row.status,user.id,row.currentPath === PatientProviderConnectionType.EXISTING_PATIENT_LINK ? 'EXISTING_RECORD_CONFIRMED' : 'NEW_REGISTRATION_COMPLETED'); await this.earnings.markPatientConnectionPayable(manager,row.reference,user.id); return this.mapProvider(row); });
 }
 private async providerTransition(user: User, reference: string, to: PatientProviderConnectionStatus, dto: ProviderConnectionDecisionDto, reason: string) { const provider = await this.currentProvider.resolveOperational(user); return this.connections.manager.transaction(async manager => { const row = await this.lockProvider(manager, provider.id, reference); if (row.status !== PatientProviderConnectionStatus.SUBMITTED) throw new ConflictException('Connection is not awaiting Provider processing'); if (to === PatientProviderConnectionStatus.UNABLE_TO_VERIFY && row.currentPath !== PatientProviderConnectionType.EXISTING_PATIENT_LINK) throw new ConflictException('Only existing-patient verification can be unable to verify'); const from=row.status; row.status=to; if(to===PatientProviderConnectionStatus.UNABLE_TO_VERIFY) row.verificationFailedAt=new Date(); await manager.getRepository(PatientProviderConnection).save(row); await this.history(manager,row,from,to,user.id,reason,dto.reason ?? null); return this.mapProvider(row); }); }
 async resubmit(user: User, reference: string, dto: ResubmitExistingPatientLinkDto) { const patient=await this.patient(user.id); return this.connections.manager.transaction(async manager=>{ const row=await this.lockPatient(manager,patient.id,reference); if(row.status!==PatientProviderConnectionStatus.UNABLE_TO_VERIFY || row.currentPath!==PatientProviderConnectionType.EXISTING_PATIENT_LINK) throw new ConflictException('Connection cannot be resubmitted'); const from=row.status; row.claimedExternalPatientReference=dto.externalPatientReference.trim(); row.demographicSnapshot=this.demographics(patient); row.status=PatientProviderConnectionStatus.SUBMITTED; await manager.getRepository(PatientProviderConnection).save(row); await this.history(manager,row,from,row.status,user.id,'PATIENT_CORRECTED_AND_RESUBMITTED'); return this.map(row); }); }
 async convert(user: User, reference: string, dto: ConvertConnectionDto) { if(!dto.consentAcknowledged) throw new BadRequestException('Explicit conversion consent is required'); const patient=await this.patient(user.id); return this.connections.manager.transaction(async manager=>{ const row=await this.lockPatient(manager,patient.id,reference); if(row.originalIntent!==PatientProviderConnectionType.EXISTING_PATIENT_LINK || row.currentPath!==PatientProviderConnectionType.EXISTING_PATIENT_LINK || row.status!==PatientProviderConnectionStatus.UNABLE_TO_VERIFY) throw new ConflictException('Connection cannot be converted'); const provider=await this.operationalProviders(manager.getRepository(Provider)).andWhere('provider.id = :id',{id:row.providerId}).getOne(); if(!provider?.newPatientRegistrationEnabled || provider.newPatientRegistrationFeeMinor==null || !provider.newPatientRegistrationCurrency) throw new ConflictException('Provider does not support new-patient registration'); if(provider.newPatientRegistrationCurrency!==row.commercialCurrency) throw new ConflictException('Conversion currency differs from the original connection'); const paid=await this.satisfiedAmount(manager,row.id); const target=BigInt(provider.newPatientRegistrationFeeMinor); const additional=target>paid?target-paid:0n; row.currentPath=PatientProviderConnectionType.NEW_PATIENT_REGISTRATION; row.commercialAmountMinor=target.toString(); row.commercialCurrency=provider.newPatientRegistrationCurrency; row.conversionRequestedAt=new Date(); row.demographicSnapshot=this.demographics(patient); row.status=additional===0n?PatientProviderConnectionStatus.SUBMITTED:PatientProviderConnectionStatus.AWAITING_FUNDING; await manager.getRepository(PatientProviderConnection).save(row); const fundingRepo=manager.getRepository(PatientProviderConnectionFunding); await fundingRepo.save(fundingRepo.create({connectionId:row.id,purpose:PatientProviderConnectionFundingPurpose.CONVERSION_ADDITIONAL,amountMinor:additional.toString(),currency:row.commercialCurrency,status:additional===0n?PatientProviderConnectionFundingStatus.SATISFIED_FREE:PatientProviderConnectionFundingStatus.PENDING,paidAt:null})); await this.history(manager,row,PatientProviderConnectionStatus.UNABLE_TO_VERIFY,row.status,user.id,additional===0n?'CONVERSION_AUTHORIZED_FUNDING_SATISFIED':'CONVERSION_AUTHORIZED_ADDITIONAL_FUNDING_REQUIRED'); return this.map(row); }); }
 async onFundingSatisfied(manager: EntityManager, connectionId: string, actorUserId: string | null) { const row=await manager.getRepository(PatientProviderConnection).findOne({where:{id:connectionId},lock:{mode:'pessimistic_write'}}); if(!row) throw new NotFoundException('Patient connection was not found'); if(row.status===PatientProviderConnectionStatus.AWAITING_FUNDING && await this.fundingSatisfied(manager,row.id)){ const from=row.status; row.status=PatientProviderConnectionStatus.SUBMITTED; await manager.getRepository(PatientProviderConnection).save(row); await this.history(manager,row,from,row.status,actorUserId,'FUNDING_SATISFIED_SUBMITTED'); } return row; }
 private validateConfig(dto: UpdateProviderConnectionConfigDto) { for(const [enabled,amount,currency,label] of [[dto.newPatientRegistrationEnabled,dto.newPatientRegistrationFeeMinor,dto.newPatientRegistrationCurrency,'new registration'],[dto.existingPatientLinkEnabled,dto.existingPatientLinkFeeMinor,dto.existingPatientLinkCurrency,'existing link']] as const){if(enabled&&(amount==null||!currency)) throw new BadRequestException(`Complete ${label} price and currency are required`); if(amount!=null&&amount<0) throw new BadRequestException('Fees cannot be negative');} }
 private operationalProviders(repository=this.providers){return repository.createQueryBuilder('provider').where('provider.status = :active',{active:ProviderStatus.ACTIVE}).andWhere('provider.onboardingStatus = :approved',{approved:ProviderOnboardingStatus.APPROVED}).andWhere('provider.deletedAt IS NULL');}
 private async patient(userId:string){const row=await this.patients.findOne({where:{userId},withDeleted:true});if(!row||row.deletedAt||row.status!==PatientStatus.ACTIVE)throw new NotFoundException('Patient profile was not found');return row;}
 private demographics(p:Patient){return{patientReference:p.patientReference,givenName:p.givenName,familyName:p.familyName,dateOfBirth:p.dateOfBirth,phone:p.phone,email:p.email};}
 private readBuilder(){return this.connections.createQueryBuilder('connection').innerJoinAndSelect('connection.provider','provider').innerJoinAndSelect('connection.patient','patient').leftJoinAndSelect('connection.fundings','fundings');}
 private async lockProvider(m:EntityManager,providerId:string,reference:string){const row=await m.getRepository(PatientProviderConnection).findOne({where:{reference,providerId},relations:{provider:true,patient:true,fundings:true},lock:{mode:'pessimistic_write'}});if(!row)this.notFound();return row;}
 private async lockPatient(m:EntityManager,patientId:string,reference:string){const row=await m.getRepository(PatientProviderConnection).findOne({where:{reference,patientId},relations:{provider:true,patient:true,fundings:true},lock:{mode:'pessimistic_write'}});if(!row)this.notFound();return row;}
 private async fundingSatisfied(m:EntityManager,id:string){const rows=await m.getRepository(PatientProviderConnectionFunding).find({where:{connectionId:id}});return rows.length>0&&rows.every(f=>f.status===PatientProviderConnectionFundingStatus.PAID||f.status===PatientProviderConnectionFundingStatus.SATISFIED_FREE);}
 private async satisfiedAmount(m:EntityManager,id:string){const rows=await m.getRepository(PatientProviderConnectionFunding).find({where:{connectionId:id}});return rows.filter(f=>f.status===PatientProviderConnectionFundingStatus.PAID||f.status===PatientProviderConnectionFundingStatus.SATISFIED_FREE).reduce((sum,f)=>sum+BigInt(f.amountMinor),0n);}
 private async history(m:EntityManager,c:PatientProviderConnection,from:PatientProviderConnectionStatus|null,to:PatientProviderConnectionStatus,actor:string|null,reason:string,note:string|null=null){await m.getRepository(PatientProviderConnectionHistory).save({connectionId:c.id,fromStatus:from,toStatus:to,actorUserId:actor,reasonCode:reason,reasonNote:note});}
 private configView(p:Provider){return{newPatientRegistration:{enabled:p.newPatientRegistrationEnabled,feeMinor:p.newPatientRegistrationFeeMinor==null?null:Number(p.newPatientRegistrationFeeMinor),currency:p.newPatientRegistrationCurrency},existingPatientLink:{enabled:p.existingPatientLinkEnabled,feeMinor:p.existingPatientLinkFeeMinor==null?null:Number(p.existingPatientLinkFeeMinor),currency:p.existingPatientLinkCurrency}};}
 private providerView(p:Provider){return{providerReference:p.providerReference,displayName:p.displayName,providerType:p.providerType,location:{city:p.city,stateOrRegion:p.stateOrRegion,countryCode:p.countryCode}};}
 private fundingView(rows:PatientProviderConnectionFunding[]=[]){return rows.map(f=>({purpose:f.purpose,amountMinor:Number(f.amountMinor),currency:f.currency,status:f.status,paidAt:f.paidAt}));}
 private map(r:PatientProviderConnection){return{reference:r.reference,provider:this.providerView(r.provider),originalIntent:r.originalIntent,currentPath:r.currentPath,status:r.status,funding:this.fundingView(r.fundings),externalPatientReference:r.status===PatientProviderConnectionStatus.CONNECTED?r.externalPatientReference:null,consentCapturedAt:r.consentCapturedAt,conversionRequestedAt:r.conversionRequestedAt,connectedAt:r.connectedAt,createdAt:r.createdAt,updatedAt:r.updatedAt};}
 private mapProvider(r:PatientProviderConnection){return{...this.map(r),patient:{patientReference:r.demographicSnapshot.patientReference,givenName:r.demographicSnapshot.givenName,familyName:r.demographicSnapshot.familyName,dateOfBirth:r.demographicSnapshot.dateOfBirth,phone:r.demographicSnapshot.phone,email:r.demographicSnapshot.email},claimedExternalPatientReference:r.currentPath===PatientProviderConnectionType.EXISTING_PATIENT_LINK?r.claimedExternalPatientReference:null,originatedAsExistingPatientAttempt:r.originalIntent===PatientProviderConnectionType.EXISTING_PATIENT_LINK};}
 private page(items:unknown[],q:ConnectionListQueryDto,total:number){return{items,page:q.page,limit:q.limit,total,totalPages:total?Math.ceil(total/q.limit):0};}
 private notFound():never{throw new NotFoundException('Patient connection was not found');}
}
