import { BadRequestException, ConflictException } from '@nestjs/common';
import { Patient } from '../patients/entities/patient.entity'; import { Provider } from '../providers/entities/provider.entity';
import { PatientProviderConnectionFunding } from './entities/patient-provider-connection-funding.entity'; import { PatientProviderConnectionHistory } from './entities/patient-provider-connection-history.entity'; import { PatientProviderConnection } from './entities/patient-provider-connection.entity';
import { PatientProviderConnectionFundingPurpose, PatientProviderConnectionFundingStatus } from './enums/patient-provider-connection-funding.enum'; import { PatientProviderConnectionStatus } from './enums/patient-provider-connection-status.enum'; import { PatientProviderConnectionType } from './enums/patient-provider-connection-type.enum'; import { PatientProviderConnectionsService } from './patient-provider-connections.service';

describe('PatientProviderConnectionsService',()=>{
 const user:any={id:'patient-user'}; const providerUser:any={id:'provider-user'};
 const patient:any={id:'patient-id',userId:user.id,patientReference:'SC-P-000001',givenName:'Ada',familyName:'Okafor',dateOfBirth:'1990-01-01',phone:'+234800',email:'ada@example.test',status:'ACTIVE',deletedAt:null};
 let provider:any;let connection:any;let manager:any;let connectionRepo:any;let fundingRepo:any;let providerRepo:any;let patientRepo:any;let historyRepo:any;let earnings:any;let subject:PatientProviderConnectionsService;
 const qb=(one:any=null)=>{const q:any={};for(const m of ['select','where','andWhere','setLock','orderBy','addOrderBy','skip','take','innerJoinAndSelect','leftJoinAndSelect'])q[m]=jest.fn().mockReturnValue(q);q.getOne=jest.fn().mockResolvedValue(one);q.getManyAndCount=jest.fn().mockResolvedValue([[],0]);return q;};
 beforeEach(()=>{
  provider={id:'provider-id',providerReference:'SCPR-74A176AB04848BE2D3977F8493D29CE5',displayName:'Prime Hospital',providerType:'CLINIC',city:'Ibadan',stateOrRegion:'Oyo',countryCode:'NG',status:'ACTIVE',onboardingStatus:'APPROVED',deletedAt:null,newPatientRegistrationEnabled:true,newPatientRegistrationFeeMinor:'500000',newPatientRegistrationCurrency:'NGN',existingPatientLinkEnabled:true,existingPatientLinkFeeMinor:'200000',existingPatientLinkCurrency:'NGN'};
  connection={id:'connection-id',reference:'SC-PPC-ABCDEF123456',patientId:patient.id,providerId:provider.id,initiatedByUserId:user.id,originalIntent:PatientProviderConnectionType.EXISTING_PATIENT_LINK,currentPath:PatientProviderConnectionType.EXISTING_PATIENT_LINK,status:PatientProviderConnectionStatus.UNABLE_TO_VERIFY,claimedExternalPatientReference:'OLD-1',externalPatientReference:null,demographicSnapshot:{patientReference:patient.patientReference,givenName:patient.givenName,familyName:patient.familyName,dateOfBirth:patient.dateOfBirth,phone:patient.phone,email:patient.email},consentCapturedAt:new Date(),commercialAmountMinor:'200000',commercialCurrency:'NGN',verificationFailedAt:new Date(),conversionRequestedAt:null,connectedAt:null,createdAt:new Date(),updatedAt:new Date(),provider,patient,fundings:[]};
  const connectionQb=qb(null);connectionRepo={manager:null,create:jest.fn(v=>({...connection,...v})),save:jest.fn(async v=>v),findOne:jest.fn().mockResolvedValue(connection),createQueryBuilder:jest.fn(()=>connectionQb)};
  fundingRepo={create:jest.fn(v=>v),save:jest.fn(async v=>v),find:jest.fn().mockResolvedValue([{connectionId:connection.id,purpose:PatientProviderConnectionFundingPurpose.INITIAL,amountMinor:'200000',currency:'NGN',status:PatientProviderConnectionFundingStatus.PAID}]),findOne:jest.fn()};
  providerRepo={save:jest.fn(async v=>v),createQueryBuilder:jest.fn(()=>qb(provider))};patientRepo={findOne:jest.fn().mockResolvedValue(patient),findOneOrFail:jest.fn().mockResolvedValue(patient)};historyRepo={save:jest.fn(async v=>v)};manager={transaction:jest.fn(async work=>work(manager)),getRepository:jest.fn((e:any)=>e===PatientProviderConnection?connectionRepo:e===PatientProviderConnectionFunding?fundingRepo:e===PatientProviderConnectionHistory?historyRepo:e===Provider?providerRepo:e===Patient?patientRepo:{})};connectionRepo.manager=manager;earnings={markPatientConnectionPayable:jest.fn()};subject=new PatientProviderConnectionsService(connectionRepo,patientRepo,providerRepo,{resolveOperational:jest.fn().mockResolvedValue(provider)} as any,earnings);
 });
 it('requires complete enabled commercial configuration while accepting explicit zero',async()=>{await expect(subject.updateProviderConfig(providerUser,{newPatientRegistrationEnabled:true,newPatientRegistrationFeeMinor:null,newPatientRegistrationCurrency:'NGN',existingPatientLinkEnabled:false})).rejects.toBeInstanceOf(BadRequestException);await expect(subject.updateProviderConfig(providerUser,{newPatientRegistrationEnabled:true,newPatientRegistrationFeeMinor:0,newPatientRegistrationCurrency:'NGN',existingPatientLinkEnabled:false})).resolves.toMatchObject({newPatientRegistration:{enabled:true,feeMinor:0,currency:'NGN'}});});
 it('snapshots paid new-registration price and consent without trusting client money',async()=>{const result:any=await subject.startNew(user,{providerReference:provider.providerReference,consentAcknowledged:true});expect(connectionRepo.save).toHaveBeenCalledWith(expect.objectContaining({patientId:patient.id,providerId:provider.id,commercialAmountMinor:'500000',commercialCurrency:'NGN',status:PatientProviderConnectionStatus.AWAITING_FUNDING,originalIntent:PatientProviderConnectionType.NEW_PATIENT_REGISTRATION}));expect(result.status).toBe(PatientProviderConnectionStatus.AWAITING_FUNDING);expect(historyRepo.save).toHaveBeenCalled();});
 it('submits free registration without Paystack-shaped records',async()=>{provider.newPatientRegistrationFeeMinor='0';const result:any=await subject.startNew(user,{providerReference:provider.providerReference,consentAcknowledged:true});expect(result.status).toBe(PatientProviderConnectionStatus.SUBMITTED);expect(fundingRepo.save).toHaveBeenCalledWith(expect.objectContaining({amountMinor:'0',status:PatientProviderConnectionFundingStatus.SATISFIED_FREE}));});
 it('rejects disabled paths and missing consent',async()=>{await expect(subject.startNew(user,{providerReference:provider.providerReference,consentAcknowledged:false})).rejects.toBeInstanceOf(BadRequestException);provider.existingPatientLinkEnabled=false;await expect(subject.startExisting(user,{providerReference:provider.providerReference,externalPatientReference:'MRN-1',consentAcknowledged:true})).rejects.toBeInstanceOf(ConflictException);});
 it('preserves original existing-link intent and charges only positive conversion difference',async()=>{const result:any=await subject.convert(user,connection.reference,{consentAcknowledged:true});expect(connection.originalIntent).toBe(PatientProviderConnectionType.EXISTING_PATIENT_LINK);expect(connection.currentPath).toBe(PatientProviderConnectionType.NEW_PATIENT_REGISTRATION);expect(connection.commercialAmountMinor).toBe('500000');expect(fundingRepo.save).toHaveBeenCalledWith(expect.objectContaining({purpose:PatientProviderConnectionFundingPurpose.CONVERSION_ADDITIONAL,amountMinor:'300000',status:PatientProviderConnectionFundingStatus.PENDING}));expect(result.status).toBe(PatientProviderConnectionStatus.AWAITING_FUNDING);});
 it('does not charge again when registration price is already covered',async()=>{provider.newPatientRegistrationFeeMinor='150000';await subject.convert(user,connection.reference,{consentAcknowledged:true});expect(fundingRepo.save).toHaveBeenCalledWith(expect.objectContaining({amountMinor:'0',status:PatientProviderConnectionFundingStatus.SATISFIED_FREE}));expect(connection.status).toBe(PatientProviderConnectionStatus.SUBMITTED);});
 it('requires Provider confirmation, not payment, to establish CONNECTED and make earnings payable',async()=>{connection.status=PatientProviderConnectionStatus.SUBMITTED;connection.fundings=[{status:PatientProviderConnectionFundingStatus.PAID}];fundingRepo.find.mockResolvedValue(connection.fundings);const result:any=await subject.confirm(providerUser,connection.reference,{externalPatientReference:'YAB-004567'});expect(result.status).toBe(PatientProviderConnectionStatus.CONNECTED);expect(connection.externalPatientReference).toBe('YAB-004567');expect(earnings.markPatientConnectionPayable).toHaveBeenCalledWith(manager,connection.reference,providerUser.id);});
});
