export enum PatientProviderConnectionStatus {
  AWAITING_FUNDING = 'AWAITING_FUNDING',
  SUBMITTED = 'SUBMITTED',
  UNABLE_TO_VERIFY = 'UNABLE_TO_VERIFY',
  CONNECTED = 'CONNECTED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}
