/**
 * Daily health quiz. General health literacy for Nigeria, Ghana and Rwanda,
 * written to be uncontroversial and taken from WHO / CDC public guidance.
 * Not personal medical advice. Add questions to the end; never reorder or
 * change an id, because answers are stored against it.
 */
export interface HealthQuizQuestion {
  id: string;
  topic: string;
  question: string;
  options: readonly string[];
  answer: number;
  explanation: string;
  source: string;
}

export const HEALTH_QUIZ: readonly HealthQuizQuestion[] = [
  { id: 'malaria-spread', topic: 'Malaria', question: 'How is malaria passed to people?', options: ['Drinking unclean water', 'The bite of an infected mosquito', 'Shaking hands', 'Eating cold food'], answer: 1, explanation: 'Malaria is spread by the bite of an infected female Anopheles mosquito, mostly between dusk and dawn.', source: 'WHO' },
  { id: 'malaria-net', topic: 'Malaria', question: 'What is one of the best ways to avoid malaria at night?', options: ['Leaving windows open for air', 'Sleeping under an insecticide-treated net', 'Drinking bitter herbs before bed', 'Sleeping with the light on'], answer: 1, explanation: 'Insecticide-treated nets protect you from mosquito bites while you sleep, when malaria mosquitoes bite most.', source: 'WHO' },
  { id: 'mosquito-breeding', topic: 'Malaria', question: 'Where do mosquitoes lay their eggs?', options: ['Dry sand', 'Stagnant water', 'Tree bark', 'Cooking oil'], answer: 1, explanation: 'Mosquitoes breed in still water. Emptying containers, tyres and blocked gutters cuts their numbers.', source: 'WHO' },
  { id: 'bp-high', topic: 'Blood pressure', question: 'For most adults, which reading counts as high blood pressure?', options: ['110/70', '120/80', '140/90 or higher', '100/60'], answer: 2, explanation: 'Hypertension is usually diagnosed when readings on two different days are 140/90 mmHg or higher.', source: 'WHO' },
  { id: 'bp-silent', topic: 'Blood pressure', question: 'How do most people with high blood pressure feel?', options: ['Always dizzy', 'Usually nothing at all', 'Always tired', 'Always thirsty'], answer: 1, explanation: 'High blood pressure usually has no symptoms. Measuring it is the only way to know, which is why regular checks matter.', source: 'WHO' },
  { id: 'salt-limit', topic: 'Nutrition', question: 'How much salt should an adult eat in a day at most?', options: ['Under 5 g, about one teaspoon', 'About 3 teaspoons', 'As much as you like', 'One tablespoon'], answer: 0, explanation: 'Keeping salt under 5 g a day lowers blood pressure and the risk of heart disease and stroke.', source: 'WHO' },
  { id: 'activity-week', topic: 'Exercise', question: 'How much moderate activity, like brisk walking, should adults aim for each week?', options: ['30 minutes', '60 minutes', 'At least 150 minutes', 'None if you are slim'], answer: 2, explanation: 'Adults should get at least 150 minutes of moderate activity a week, for example 30 minutes on five days.', source: 'WHO' },
  { id: 'fruit-veg', topic: 'Nutrition', question: 'How much fruit and vegetables should you eat a day?', options: ['One piece a week', 'At least five portions (400 g)', 'Only on weekends', 'Fruit juice is enough'], answer: 1, explanation: 'At least 400 g, about five portions, of fruit and vegetables a day helps protect against heart disease and diabetes.', source: 'WHO' },
  { id: 'sugary-drinks', topic: 'Nutrition', question: 'Drinking a lot of sugary drinks raises your risk of…', options: ['Type 2 diabetes and weight gain', 'Malaria', 'Typhoid', 'Nothing, they are harmless'], answer: 0, explanation: 'Sugary drinks add a lot of sugar fast and are linked to weight gain, type 2 diabetes and tooth decay.', source: 'WHO' },
  { id: 'diabetes-risk', topic: 'Diabetes', question: 'Which of these raises the risk of type 2 diabetes?', options: ['Being overweight and inactive', 'Drinking water', 'Sleeping well', 'Eating vegetables'], answer: 0, explanation: 'Excess weight and too little activity are the biggest changeable risk factors for type 2 diabetes.', source: 'WHO' },
  { id: 'diabetes-harm', topic: 'Diabetes', question: 'Diabetes that is not controlled can damage…', options: ['Only the teeth', 'The eyes, kidneys, nerves and feet', 'Only the hair', 'Nothing serious'], answer: 1, explanation: 'High blood sugar over time damages blood vessels and nerves, affecting the eyes, kidneys, heart and feet.', source: 'WHO' },
  { id: 'bmi-overweight', topic: 'Weight', question: 'For adults, a BMI from which number counts as overweight?', options: ['18', '22', '25', '35'], answer: 2, explanation: 'A body mass index of 25 or more is overweight, and 30 or more is obesity.', source: 'WHO' },
  { id: 'genotype-as-as', topic: 'Sickle cell', question: 'If both parents have genotype AS, what is the chance of a child with sickle cell disease (SS) in each pregnancy?', options: ['No chance', '1 in 4', '1 in 2', 'Every child'], answer: 1, explanation: 'Each AS parent passes on S half the time, so each pregnancy has a 1 in 4 chance of SS. Knowing your genotype before marriage helps you plan.', source: 'CDC' },
  { id: 'genotype-aa', topic: 'Sickle cell', question: 'What does genotype AA mean?', options: ['You have sickle cell disease', 'You carry the sickle cell trait', 'You do not carry the sickle cell gene', 'Your blood group is A'], answer: 2, explanation: 'AA means you do not carry the sickle gene. Genotype is not the same as blood group.', source: 'CDC' },
  { id: 'genotype-test', topic: 'Sickle cell', question: 'How do you find out your genotype?', options: ['From your blood group', 'A simple blood test', 'From your height', 'You can guess it'], answer: 1, explanation: 'A haemoglobin genotype blood test tells you your genotype. You can request one on SmartClinic.', source: 'CDC' },
  { id: 'ors', topic: 'Diarrhoea', question: 'What does ORS (oral rehydration solution) do for someone with diarrhoea?', options: ['Stops the diarrhoea immediately', 'Replaces lost water and salts', 'Kills the germs', 'Nothing useful'], answer: 1, explanation: 'ORS replaces the water and salts lost in diarrhoea and prevents dangerous dehydration, especially in children.', source: 'WHO' },
  { id: 'dehydration-signs', topic: 'Hydration', question: 'Which is a sign you may be dehydrated?', options: ['Dark urine and feeling dizzy', 'Clear urine', 'Feeling full', 'Sneezing'], answer: 0, explanation: 'Thirst, dark urine, dizziness and tiredness are common signs. Drink water, and seek care if it is severe.', source: 'CDC' },
  { id: 'handwashing', topic: 'Hygiene', question: 'How long should you wash your hands with soap?', options: ['2 seconds', 'At least 20 seconds', 'Only rinse with water', 'Once a day is enough'], answer: 1, explanation: 'Scrubbing with soap for at least 20 seconds removes germs that cause diarrhoea and respiratory infections.', source: 'CDC' },
  { id: 'typhoid-spread', topic: 'Typhoid', question: 'How does typhoid usually spread?', options: ['Through contaminated food and water', 'Through mosquito bites', 'Through the air when talking', 'From sunlight'], answer: 0, explanation: 'Typhoid spreads through food or water contaminated with the bacteria. Safe water and handwashing help prevent it.', source: 'WHO' },
  { id: 'boil-water', topic: 'Hygiene', question: 'What makes doubtful drinking water safer?', options: ['Adding sugar', 'Bringing it to a rolling boil', 'Putting it in the fridge', 'Leaving it overnight'], answer: 1, explanation: 'Bringing water to a rolling boil kills most germs. Let it cool covered before drinking.', source: 'WHO' },
  { id: 'cholera-prevent', topic: 'Cholera', question: 'What prevents cholera best?', options: ['Antibiotics every week', 'Safe water, sanitation and handwashing', 'Avoiding the sun', 'Eating less'], answer: 1, explanation: 'Cholera spreads through contaminated water and food. Safe water, toilets and handwashing stop it.', source: 'WHO' },
  { id: 'lassa-spread', topic: 'Lassa fever', question: 'How do people usually catch Lassa fever?', options: ['Mosquito bites', 'Food or items contaminated by rat urine or droppings', 'Cold weather', 'Eating fruit'], answer: 1, explanation: 'Lassa fever spreads mainly through contact with food or household items contaminated by infected rats. Store food in covered containers.', source: 'WHO' },
  { id: 'antibiotics-viral', topic: 'Medicines', question: 'Do antibiotics treat the common cold?', options: ['Yes, always', 'No, colds are caused by viruses', 'Only if taken with tea', 'Only at night'], answer: 1, explanation: 'Antibiotics only work on bacteria. Using them for viral infections does not help and fuels antibiotic resistance.', source: 'WHO' },
  { id: 'antibiotics-course', topic: 'Medicines', question: 'How should you take antibiotics a health worker prescribed?', options: ['Stop as soon as you feel better', 'Exactly as prescribed', 'Share them with family', 'Take double to finish faster'], answer: 1, explanation: 'Take antibiotics exactly as prescribed and never share them. This helps them work and slows resistance.', source: 'WHO' },
  { id: 'paracetamol-liver', topic: 'Medicines', question: 'Taking too much paracetamol can damage which organ?', options: ['The liver', 'The eyes', 'The ears', 'The skin'], answer: 0, explanation: 'Paracetamol is safe at the right dose, but too much can seriously damage the liver. Check the dose on the pack.', source: 'WHO' },
  { id: 'stroke-fast', topic: 'Stroke', question: 'Face drooping, arm weakness and slurred speech can be signs of…', options: ['A stroke, so get help fast', 'Tiredness, so sleep it off', 'Hunger', 'A cold'], answer: 0, explanation: 'These are warning signs of a stroke. Getting emergency care quickly saves lives and brain function.', source: 'CDC' },
  { id: 'smoking-risk', topic: 'Smoking', question: 'Smoking raises the risk of…', options: ['Heart disease, stroke and cancer', 'Only bad breath', 'Nothing if you smoke a little', 'Malaria'], answer: 0, explanation: 'Tobacco harms almost every organ. Stopping at any age lowers the risk of heart disease, stroke and cancer.', source: 'WHO' },
  { id: 'sleep-adults', topic: 'Sleep', question: 'How much sleep do most adults need?', options: ['4 hours', '5 hours', '7 hours or more', '12 hours'], answer: 2, explanation: 'Most adults need at least 7 hours of sleep a night for good health and mood.', source: 'CDC' },
  { id: 'breastfeeding', topic: 'Children', question: 'For how long is exclusive breastfeeding recommended for babies?', options: ['The first 2 weeks', 'The first 6 months', 'Until the first tooth', 'It is not recommended'], answer: 1, explanation: 'Breast milk alone for the first 6 months gives babies the nutrition and protection they need.', source: 'WHO' },
  { id: 'measles-vaccine', topic: 'Children', question: 'What is the best protection against measles?', options: ['Vaccination', 'Staying indoors', 'Herbal baths', 'Eating eggs'], answer: 0, explanation: 'Measles vaccine is safe and very effective. Two doses give strong, lasting protection.', source: 'WHO' },
  { id: 'hep-b-vaccine', topic: 'Hepatitis', question: 'How can you prevent hepatitis B?', options: ['There is no way', 'With a vaccine', 'By drinking more water', 'By avoiding fruit'], answer: 1, explanation: 'A safe vaccine prevents hepatitis B. Ask about testing and vaccination if you have not had it.', source: 'WHO' },
  { id: 'hpv-cervical', topic: 'Women’s health', question: 'The HPV vaccine helps prevent which cancer?', options: ['Cervical cancer', 'Skin cancer', 'Lung cancer', 'Blood cancer'], answer: 0, explanation: 'HPV causes most cervical cancers. Vaccination and regular screening greatly reduce the risk.', source: 'WHO' },
  { id: 'tb-cough', topic: 'Tuberculosis', question: 'A cough that lasts how long should be checked for TB?', options: ['One day', 'Two weeks or more', 'Only if there is blood', 'Never'], answer: 1, explanation: 'A cough for two weeks or more is a key sign to get tested for tuberculosis. TB is curable with treatment.', source: 'WHO' },
  { id: 'hiv-not-spread', topic: 'HIV', question: 'Which of these does NOT spread HIV?', options: ['Sharing needles', 'Unprotected sex', 'Sharing food or shaking hands', 'From mother to baby without treatment'], answer: 2, explanation: 'HIV is not spread by everyday contact like sharing food, hugging or shaking hands.', source: 'WHO' },
  { id: 'blood-o-neg', topic: 'Blood', question: 'Which blood group can usually donate red cells to anyone?', options: ['AB positive', 'O negative', 'A positive', 'B negative'], answer: 1, explanation: 'O negative red cells can be given to people of any blood group, which is why O negative donors are so valued.', source: 'Red Cross' },
  { id: 'blood-group-vs-genotype', topic: 'Blood', question: 'Is your blood group the same as your genotype?', options: ['Yes, they are the same', 'No, they are different tests', 'Only for children', 'Only for women'], answer: 1, explanation: 'Blood group (like O+) is about blood transfusion. Genotype (like AS) is about sickle cell. Both are worth knowing.', source: 'CDC' },
  { id: 'heat-water', topic: 'Hydration', question: 'In hot weather, when should you drink water?', options: ['Only when very thirsty', 'Regularly through the day', 'Only at meals', 'Only at night'], answer: 1, explanation: 'Drink regularly in the heat, before you feel very thirsty, especially when working or exercising outdoors.', source: 'CDC' },
  { id: 'eye-sugar', topic: 'Checkups', question: 'Why get a checkup when you feel well?', options: ['There is no reason', 'Problems like high blood pressure and sugar often have no symptoms', 'To get a sick note', 'Only if you are old'], answer: 1, explanation: 'Many common conditions are silent at first. A routine check finds them early, when they are easier to treat.', source: 'WHO' },
  { id: 'alcohol', topic: 'Lifestyle', question: 'Drinking a lot of alcohol raises the risk of…', options: ['Liver disease, high blood pressure and injuries', 'Better sleep', 'Stronger bones', 'Nothing'], answer: 0, explanation: 'Heavy drinking harms the liver and heart and causes many injuries. Less is better for health.', source: 'WHO' },
  { id: 'self-medication', topic: 'Medicines', question: 'What is the risk of buying strong medicines without seeing a health worker?', options: ['None at all', 'Wrong medicine or dose, and hiding a serious illness', 'You save money and time', 'They work faster'], answer: 1, explanation: 'Self-medicating can mean the wrong drug or dose and can delay finding the real problem. Ask a pharmacist or clinician.', source: 'WHO' },
];

/** Everyone gets the same question on the same local date; it rotates through the bank. */
export function questionForDate(localDate: string): HealthQuizQuestion {
  const day = Math.floor(Date.parse(`${localDate}T00:00:00Z`) / 86_400_000);
  return HEALTH_QUIZ[((day % HEALTH_QUIZ.length) + HEALTH_QUIZ.length) % HEALTH_QUIZ.length];
}
