import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { EntityManager, Repository } from 'typeorm';
import { CareRequest } from '../care-requests/entities/care-request.entity';
import { CareRequestStatus } from '../care-requests/enums/care-request-status.enum';
import { Patient } from '../patients/entities/patient.entity';
import { PatientStatus } from '../patients/enums/patient-status.enum';
import { CareServiceDefinition } from '../providers/entities/care-service-definition.entity';
import { ProviderCareService } from '../providers/entities/provider-care-service.entity';
import { Provider } from '../providers/entities/provider.entity';
import { CurrentProviderService } from '../providers/current-provider.service';
import { ProviderOnboardingStatus } from '../providers/enums/provider-onboarding-status.enum';
import { ProviderStatus } from '../providers/enums/provider-status.enum';
import { User } from '../users/entities/user.entity';
import { AdminFastTrackQueryDto, CreateExternalFastTrackDto, FastTrackListQueryDto } from './dto/fasttrack.dto';
import { FastTrackRequestStatusHistory } from './entities/fasttrack-request-status-history.entity';
import { FastTrackRequest } from './entities/fasttrack-request.entity';
import { FastTrackSource } from './enums/fasttrack-source.enum';
import { FastTrackStatus } from './enums/fasttrack-status.enum';
import { generateFastTrackReference, isFastTrackReferenceCollision, MAX_FASTTRACK_REFERENCE_ATTEMPTS } from './fasttrack-reference';

const PATIENT_CANCELLABLE = [FastTrackStatus.SUBMITTED, FastTrackStatus.VERIFYING, FastTrackStatus.READY_FOR_PAYMENT];

@Injectable()
export class FastTrackService {
  constructor(@InjectRepository(FastTrackRequest) private readonly requests: Repository<FastTrackRequest>, @InjectRepository(Patient) private readonly patients: Repository<Patient>, private readonly currentProvider: CurrentProviderService) {}

  async createForCareRequest(user: User, careReference: string) {
    return this.retryCreate(async (manager) => {
      const patient = await this.patient(user.id, manager);
      const care = await manager.getRepository(CareRequest).findOne({ where: { reference: careReference, patientId: patient.id }, lock: { mode: 'pessimistic_write' } });
      if (!care) this.notFound('Care Request');
      if (care.status !== CareRequestStatus.PROVIDER_ACCEPTED || !care.assignedProviderId || !care.assignedProviderCareServiceId) throw new ConflictException('Care Request must have an accepted provider before FastTrack');
      if (await manager.getRepository(FastTrackRequest).createQueryBuilder('fasttrack').setLock('pessimistic_write').where('fasttrack.careRequestId = :careRequestId', { careRequestId: care.id }).andWhere('fasttrack.status NOT IN (:...terminal)', { terminal: [FastTrackStatus.REJECTED, FastTrackStatus.CANCELLED, FastTrackStatus.EXPIRED, FastTrackStatus.COMPLETED] }).getOne()) throw new ConflictException('An active FastTrack request already exists for this Care Request');
      const offering = await this.eligibleOffering(manager, care.assignedProviderId, care.assignedProviderCareServiceId, care.careServiceDefinitionId);
      const request = await this.save(manager, { userId: user.id, patientId: patient.id, source: FastTrackSource.SMARTCLINIC_CARE_REQUEST, careRequestId: care.id, providerId: offering.providerId, providerCareServiceId: offering.id, careServiceDefinitionId: offering.careServiceDefinitionId, externalAppointmentReference: null, appointmentDate: null, appointmentTime: null, department: null, doctorName: null, notes: null, feeMinor: offering.fastTrackFeeMinor!, currency: offering.fastTrackCurrency!, status: FastTrackStatus.READY_FOR_PAYMENT, verifiedAt: new Date(), paidAt: null, confirmedAt: null }, user.id, 'SMARTCLINIC_CARE_REQUEST_VERIFIED');
      return this.getMapped(manager, request.id);
    });
  }

  async createExternal(user: User, dto: CreateExternalFastTrackDto) {
    return this.retryCreate(async (manager) => {
      const patient = await this.patient(user.id, manager);
      const definition = await manager.getRepository(CareServiceDefinition).findOne({ where: { code: dto.serviceCode, isActive: true }, lock: { mode: 'pessimistic_read' } });
      if (!definition) throw new ConflictException('Selected care service is not active');
      const provider = await manager.getRepository(Provider).findOne({ where: { providerReference: dto.providerReference }, withDeleted: true, lock: { mode: 'pessimistic_read' } });
      if (!provider || provider.deletedAt || provider.status !== ProviderStatus.ACTIVE || provider.onboardingStatus !== ProviderOnboardingStatus.APPROVED) throw new ConflictException('Provider is not eligible for FastTrack');
      const offering = await manager.getRepository(ProviderCareService).findOne({ where: { providerId: provider.id, careServiceDefinitionId: definition.id, isActive: true }, lock: { mode: 'pessimistic_read' } });
      if (!offering) throw new ConflictException('Provider does not actively offer the selected service');
      await this.requireFastTrack(offering);
      const active = await manager.getRepository(FastTrackRequest).createQueryBuilder('fasttrack').setLock('pessimistic_write').where('fasttrack.userId = :userId AND fasttrack.providerId = :providerId AND LOWER(fasttrack.externalAppointmentReference) = LOWER(:externalReference)', { userId: user.id, providerId: provider.id, externalReference: dto.externalAppointmentReference }).andWhere('fasttrack.status NOT IN (:...terminal)', { terminal: [FastTrackStatus.REJECTED, FastTrackStatus.CANCELLED, FastTrackStatus.EXPIRED, FastTrackStatus.COMPLETED] }).getOne();
      if (active) throw new ConflictException('An active FastTrack request already exists for this provider appointment');
      const request = await this.save(manager, { userId: user.id, patientId: patient.id, source: FastTrackSource.EXTERNAL_APPOINTMENT, careRequestId: null, providerId: provider.id, providerCareServiceId: offering.id, careServiceDefinitionId: definition.id, externalAppointmentReference: dto.externalAppointmentReference, appointmentDate: dto.appointmentDate, appointmentTime: dto.appointmentTime ?? null, department: dto.department ?? null, doctorName: dto.doctorName ?? null, notes: dto.notes ?? null, feeMinor: offering.fastTrackFeeMinor!, currency: offering.fastTrackCurrency!, status: FastTrackStatus.VERIFYING, verifiedAt: null, paidAt: null, confirmedAt: null }, user.id, 'EXTERNAL_APPOINTMENT_AWAITING_VERIFICATION');
      return this.getMapped(manager, request.id);
    });
  }

  async listMine(user: User, query: FastTrackListQueryDto) { const patient = await this.patient(user.id); const builder = this.readBuilder().where('fasttrack.patientId = :patientId', { patientId: patient.id }); if (query.status) builder.andWhere('fasttrack.status = :status', { status: query.status }); return this.page(builder, query); }
  async getMine(user: User, reference: string) { const patient = await this.patient(user.id); const row = await this.readBuilder().where('fasttrack.reference = :reference AND fasttrack.patientId = :patientId', { reference, patientId: patient.id }).getOne(); if (!row) this.notFound(); return this.map(row); }
  async cancelMine(user: User, reference: string) { const patient = await this.patient(user.id); return this.command(reference, patient.id, null, user.id, (row) => { if (!PATIENT_CANCELLABLE.includes(row.status)) throw new ConflictException('FastTrack request can no longer be cancelled without operations review'); return [FastTrackStatus.CANCELLED, 'PATIENT_CANCELLED', null]; }); }

  async listProvider(user: User, query: FastTrackListQueryDto) { const provider = await this.operationalProvider(user); const builder = this.readBuilder().where('fasttrack.providerId = :providerId', { providerId: provider.id }); if (query.status) builder.andWhere('fasttrack.status = :status', { status: query.status }); return this.page(builder, query, true); }
  async getProvider(user: User, reference: string) { const provider = await this.operationalProvider(user); const row = await this.readBuilder().where('fasttrack.reference = :reference AND fasttrack.providerId = :providerId', { reference, providerId: provider.id }).getOne(); if (!row) this.notFound(); return this.map(row, true); }
  async providerVerify(user: User, reference: string) { const provider = await this.operationalProvider(user); return this.command(reference, null, provider.id, user.id, async (row, manager) => { if (row.source !== FastTrackSource.EXTERNAL_APPOINTMENT || row.status !== FastTrackStatus.VERIFYING) throw new ConflictException('Only a verifying external appointment can be verified'); await this.eligibleOffering(manager, provider.id, row.providerCareServiceId, row.careServiceDefinitionId); row.verifiedAt = new Date(); return [FastTrackStatus.READY_FOR_PAYMENT, 'PROVIDER_VERIFIED_APPOINTMENT', null]; }); }
  async providerReject(user: User, reference: string, reason: string) { const provider = await this.operationalProvider(user); return this.command(reference, null, provider.id, user.id, (row) => { if (row.source !== FastTrackSource.EXTERNAL_APPOINTMENT || row.status !== FastTrackStatus.VERIFYING) throw new ConflictException('Only a verifying external appointment can be rejected'); return [FastTrackStatus.REJECTED, 'PROVIDER_REJECTED_APPOINTMENT', reason]; }); }

  async adminList(query: AdminFastTrackQueryDto) { const builder = this.readBuilder(); if (query.status) builder.andWhere('fasttrack.status = :status', { status: query.status }); if (query.source) builder.andWhere('fasttrack.source = :source', { source: query.source }); if (query.providerReference) builder.andWhere('provider.providerReference = :providerReference', { providerReference: query.providerReference }); if (query.serviceCode) builder.andWhere('definition.code = :serviceCode', { serviceCode: query.serviceCode }); return this.page(builder, query); }
  async adminGet(reference: string) { const row = await this.readBuilder().leftJoinAndSelect('fasttrack.statusHistory', 'history').where('fasttrack.reference = :reference', { reference }).orderBy('history.createdAt', 'ASC').getOne(); if (!row) this.notFound(); return { ...this.map(row), statusHistory: row.statusHistory.map((h) => ({ fromStatus: h.fromStatus, toStatus: h.toStatus, reasonCode: h.reasonCode, reasonNote: h.reasonNote, createdAt: h.createdAt })) }; }
  adminReject(reference: string, actor: string, reason: string) { return this.adminTerminal(reference, actor, FastTrackStatus.REJECTED, 'OPERATIONS_REJECTED', reason); }
  adminCancel(reference: string, actor: string, reason: string) { return this.adminTerminal(reference, actor, FastTrackStatus.CANCELLED, 'OPERATIONS_CANCELLED', reason); }
  adminExpire(reference: string, actor: string, reason: string) { return this.adminTerminal(reference, actor, FastTrackStatus.EXPIRED, 'OPERATIONS_EXPIRED', reason); }

  private adminTerminal(reference: string, actor: string, status: FastTrackStatus, code: string, reason: string) { return this.command(reference, null, null, actor, (row) => { if (![FastTrackStatus.SUBMITTED, FastTrackStatus.VERIFYING, FastTrackStatus.READY_FOR_PAYMENT].includes(row.status)) throw new ConflictException('FastTrack request can no longer be changed without a refund workflow'); return [status, code, reason]; }); }
  private async command(reference: string, patientId: string | null, providerId: string | null, actor: string, resolve: (row: FastTrackRequest, manager: EntityManager) => [FastTrackStatus, string, string | null] | Promise<[FastTrackStatus, string, string | null]>) { return this.requests.manager.transaction(async (manager) => { const row = await manager.getRepository(FastTrackRequest).findOne({ where: { reference, ...(patientId ? { patientId } : {}), ...(providerId ? { providerId } : {}) }, lock: { mode: 'pessimistic_write' } }); if (!row) this.notFound(); const [to, code, note] = await resolve(row, manager); await this.transition(manager, row, to, actor, code, note); return this.getMapped(manager, row.id, providerId != null); }); }
  private async eligibleOffering(manager: EntityManager, providerId: string, offeringId: string, definitionId: string) { const offering = await manager.getRepository(ProviderCareService).findOne({ where: { id: offeringId, providerId, careServiceDefinitionId: definitionId, isActive: true }, relations: { provider: true, definition: true }, lock: { mode: 'pessimistic_read' } }); if (!offering || !offering.definition.isActive || offering.provider.deletedAt || offering.provider.status !== ProviderStatus.ACTIVE || offering.provider.onboardingStatus !== ProviderOnboardingStatus.APPROVED) throw new ConflictException('Provider service is no longer eligible for FastTrack'); await this.requireFastTrack(offering); return offering; }
  private async requireFastTrack(offering: ProviderCareService) { if (!offering.supportsFastTrack || !offering.fastTrackFeeMinor || !offering.fastTrackCurrency) throw new ConflictException('Selected provider service does not support FastTrack'); }
  private async save(manager: EntityManager, values: Partial<FastTrackRequest>, actor: string, reason: string) { const repo = manager.getRepository(FastTrackRequest); const row = await repo.save(repo.create({ ...values, reference: generateFastTrackReference() })); await this.history(manager, row.id, null, row.status, actor, reason, null); return row; }
  private async retryCreate(work: (manager: EntityManager) => Promise<unknown>) { for (let i = 0; i < MAX_FASTTRACK_REFERENCE_ATTEMPTS; i++) { try { return await this.requests.manager.transaction(work); } catch (error) { if (isFastTrackReferenceCollision(error) && i + 1 < MAX_FASTTRACK_REFERENCE_ATTEMPTS) continue; const constraint = typeof error === 'object' && error !== null && 'constraint' in error ? String((error as { constraint?: string }).constraint) : ''; if (constraint === 'UQ_fasttrack_active_care_request' || constraint === 'UQ_fasttrack_active_external_appointment') throw new ConflictException('An active FastTrack request already exists for this appointment'); throw error; } } throw new ConflictException('Unable to allocate a FastTrack reference'); }
  private async transition(manager: EntityManager, row: FastTrackRequest, to: FastTrackStatus, actor: string | null, code: string, note: string | null) { const from = row.status; row.status = to; await manager.getRepository(FastTrackRequest).save(row); await this.history(manager, row.id, from, to, actor, code, note); }
  private async history(manager: EntityManager, id: string, from: FastTrackStatus | null, to: FastTrackStatus, actor: string | null, code: string, note: string | null) { const repo = manager.getRepository(FastTrackRequestStatusHistory); await repo.save(repo.create({ fastTrackRequestId: id, fromStatus: from, toStatus: to, actorUserId: actor, reasonCode: code, reasonNote: note })); }
  private readBuilder(manager: EntityManager = this.requests.manager) { return manager.getRepository(FastTrackRequest).createQueryBuilder('fasttrack').innerJoinAndSelect('fasttrack.provider', 'provider').innerJoinAndSelect('fasttrack.careServiceDefinition', 'definition').innerJoinAndSelect('fasttrack.providerCareService', 'offering').leftJoinAndSelect('fasttrack.careRequest', 'careRequest').leftJoinAndSelect('careRequest.appointments', 'careAppointment', `careAppointment.status IN ('SCHEDULED','CONFIRMED','IN_PROGRESS','COMPLETED')`); }
  private async getMapped(manager: EntityManager, id: string, provider = false) { return this.map(await this.readBuilder(manager).where('fasttrack.id = :id', { id }).getOneOrFail(), provider); }
  private async page(builder: ReturnType<FastTrackService['readBuilder']>, query: FastTrackListQueryDto, provider = false) { builder.orderBy('fasttrack.createdAt', 'DESC').addOrderBy('fasttrack.reference', 'DESC').skip((query.page - 1) * query.limit).take(query.limit); const [rows, total] = await builder.getManyAndCount(); return { items: rows.map((r) => this.map(r, provider)), page: query.page, limit: query.limit, total, totalPages: total ? Math.ceil(total / query.limit) : 0 }; }
  private map(row: FastTrackRequest, providerView = false) { const appointment = row.careRequest?.appointments?.[0] ?? null; return { reference: row.reference, source: row.source, status: row.status, provider: { providerReference: row.provider.providerReference, displayName: row.provider.displayName, providerType: row.provider.providerType }, service: { code: row.careServiceDefinition.code, name: row.careServiceDefinition.name }, careRequestReference: row.careRequest?.reference ?? null, careAppointment: appointment ? { appointmentReference: appointment.reference, status: appointment.status, scheduledDate: appointment.scheduledDate, scheduledTimeFrom: appointment.scheduledTimeFrom, scheduledTimeTo: appointment.scheduledTimeTo, timezone: appointment.timezone } : null, externalAppointment: row.source === FastTrackSource.EXTERNAL_APPOINTMENT ? { reference: row.externalAppointmentReference, appointmentDate: row.appointmentDate, appointmentTime: row.appointmentTime, department: row.department, doctorName: row.doctorName } : null, notes: row.notes, feeMinor: Number(row.feeMinor), currency: row.currency, paymentReady: row.status === FastTrackStatus.READY_FOR_PAYMENT, verifiedAt: row.verifiedAt, paidAt: row.paidAt, confirmedAt: row.confirmedAt, createdAt: row.createdAt, updatedAt: row.updatedAt, ...(providerView ? {} : {}) }; }
  private async patient(userId: string, manager: EntityManager = this.patients.manager) { const patient = await manager.getRepository(Patient).findOne({ where: { userId }, withDeleted: true }); if (!patient || patient.deletedAt || patient.status !== PatientStatus.ACTIVE) this.notFound('Patient profile'); return patient; }
  private operationalProvider(user: User) { return this.currentProvider.resolveOperational(user); }
  private notFound(label = 'FastTrack request'): never { throw new NotFoundException(`${label} was not found`); }
}
