export enum NotificationEntityType {
  CARE_REQUEST = "CARE_REQUEST",
  CARE_APPOINTMENT = "CARE_APPOINTMENT",
  PROVIDER_PROFILE = "PROVIDER_PROFILE",
  DAILY_ROUTINE = "DAILY_ROUTINE",
  CLINICAL_ORDER = "CLINICAL_ORDER",
}
