import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, SelectQueryBuilder } from 'typeorm';
import { CurrentProviderService } from '../providers/current-provider.service';
import { ProviderLocation } from '../providers/entities/provider-location.entity';
import { User } from '../users/entities/user.entity';
import { CreateProviderServiceUnitDto, ServiceUnitListQueryDto, UpdateProviderServiceUnitDto } from './dto/provider-service-unit.dto';
import { ProviderServiceUnit } from './entities/provider-service-unit.entity';
import { ProviderServiceUnitStatus } from './enums/provider-service-unit-status.enum';
import { generateProviderServiceUnitReference } from './provider-service-unit-reference';
@Injectable()
export class ProviderServiceUnitsService {
  constructor(@InjectRepository(ProviderServiceUnit) private readonly units:Repository<ProviderServiceUnit>,private readonly current:CurrentProviderService){}
  async create(user:User,d:CreateProviderServiceUnitDto){const p=await this.current.resolveOperational(user);return this.units.manager.transaction(async m=>{const location=await this.location(m.getRepository(ProviderLocation),p.id,d.providerLocationReference);const repo=m.getRepository(ProviderServiceUnit);if(await repo.exists({where:{providerId:p.id,code:d.code}}))throw new ConflictException('Provider service-unit code already exists');const row=await repo.save(repo.create({reference:generateProviderServiceUnitReference(),providerId:p.id,code:d.code,name:d.name.trim(),type:d.type,description:d.description?.trim()||null,status:ProviderServiceUnitStatus.ACTIVE,providerLocationId:location?.id??null}));row.provider=p;row.providerLocation=location??null;return this.map(row);});}
  async list(user:User,q:ServiceUnitListQueryDto){const p=await this.current.resolveOperational(user);const b=this.builder().andWhere('unit.providerId=:providerId',{providerId:p.id});if(q.q)b.andWhere('(unit.name ILIKE :search OR unit.code ILIKE :search)',{search:`%${q.q}%`});if(q.type)b.andWhere('unit.type=:type',{type:q.type});if(q.status)b.andWhere('unit.status=:status',{status:q.status});return this.page(b,q);}
  async get(user:User,ref:string){const p=await this.current.resolveOperational(user);const row=await this.builder().andWhere('unit.reference=:ref',{ref}).andWhere('unit.providerId=:providerId',{providerId:p.id}).getOne();if(!row)this.notFound();return this.map(row);}
  async listForAdmin(providerReference:string,q:ServiceUnitListQueryDto){const b=this.builder().andWhere('provider.providerReference=:providerReference',{providerReference});if(q.q)b.andWhere('(unit.name ILIKE :search OR unit.code ILIKE :search)',{search:`%${q.q}%`});if(q.type)b.andWhere('unit.type=:type',{type:q.type});if(q.status)b.andWhere('unit.status=:status',{status:q.status});return this.page(b,q);}
  async update(user:User,ref:string,d:UpdateProviderServiceUnitDto){const p=await this.current.resolveOperational(user);return this.units.manager.transaction(async m=>{const repo=m.getRepository(ProviderServiceUnit);const row=await repo.findOne({where:{reference:ref,providerId:p.id},lock:{mode:'pessimistic_write'}});if(!row)this.notFound();if(d.code&&d.code!==row.code&&await repo.exists({where:{providerId:p.id,code:d.code}}))throw new ConflictException('Provider service-unit code already exists');const loc=d.providerLocationReference===undefined?undefined:await this.location(m.getRepository(ProviderLocation),p.id,d.providerLocationReference);if(d.code)row.code=d.code;if(d.name)row.name=d.name.trim();if(d.type)row.type=d.type;if(d.description!==undefined)row.description=d.description?.trim()||null;if(loc!==undefined)row.providerLocationId=loc?.id??null;await repo.save(row);const loaded=await this.builder(m.getRepository(ProviderServiceUnit)).andWhere('unit.id=:id',{id:row.id}).getOneOrFail();return this.map(loaded);});}
  activate(u:User,r:string){return this.status(u,r,ProviderServiceUnitStatus.ACTIVE);} deactivate(u:User,r:string){return this.status(u,r,ProviderServiceUnitStatus.INACTIVE);}
  private async status(u:User,r:string,s:ProviderServiceUnitStatus){const p=await this.current.resolveOperational(u);const row=await this.units.findOne({where:{reference:r,providerId:p.id},withDeleted:true});if(!row||row.deletedAt)this.notFound();row.status=s;await this.units.save(row);return this.get(u,r);}
  private async location(repo:Repository<ProviderLocation>,pid:string,ref:string|null|undefined):Promise<ProviderLocation|null|undefined>{if(!ref)return ref===undefined?undefined:null;const row=await repo.findOne({where:{locationReference:ref,providerId:pid,isActive:true}});if(!row)throw new ConflictException('Active Provider location was not found');return row;}
  private builder(repo=this.units){return repo.createQueryBuilder('unit').innerJoinAndSelect('unit.provider','provider').leftJoinAndSelect('unit.providerLocation','location').where('unit.deletedAt IS NULL');}
  private map(u:ProviderServiceUnit){return{reference:u.reference,code:u.code,name:u.name,type:u.type,description:u.description,status:u.status,location:u.providerLocation?{locationReference:u.providerLocation.locationReference,name:u.providerLocation.name,city:u.providerLocation.city,stateOrRegion:u.providerLocation.state,countryCode:u.providerLocation.countryCode}:null,createdAt:u.createdAt,updatedAt:u.updatedAt};}
  private async page(b:SelectQueryBuilder<ProviderServiceUnit>,q:ServiceUnitListQueryDto){b.orderBy('unit.name','ASC').addOrderBy('unit.reference','ASC').skip((q.page-1)*q.limit).take(q.limit);const[rows,total]=await b.getManyAndCount();return{items:rows.map(x=>this.map(x)),page:q.page,limit:q.limit,total,totalPages:total?Math.ceil(total/q.limit):0};}
  private notFound():never{throw new NotFoundException('Provider service unit was not found');}
}
